from types import MappingProxyType

import pytest

from ephemeraldaddy.core.sidereal import SiderealChartData
from ephemeraldaddy.core.vargas import VARGA_RULES, project_longitude, project_varga


# Fixed Lahiri D1 -> D9 reference values for the same J2000 fixture used by
# test_sidereal.py. Expected D9 values were calculated independently from the
# Parashara movable/fixed/dual Navamsha start rules and are intentionally kept
# as constants rather than generated by project_longitude().
_J2000_LAHIRI_D1 = {
    "Sun": 256.51569718931427,
    "Moon": 199.47055295238047,
    "Mercury": 248.0360525214584,
    "Venus": 217.7125758401396,
    "Mars": 304.11009083249115,
    "Jupiter": 1.3998078233926976,
    "Saturn": 16.542416469972864,
    "AS": 0.4340826001690026,
}
_J2000_NAVAMSHA = {
    "Sun": 148.6412747038284,
    "Moon": 355.2349765714242,
    "Mercury": 72.32447269312561,
    "Venus": 159.41318256125646,
    "Mars": 216.99081749242038,
    "Jupiter": 12.598270410534278,
    "Saturn": 148.88174822975577,
    "AS": 3.9067434015210227,
}


def test_only_explicitly_validated_varga_rules_are_exposed():
    assert set(VARGA_RULES) == {"D9"}
    assert VARGA_RULES["D9"].name == "Navamsha"
    with pytest.raises(ValueError):
        project_longitude(10.0, "D10")


@pytest.mark.parametrize(
    ("source_sign", "expected_start_sign"),
    [
        (0, 0),   # Aries -> Aries
        (1, 9),   # Taurus -> Capricorn
        (2, 6),   # Gemini -> Libra
        (3, 3),   # Cancer -> Cancer
        (4, 0),   # Leo -> Aries
        (5, 9),   # Virgo -> Capricorn
        (6, 6),   # Libra -> Libra
        (7, 3),   # Scorpio -> Cancer
        (8, 0),   # Sagittarius -> Aries
        (9, 9),   # Capricorn -> Capricorn
        (10, 6),  # Aquarius -> Libra
        (11, 3),  # Pisces -> Cancer
    ],
)
def test_navamsha_uses_parashara_modality_starts_for_all_source_signs(
    source_sign, expected_start_sign
):
    assert int(project_longitude(source_sign * 30.0) // 30) == expected_start_sign


@pytest.mark.parametrize("source_sign", range(12))
@pytest.mark.parametrize("segment", range(1, 9))
def test_navamsha_segment_boundaries_are_deterministic_for_every_source_sign(
    source_sign, segment
):
    source_boundary = source_sign * 30.0 + segment * (30.0 / 9.0)
    below = project_longitude(source_boundary - 1e-9)
    at = project_longitude(source_boundary)

    # Every exact segment transition advances exactly one Navamsha sign. The
    # projected longitude immediately below it must approach the boundary from
    # the previous projected sign rather than randomly flipping from float noise.
    expected_sign_at = int(at // 30.0)
    expected_previous_sign = (expected_sign_at - 1) % 12
    assert int((below + 1e-8) % 360.0 // 30.0) == expected_previous_sign
    assert at % 30.0 == pytest.approx(0.0, abs=1e-8)


def test_navamsha_wraps_at_360():
    assert project_longitude(360.0) == pytest.approx(0.0)


def test_navamsha_matches_fixed_j2000_reference_fixture():
    for body, source_longitude in _J2000_LAHIRI_D1.items():
        assert project_longitude(source_longitude, "D9") == pytest.approx(
            _J2000_NAVAMSHA[body],
            abs=1e-8,
        )


def test_varga_retains_parent_uid_and_retrograde_state_without_persistence():
    source = SiderealChartData(
        chart_uid="PARENT01",
        ayanamsha="lahiri",
        ayanamsha_degrees=24.0,
        positions=MappingProxyType({"Mercury": 10.0}),
        retrogrades=MappingProxyType({"Mercury": True}),
        ascendant=None,
        mc=None,
        house_cusps=None,
        aspects=(),
        nakshatras=MappingProxyType({}),
        source_recalculation_token="token",
    )

    projected = project_varga(source)

    assert projected.chart_uid == source.chart_uid
    assert projected.retrogrades == source.retrogrades
    assert projected.house_cusps is None
    assert not projected.uses_houses


def test_d9_projects_lagna_but_not_unvalidated_angles_or_part_of_fortune():
    source = SiderealChartData(
        chart_uid="PARENT01",
        ayanamsha="lahiri",
        ayanamsha_degrees=24.0,
        positions=MappingProxyType(
            {
                "Sun": 10.0,
                "AS": 20.0,
                "MC": 30.0,
                "DS": 200.0,
                "IC": 210.0,
                "Part of Fortune": 40.0,
            }
        ),
        retrogrades=MappingProxyType({"Sun": False}),
        ascendant=20.0,
        mc=30.0,
        house_cusps=tuple(float(index * 30) for index in range(12)),
        aspects=(),
        nakshatras=MappingProxyType({}),
        source_recalculation_token="token",
    )

    projected = project_varga(source)

    assert set(projected.positions) == {"Sun", "AS"}
    assert "MC" not in projected.positions
    assert "DS" not in projected.positions
    assert "IC" not in projected.positions
    assert "Part of Fortune" not in projected.positions
