
DND_5E_MASTER = {
    "official_wotc": {
        "Artificer": [
            "Alchemist",
            "Armorer",
            "Artillerist",
            "Battle Smith",
            "Cartographer",
        ],
        "Barbarian": [
            "Ancestral Guardian",
            "Battlerager",
            "Beast",
            "Berserker",
            "Giant",
            "Storm Herald",
            #"Totem Warrior",
            "Wild Magic",
            #"World Tree",
            "Zealot",
        ],
        "Bard": [
            "Creation",
            "Dance",
            "Eloquence",
            "Glamour",
            "Lore",
            #"Spirits",
            "Swords",
            "Valor",
            "Whispers",
        ],
        "Cleric": [
            "Arcana",
            "Death",
            "Forge",
            "Grave",
            "Knowledge",
            "Life",
            "Light",
            "Nature",
            "Order",
            "Peace",
            "Tempest",
            "Trickery",
            "Twilight",
            "War",
        ],
        "Druid": [
            "Dreams",
            "Land",
            "Moon",
            "Sea",
            "Shepherd",
            "Spores",
            "Stars",
            "Wildfire",
        ],
        "Fighter": [
            "Arcane Archer",
            #"Banneret / Purple Dragon Knight",
            "Battle Master",
            "Cavalier",
            "Champion",
            "Echo Knight",
            "Eldritch Knight",
            "Psi Warrior",
            "Rune Knight",
            "Samurai",
        ],
        "Monk": [
            #"Ascendant Dragon",
            "Astral Self",
            "Drunken Master",
            #"Kensei",
            "Long Death",
            "Mercy",
            "Open Hand",
            "Shadow",
            #"Sun Soul",
            "Warrior of the Elements / Four Elements",
        ],
        "Paladin": [
            "Ancients",
            "Conquest",
            "Crown",
            "Devotion",
            "Glory",
            "Oathbreaker",
            "Redemption",
            "Vengeance",
            "Watchers",
        ],
        "Ranger": [
            "Beast Master",
            "Drakewarden",
            "Fey Wanderer",
            "Gloom Stalker",
            "Horizon Walker",
            "Hunter",
            "Monster Slayer",
            "Swarmkeeper",
        ],
        "Rogue": [
            "Arcane Trickster",
            "Assassin",
            "Inquisitive",
            "Mastermind",
            "Phantom",
            "Scout",
            "Soulknife",
            "Swashbuckler",
            "Thief",
        ],
        "Sorcerer": [
            "Aberrant Mind",
            "Clockwork Soul",
            "Divine Soul",
            "Draconic Sorcery / Draconic Bloodline",
            "Lunar Sorcery",
            "Shadow Magic",
            "Storm Sorcery",
            "Wild Magic",
        ],
        "Warlock": [
            "Archfey",
            "Celestial",
            "Fathomless",
            "Fiend",
            "Genie",
            "Great Old One",
            "Hexblade",
            "Undead",
            "Undying",
        ],
        "Wizard": [
            "Abjuration",
            "Bladesinger",
            "Chronurgy Magic",
            "Conjuration",
            "Divination",
            "Enchantment",
            "Evocation",
            "Graviturgy Magic",
            "Illusion",
            "Necromancy",
            "Order of Scribes",
            "Transmutation",
            "War Magic",
        ],
    },

    # "partner_published_on_dndbeyond": {
    #     "Bard": [
    #         "College of Masks",
    #         "College of Requiems",
    #         "College of Shadow",
    #         "College of the Road",
    #         "College of Tragedy",
    #     ],
    #     "Cleric": [
    #         "Blood Domain",
    #         "Community Domain",
    #         "Inquisition Domain",
    #         "Keeper Domain",
    #         "Moon Domain",
    #         "Night Domain",
    #         "Shadow Domain",
    #     ],
    #     "Druid": [
    #         "Circle of the Blighted",
    #         "Circle of Shadows",
    #     ],
    #     "Fighter": [
    #         "Gunslinger",
    #         "Scofflaw",
    #     ],
    #     "Monk": [
    #         "Way of the Prophet",
    #     ],
    #     "Paladin": [
    #         "Oath of the Open Sea",
    #         "Oath of the River",
    #         "Oath of Zeal",
    #     ],
    #     "Warlock": [
    #         "Mother of Sorrows",
    #     ],
    #     "Wizard": [
    #         "Blood Magic",
    #     ],
    # },
}