# Master reference for species + subtype data and explainer text.
from typing import Dict, List

DND_STAT_EXPLANATIONS = {
    "strength": {
        "label": "Strength",
        "abbrev": "STR",
        "core_function": "Force applied through the body.",
        "plain_definition": "How much physical pressure the character can generate, resist, carry, lift, shove, drag, or impose.",
        "implies": {
            "body": [
                "muscle mass",
                "grip strength",
                "bone density",
                "raw lifting capacity",
                "shoulder/back/leg power",
                "ability to carry gear without slowing down",
                "ability to force stuck objects open",
                "ability to restrain or overpower physically",
            ],
            "movement": [
                "explosive effort",
                "climbing through force rather than finesse",
                "jumping with power",
                "swimming against resistance",
                "holding position under pressure",
            ],
            "behavior": [
                "directness",
                "preference for simple physical solutions",
                "comfort with labor",
                "confidence in bodily competence",
                "tendency to treat obstacles as movable",
            ],
            "social_signal": [
                "physically imposing presence",
                "useful in manual work",
                "visible capability",
                "may be read as blunt, practical, or intimidating depending on context",
            ],
            "survival_value": [
                "hauling supplies",
                "moving debris",
                "restraining doors",
                "carrying injured allies",
                "forcing entry or exit when mechanisms fail",
            ],
        },
        "high_score_suggests": [
            "powerful build or unusually efficient leverage",
            "confidence in contests of force",
            "usefulness in harsh terrain and manual tasks",
            "body-first problem solving",
            "less dependence on tools for basic physical obstacles",
        ],
        "low_score_suggests": [
            "limited lifting/carrying capacity",
            "poor grappling or shoving ability",
            "difficulty with climbing, swimming, dragging, or forcing objects",
            "may rely on tools, planning, allies, leverage, or magic",
            "not necessarily frailty; could be small size, injury, age, training bias, or disinterest",
        ],
        "does_not_automatically_mean": [
            "athletic grace",
            "good stamina",
            "good aim",
            "courage",
            "discipline",
            "martial skill",
            "large body size",
        ],
        "skills": ["Athletics",],
        "save_triggers": [
            "resisting being shoved, dragged, knocked prone, or restrained",
            "holding position against direct physical force",
            "escaping crushing pressure",
            "resisting forced movement from spells, monsters, traps, or terrain",
            "grabbing onto a ledge, rope, rail, or ally before being moved",
            "withstanding wind, waves, collapsing objects, or similar brute-force hazards",
        ],
        "character_archetypes": [
            "laborer",
            "wrestler",
            "bodyguard",
            "miner",
            "farmhand",
            "sailor",
            "athlete",
            "porter",
            "blacksmith",
            "brawler",
        ],
        "failure_modes": [
            "overuses force where precision would work better",
            "breaks fragile things by defaulting to pressure",
            "underestimates social, magical, or technical obstacles",
            "assumes every locked door is a personal insult from architecture",
        ],
    },

    "dexterity": {
        "label": "Dexterity",
        "abbrev": "DEX",
        "core_function": "Precision, coordination, speed, and bodily control.",
        "plain_definition": "How well the character moves, aims, reacts, balances, manipulates objects, and avoids danger through control rather than force.",
        "implies": {
            "body": [
                "fine motor control",
                "hand-eye coordination",
                "balance",
                "reflexes",
                "agility",
                "body awareness",
                "steady hands",
                "efficient footwork",
            ],
            "movement": [
                "dodging",
                "sneaking",
                "balancing on narrow surfaces",
                "moving quietly",
                "fall recovery",
                "quick direction changes",
                "precise placement of hands and feet",
            ],
            "behavior": [
                "careful physical timing",
                "preference for finesse over force",
                "quick reactions",
                "low tolerance for clumsy solutions",
                "comfort with delicate tasks",
            ],
            "social_signal": [
                "poise",
                "lightness",
                "controlled gestures",
                "good stage movement",
                "may appear evasive, graceful, twitchy, or understated depending on temperament",
            ],
            "survival_value": [
                "avoiding traps",
                "crossing unstable terrain",
                "picking locks",
                "handling fragile mechanisms",
                "escaping restraints",
                "acting before slower enemies or hazards",
            ],
        },
        "high_score_suggests": [
            "precise movement",
            "fast reaction time",
            "strong aim",
            "quiet footwork",
            "competence with tools requiring touch control",
            "physical subtlety",
        ],
        "low_score_suggests": [
            "clumsiness",
            "slow reaction time",
            "poor balance",
            "heavy or noisy movement",
            "difficulty with delicate manual tasks",
            "not necessarily weakness; could be stiffness, armor burden, injury, nerves, or lack of training",
        ],
        "does_not_automatically_mean": [
            "good endurance",
            "physical strength",
            "good judgment",
            "patience",
            "beauty",
            "stealthy personality",
            "moral subtlety",
        ],
        "skills": ["Acrobatics","Sleight of Hand","Stealth"],
        "save_triggers": [
            "dodging explosions, breath weapons, falling debris, or area effects",
            "avoiding traps that require quick movement",
            "diving away from fire, acid, lightning, falling rocks, blades, or collapsing floors",
            "keeping footing on unstable ground",
            "reacting before a hazard fully lands",
            "avoiding effects where speed and body control matter more than toughness",
        ],
        "character_archetypes": [
            "thief",
            "archer",
            "acrobat",
            "duelist",
            "dancer",
            "locksmith",
            "watchmaker",
            "knife-thrower",
            "scout",
            "street performer",
        ],
        "failure_modes": [
            "overvalues clever movement when brute simplicity would work",
            "gets cute with unnecessary flourishes",
            "depends too much on not being touched",
            "treats every room like a floor puzzle designed by an unwell architect",
        ],
    },

    "constitution": {
        "label": "Constitution",
        "abbrev": "CON",
        "core_function": "Durability, stamina, and physiological resilience.",
        "plain_definition": "How well the character’s body keeps functioning under strain, injury, exhaustion, toxins, illness, hunger, weather, and prolonged effort.",
        "implies": {
            "body": [
                "stamina",
                "pain tolerance",
                "immune resilience",
                "cardiovascular endurance",
                "recovery speed",
                "resistance to poison",
                "resistance to disease",
                "ability to keep moving while depleted",
            ],
            "movement": [
                "long-distance travel",
                "marching while encumbered",
                "holding breath",
                "enduring heat or cold",
                "maintaining effort over time",
                "surviving bad food, bad beds, and worse decisions",
            ],
            "behavior": [
                "persistence",
                "physical patience",
                "low complaint threshold or high complaint threshold depending on personality",
                "comfort with discomfort",
                "ability to continue after setbacks",
            ],
            "social_signal": [
                "hard to wear down",
                "reliable under unpleasant conditions",
                "may appear stoic, rugged, stubborn, or simply annoyingly hard to remove from the premises",
            ],
            "survival_value": [
                "surviving poison",
                "resisting exhaustion",
                "lasting through long travel",
                "maintaining concentration under strain",
                "recovering from wounds",
                "withstanding deprivation",
            ],
        },
        "high_score_suggests": [
            "staying power",
            "strong health",
            "tolerance for extremes",
            "slow to collapse",
            "less dependence on comfort",
            "good recovery after damage or depletion",
        ],
        "low_score_suggests": [
            "fragility under prolonged stress",
            "poor stamina",
            "susceptibility to illness, poison, exhaustion, or harsh environments",
            "need for rest, planning, medicine, shelter, or protective magic",
            "not necessarily smallness or weakness; could be chronic depletion, age, sheltered background, or specialized training elsewhere",
        ],
        "does_not_automatically_mean": [
            "muscle power",
            "speed",
            "bravery",
            "emotional stability",
            "healthy habits",
            "large size",
            "discipline",
        ],
        "skills": ["no real skills, only resistance"],
        "save_triggers": [
            "resisting poison",
            "resisting disease",
            "enduring exhaustion",
            "surviving extreme heat, cold, hunger, thirst, or suffocation",
            "maintaining concentration after taking damage",
            "withstanding necrotic, toxic, draining, or body-altering effects",
            "pushing the body past normal limits",
            "staying conscious or functional under physical stress",
        ],
        "character_archetypes": [
            "survivor",
            "mountaineer",
            "sailor",
            "frontier doctor",
            "endurance athlete",
            "monk",
            "drunk who somehow keeps passing the saves",
            "desert guide",
            "hard-traveling mercenary",
        ],
        "failure_modes": [
            "confuses endurance with invulnerability",
            "accepts unnecessary suffering because they can tolerate it",
            "slow to notice when others are at their limit",
            "becomes the party’s pack animal by social accident",
        ],
    },

    "intelligence": {
        "label": "Intelligence",
        "abbrev": "INT",
        "core_function": "Knowledge, analysis, memory, abstraction, and formal reasoning.",
        "plain_definition": "How well the character learns systems, recalls information, studies patterns, solves technical problems, and reasons from structured knowledge.",
        "implies": {
            "mind": [
                "book learning",
                "memory",
                "logic",
                "taxonomy",
                "mathematical reasoning",
                "historical knowledge",
                "arcane theory",
                "technical planning",
                "language study",
                "pattern recognition",
            ],
            "behavior": [
                "asks how things work",
                "categorizes information",
                "prepares through research",
                "prefers evidence over vibes",
                "may overthink when immediacy matters",
                "may seek the rule behind the event",
            ],
            "social_signal": [
                "educated speech",
                "specialized vocabulary",
                "fast explanations",
                "technical confidence",
                "may come across as precise, detached, pedantic, useful, or insufferable depending on delivery",
            ],
            "survival_value": [
                "identifying monsters",
                "decoding inscriptions",
                "understanding rituals",
                "solving puzzles",
                "using maps",
                "making plans from incomplete records",
                "detecting faulty arguments",
            ],
            "worldview": [
                "things can be studied",
                "problems have structures",
                "names and categories matter",
                "ignorance is fixable if the library has not been eaten by mold",
            ],
        },
        "high_score_suggests": [
            "strong memory",
            "systemic thinking",
            "technical competence",
            "academic or self-taught expertise",
            "strong planning capacity",
            "ability to infer hidden rules from clues",
        ],
        "low_score_suggests": [
            "limited formal education",
            "poor recall",
            "weak technical reasoning",
            "difficulty with abstract systems",
            "may solve problems through instinct, imitation, social reading, faith, or experience instead",
            "not necessarily stupidity; could be illiteracy, class background, anti-academic temperament, or practical specialization",
        ],
        "does_not_automatically_mean": [
            "common sense",
            "perception",
            "empathy",
            "good decisions under pressure",
            "social skill",
            "wisdom",
            "moral seriousness",
        ],
        "skills": ["Arcana","History","Investigation","Nature","Religion"],
        "save_triggers": [
            "disbelieving or recognizing illusions",
            "resisting effects that attack reasoning, memory, or cognition",
            "escaping psychic confusion through logic",
            "noticing contradictions in magical falsehoods",
            "resisting mind-altering effects that scramble thought rather than emotion",
            "holding onto facts, identity details, or learned structure under mental interference",
        ],
        "character_archetypes": [
            "wizard",
            "scholar",
            "engineer",
            "strategist",
            "archivist",
            "alchemist",
            "linguist",
            "investigator",
            "cartographer",
            "lawyer",
        ],
        "failure_modes": [
            "mistakes explanation for control",
            "misses obvious social cues while solving theoretical ones",
            "treats people like badly indexed documents",
            "prepares for the wrong problem with impressive confidence",
        ],
    },

    "wisdom": {
        "label": "Wisdom",
        "abbrev": "WIS",
        "core_function": "Perception, judgment, intuition, attunement, and practical discernment.",
        "plain_definition": "How well the character notices what matters, reads situations, senses danger, regulates impulses, and understands consequences without needing a lecture series.",
        "implies": {
            "mind": [
                "situational awareness",
                "intuition",
                "patience",
                "pattern sensitivity",
                "emotional discernment",
                "self-control",
                "practical judgment",
                "ability to notice inconsistencies",
                "awareness of motives",
            ],
            "body": [
                "good sensory attention",
                "calm under pressure",
                "subtle environmental tracking",
                "noticing posture, tone, tracks, weather, silence, smell, and timing",
            ],
            "behavior": [
                "thinks before acting",
                "spots danger early",
                "knows when not to speak",
                "distinguishes impulse from signal",
                "learns from consequences",
                "can accept uncertainty without becoming useless",
            ],
            "social_signal": [
                "grounded presence",
                "good listener",
                "difficult to fool",
                "may appear calm, suspicious, mature, dry, or annoyingly hard to impress",
            ],
            "survival_value": [
                "detecting ambushes",
                "reading intentions",
                "tracking creatures",
                "resisting manipulation",
                "making good calls with incomplete information",
                "understanding when the obvious option is bait",
            ],
            "worldview": [
                "not everything important is loud",
                "consequences outrank theories",
                "people reveal themselves indirectly",
                "the room usually knows before the speaker does",
            ],
        },
        "high_score_suggests": [
            "strong perception",
            "good instincts",
            "practical restraint",
            "mature judgment",
            "sensitivity to motives and environments",
            "ability to read risk",
        ],
        "low_score_suggests": [
            "poor awareness",
            "impulsiveness",
            "gullibility",
            "difficulty reading danger or motives",
            "poor self-regulation",
            "not necessarily low intelligence; may be naïveté, distraction, arrogance, sheltered upbringing, or untreated curiosity",
        ],
        "does_not_automatically_mean": [
            "formal education",
            "kindness",
            "religiosity",
            "old age",
            "social charm",
            "certainty",
            "passivity",
        ],
        "skills": ["Animal Handling","Insight","Medicine","Perception","Survival"],
        "save_triggers": [
            "resisting charm",
            "resisting fear",
            "resisting domination, compulsion, suggestion, or mental pressure",
            "seeing through emotional manipulation",
            "keeping judgment intact under supernatural influence",
            "noticing that something is wrong before fully believing it",
            "resisting effects that target instinct, perception, or willpower",
        ],
        "character_archetypes": [
            "druid",
            "cleric",
            "ranger",
            "hermit",
            "tracker",
            "midwife",
            "village elder",
            "detective",
            "animal handler",
            "survivalist",
        ],
        "failure_modes": [
            "becomes overly cautious",
            "trusts instinct when data would improve the call",
            "reads too much into ordinary details",
            "knows something is off but still has to explain it to the wizard, which is its own tax",
        ],
    },

    "charisma": {
        "label": "Charisma",
        "abbrev": "CHA",
        "core_function": "Presence, social force, self-expression, persuasion, and identity projection.",
        "plain_definition": "How strongly the character can affect others through personality, confidence, voice, beauty, menace, sincerity, performance, status, or sheer personal voltage.",
        "implies": {
            "presence": [
                "commanding attention",
                "memorable first impression",
                "expressive voice",
                "controlled persona",
                "social boldness",
                "emotional intensity",
                "performative skill",
                "confidence under scrutiny",
            ],
            "behavior": [
                "negotiates directly",
                "uses timing and tone",
                "reads audience response",
                "projects certainty",
                "can bluff, inspire, charm, unsettle, or rally",
                "may prioritize impression over precision",
            ],
            "social_signal": [
                "magnetism",
                "leadership appeal",
                "seductive or theatrical quality",
                "status fluency",
                "may be loved, feared, envied, followed, or absolutely exhausting",
            ],
            "survival_value": [
                "talking past guards",
                "de-escalating conflict",
                "gaining allies",
                "lying convincingly",
                "performing rituals or magic that requires force of self",
                "holding a group together through morale",
            ],
            "worldview": [
                "people respond to framing",
                "confidence changes outcomes",
                "presentation is not decoration; it is leverage",
                "the room is also a terrain",
            ],
        },
        "high_score_suggests": [
            "strong personal impact",
            "persuasive speech",
            "social courage",
            "clear identity projection",
            "ability to lead, deceive, entertain, or inspire",
            "magical potency for classes that cast through selfhood or pact",
        ],
        "low_score_suggests": [
            "weak social projection",
            "awkward delivery",
            "low confidence",
            "forgettable presence",
            "difficulty persuading, bluffing, or performing",
            "not necessarily ugliness or rudeness; could be shyness, flat affect, poor timing, honesty, alien manners, or lack of social practice",
        ],
        "does_not_automatically_mean": [
            "beauty",
            "kindness",
            "truthfulness",
            "leadership ethics",
            "popularity",
            "emotional intelligence",
            "good ideas",
        ],
        "skills": ["Deception","Intimidation","Performance","Persuasion"],
        "save_triggers": [
            "resisting banishment",
            "resisting possession",
            "resisting forced planar displacement",
            "resisting effects that override personal presence or self-definition",
            "holding oneself together against magic that suppresses, relocates, or rewrites agency",
            "opposing effects where force of personality matters more than logic or perception",
        ],
        "character_archetypes": [
            "bard",
            "sorcerer",
            "warlock",
            "courtier",
            "cult leader",
            "merchant",
            "actor",
            "diplomat",
            "propagandist",
            "con artist",
            "saintly nuisance",
        ],
        "failure_modes": [
            "believes persuasion can replace competence",
            "performs certainty without checking facts",
            "confuses attention with loyalty",
            "turns every tavern conversation into a one-person festival of facial expressions",
        ],
    },
}

DND_STAT_PREDICTORS = { #mostly currently theoretical, just based on lore - unless otherwise indicated
    "STR" : { #based on 33 charts:
        "signs":{
            "Capricorn":31,"Cancer":5,"Libra":11,"Gemini":5, #cumulatively, Cap is 5% positive & Can is 2% positive
            "Taurus":-14,"Leo":-12,"Pisces":-7 #cumulatively, Taurus is 3% neg & Leo is 2% neg
            }, 
        "antisigns":{}, 
        "houses":{
            5:9,7:4,1:3,6:3,
            3:-6,9:-6
        }, #cumulatively, only 6 is strong (3%) but 6 doesn't show up in the 'dominant houses top 3'
        "antihouses":{}, #cumulatively, only 3rd house is super neg, 9th is 2% neg
        "bodies":{
            "Moon":5,"Pluto":3,"Saturn":3, #cumulatively, no relevance shown
            "Venus":-6,"Jupiter":-7,"Neptune":-3 #cumulatively, only Venus is negative
        },
        "antibodies":{}, 
        "nakshatras":{
            "Punarvasu":11,"Uttara Ashadha":10,"Purva Ashadha":6,"Mula":8,"Ardra":8,"Mrigashira":6,"Chitra":12,"Revati":7,"Swati":7, #wondering if P Ash is only implicated by proximity to Ut Ash in charts... Cumulatively, only Punarvasu is 4% positive. P. Ash & Ut Ash are 2%. Everything else is 1% or less. #Similar Charts view & Database Analytics disagree about this for some reason.
            "Bharani":6,"Rohini":4,"Pushya":8,"Ashlesha":8,"Purva Phalguni":4,"Uttara Phalguni":8,"Vishakha":11,"Uttara Bhadrapada":6 #cumulatively, Ashwini & Jyestha are 2% neg. #Similar Charts view & Database Analytics disagree about this for some reason.
        }, 
        "antinakshatras":{}, 
        "positions":{
            "Sun in Capricorn":10,"Sun in Sagittarius":5,"Sun in Leo":4,"Sun in H4":18,
            "Moon in Aries":4,"Moon in Cancer":4,"Moon in Libra":5,
            "Mercury in Capricorn":10,"Mercury in Sagittarius":5,"Mercury in Aries":4,"Mercury in H5":19,
            "Venus in Capricorn":11,"Venus in Cancer":7,"Venus in Aquarius":9,"Venus in Virgo":4,
            "Mars in Cancer":8,"Mars in Taurus":4,
            "Jupiter in Gemini":8,"Jupiter in Scorpio":8,"Jupiter in Cancer":6,"Jupiter in Aries":4,"Jupiter in H5":17,
            "Saturn in Gemini":8,"Saturn in Libra":4,
            "Pluto in H6":19,
            "Ceres in H1":17,
            "Sun in Aries":-6,"Sun in Gemini":-4,"Sun in Virgo":-8,"Sun in Scorpio":-4,
            "Moon in Taurus":-5,"Moon in Sagittarius":-5,
            "Mercury in Taurus":-7,"Mercury in Leo":-4,"Mercury in Pisces":-9,
            "Venus in Libra":-7,"Venus in Leo":-7,"Venus in Pisces":-8,"Venus in Taurus":-4,
            "Mars in Leo":-6,"Mars in Virgo":-7,"Mars in Pisces":-4,
            "Jupiter in Leo":-7,"Jupiter in Virgo":-9,"Jupiter in Sagittarius":-7,"Jupiter in Pisces":-8,"Jupiter in Aquarius":-4,
            "Saturn in Taurus":-4,"Saturn in Virgo":-6,"Saturn in Sagittarius":-7,
        },
        "antipositions":{},
        "aspects":{
            "Chiron opposition Uranus":16,"Moon square Fortune":16,"Chiron trine Vesta":16,"Mars sextile Mercury":16,"Ceres sextile Rahu":16,"Ceres trine Ketu":14,"Ceres trine Moon":13,"Mercury sextile Venus":10,"Neptune square Pallas":14,"Chiron opposition Saturn":10,"Chiron square Mars":10
        },
        "antiaspects":{},
        "gates":{58,34,44,20,46,10,32,61,62,8,12,19,38},
        "antigates":{59,29,47,27,5,26,4,22,25,36,33},
        "channels": {
            (20, 34): 2,
            (10, 20): 4,
            (10, 34): 3,
            (34, 57): 2,
            (20, 57): 2,
        },
        "antichannels": {
            (6, 59): 2,
            (47, 64): 3,
        },
        "hdtypes":{"MF Generator":6},
        "antihdtypes":{"Projector":7},
        "centers":{"Spleen":3},
        "anticenters":{"Solar Plexus":3},
        "profiles":{"4/6":11,"5/1":9,"6/2":7},
        "antiprofiles":{"1/3":11,"3/5":11},
        "authorities":{"Sacral":12,"Ego Manifested":3},
        "antiauthorities":{"Emotional":14},
        "bazisigns":{},
        "antibazisigns":{},
        "color":"#cc99ff",
        "motivation":"",
        "description":"",
        "quotes":{""},
    },
    "DEX" : { #sampled 28 charts, sooo tiny selection...
        "signs":{"Taurus":8,"Gemini":6,"Virgo":12,"Sagittarius":10},
        "antisigns":{"Pisces":11,"Leo":6,"Aries":6},
        "houses":{1:7,11:4,12:5},
        "antihouses":{4:6,6:8,8:4},
        "bodies":{"Pluto":12,"Moon":6,"Saturn":8},
        "antibodies":{"Venus":20,"Jupiter":10},
        "nakshatras":{"Bharani":8,"Punarvasu":14,"Mrigashira":9,"Ardra":7,"Purva Ashadha":12,"Shravana":11,"Revati":8}, 
        "antinakshatras":{"Hasta":8,"Anuradha":5,"Mula":5,"Shatabhisha":10,"Purva Bhadrapada":5,"Uttara Phalguni":4}, 
        "positions":{
            "Sun in Taurus":5,"Sun in Gemini":4,"Sun in Sagittarius":4,
            "Moon in Gemini":10,
            "Mercury in Pisces":5,"Mercury in Cancer":7,
            "Venus in Aries":18,"Venus in Taurus":4,"Venus in Virgo":9,
            "Mars in Virgo":8,"Mars in Aquarius":7,
            "Jupiter in Virgo":5,
            "Saturn in Gemini":10,
            "Pluto in Scorpio":9,
            "Ceres in Libra":7,
            "Juno in Sagittarius":14,"Juno in Scorpio":6,
            "Pallas in Virgo":14,"Pallas in Scorpio":11,
            "Lilith in Taurus":13,"Vesta in Cancer":10,"Fortune in Scorpio":11,
            "Rahu in Capricorn":17,
        },
        "antipositions":{
            "Sun in Cancer":7,"Sun in Leo":5,"Sun in Scorpio":7,"Sun in Capricorn":5,
            "Moon in Virgo":7,"Moon in Sagittarius":4,
            "Mercury in Gemini":5,
            "Venus in Cancer":5,"Venus in Libra":6,"Venus in Sagittarius":7,"Venus in Capricorn":8,"Venus in Aquarius":6,
            "Mars in Libra":5,
            "Jupiter in Pisces":8,"Jupiter in Libra":6,
            "Saturn in Cancer":6,"Saturn in Sagittarius":6
        },
        "aspects":{},
        "antiaspects":{},
        "gates":{54:21,25:16,38:16,11:15,23:18,48:11,6:11,12:13,32:9,41:14,61:13,62:9,9:8},
        "antigates":{16:8,33:15,40:12,51:10,15:16,15:16,55:15,10:20},
        "channels": {
            (26, 44): 11,
            (6, 59): 7,
            (19, 49): 7,
            (2, 14): 8,
        },
        "antichannels": {
            (10, 34): 1,
        },
        "hdtypes":{"Generator":10},
        "antihdtypes":{"MF Generator":6},
        "centers":{"Emotional":6},
        "anticenters":{},
        "profiles":{"1/3":7,"4/6":7},
        "antiprofiles":{"3/5":4},
        "authorities":{},
        "antiauthorities":{},
        "bazisigns":{},
        "antibazisigns":{},
        "color":"#cc99ff",
        "motivation":"",
        "description":"",
        "quotes":{""},
    },
    "CON" : {
        "signs":{"Aquarius":6,"Capricorn":6,"Pisces":5},
        "antisigns":{"Libra":8,"Sagittarius":4,"Gemini":4},
        "houses":{1:6,12:6,},
        "antihouses":{11:5,9:5},
        "bodies":{"Sun":7,"Moon":4},
        "antibodies":{"Mars":5,"Uranus":4},
        "nakshatras":{"Purva Ashadha":5,"Uttara Ashadha":5,}, 
        "antinakshatras":{"Magha":7}, 
        "positions":{
            "Sun in Capricorn":9,
            "Mercury in H5":5,
            "Venus in Capricorn":6,
            "Mars in H8":4,
            "Ceres in Pisces":6,"Ceres in H4":5,
            "Lilith in H6":6,"Rahu in H2":6,"Ketu in H1":5,
        },
        "antipositions":{"Neptune in Sagittarius":8},
        "aspects":{"Moon square Fortune":7,"Lilith trine Uranus":6,"Ceres trine Vesta":5,"Pluto sextile Vesta":5,"Uranus trine Vesta":4,"DS trine Pallas":7,"MC trine Neptune":5,"Pallas conjunction Uranus":5,"IC square Vesta":5,"MC trine Lilith":5},
        "antiaspects":{"Sun semisquare Venus":6},
        "gates":{44:5,47:8,46:5,12:7,29:5,56:5,28:7,25:5,63:5,},
        "antigates":{48:5,26:5,28:8,18:6,49:5,5:6,55:4,2:5},
        "channels": {},
        "antichannels": {
            (20, 57): 5,
        },
        "hdtypes":{},
        "antihdtypes":{},
        "centers":{"Sacral":7},
        "anticenters":{"Emotional":6},
        "profiles":{"4/1":2},
        "antiprofiles":{"5/1":3},
        "authorities":{},
        "antiauthorities":{},
        "bazisigns":{},
        "antibazisigns":{},
        "color":"#cc99ff",
        "motivation":"",
        "description":"",
        "quotes":{""},
    },
    "INT" : {
        "signs":{"Gemini":8,"Cancer":5,"Libra":5,"Aries":3}, #Gem & Aries got 1% Cumulative
        "antisigns":{"Sagittarius":5},
        "houses":{3:2}, #even 1% cumulative.
        "antihouses":{}, #none
        "bodies":{"Mars":8}, #what, you were expecting Mercury?? <_<
        "antibodies":{"Mercury":6}, #lol yeah it got -6% in 'Similarities Analysis'
        "nakshatras":{"Mrigashira":6,"Punarvasu":3,"Purva Phalguni":2,"Revati":2,}, 
        "antinakshatras":{"Purva Ashadha":2}, 
        "positions":{
            "Moon in Aries":3,
            "Mercury in Scorpio":4,
            "Venus in Scorpio":5,"Mars in Capricorn":4,
            "Saturn in Gemini":4,
            "Pluto in Leo":5,
            "Neptune in Libra":4,
            "Scorpio in H1":5,"Virgo in H1":4,"Leo in H10":5,
            "Juno in Scorpio":4
        },
        "antipositions":{
            "Sun in Leo":4,
            "Saturn in Capricorn":4,
            "Neptune in Scorpio":4,
            "Pluto in Virgo":4,
            "Aquarius in H1":4,
        },
        "aspects":{
            "Chiron opposition Uranus":8,"Mars trine Fortune":5,"Fortune trine Lilith":5,"Rahu trine Sun":4,"Moon trine Uranus":5,"Juno sextile Jupiter":5,"Neptune opposition Fortune":6,"AS square Mercury":5,"Mars conjunction Moon":5,"Pallas opposition Vesta":4,"AS square Juno":5,"Fortune opposition Vesta":4,"MC sextile Fortune":5
        },
        "antiaspects":{},
        "gates":{45,62,51,12,61,36,},
        "antigates":{59,44,29,5,63,37,13},
        "channels": {
            (27, 50): 1,
            (35, 36): 1,
        },
        "antichannels": {},
        "hdtypes":{},
        "antihdtypes":{},
        "centers":{},
        "anticenters":{},
        "profiles":{"1/4":3,"3/5":4},
        "antiprofiles":{"1/3":4,"6/2":4},
        "authorities":{"Emotional":2},
        "antiauthorities":{},
        "bazisigns":{},
        "antibazisigns":{},
        "color":"#cc99ff",
        "motivation":"",
        "description":"",
        "quotes":{""},
    },
    "WIS" : {
        "signs":{"Gemini":8,"Virgo":6,"Pisces":11,"Sagittarius":4},
        "antisigns":{"Libra":8,"Scorpio":4,"Aquarius":4},
        "houses":{1:6},
        "antihouses":{9:6},
        "bodies":{},
        "antibodies":{"Saturn":3},
        "nakshatras":{"Shatabhisha":7,"Mrigashira":4,"Rohini":6,"Purva Phalguni":6,"Jyestha":4,"Mula":3}, 
        "antinakshatras":{"Ashwini":4,"Pushya":4,"Hasta":4,"Swati":6,"Uttara Bhadrapada":4}, 
        "positions":{
            "Sun in Virgo":5,"Sun in Taurus":4,"Sun in Cancer":3,"Sun in Pisces":3,
            "Moon in Pisces":7,
            "Mercury in Gemini":8,"Venus in Libra":3,"Venus in Aquarius":3,
            "Mars in Pisces":4,"Mars in Libra":3,
            "Jupiter in Virgo":5,"Jupiter in Aries":4,
            "Saturn in Pisces":4,"Saturn in Sagittarius":6,"Saturn in Cancer":4,
            "Aries in H1":8,"Scorpio in H1":4
        },
        "antipositions":{
            "Sun in Aries":7,"Sun in Leo":6,"Sun in Libra":4,
            "Moon in Sagittarius":5,"Moon in Cancer":3,
            "Mercury in Cancer":6,"Mercury in Scorpio":3,"Mercury in Taurus":3,
            "Venus in Sagittarius":3,
            "Mars in Scorpio":4,
            "Jupiter in Leo":3,"Jupiter in Scorpio":3,
            "Saturn in Libra":5,"Saturn in Aquarius":3,"Saturn in Scorpio":3,
            "Cancer in H1":8,"Libra in H1":6,"Sagittarius in H1":4
        },
        "aspects":{},
        "antiaspects":{},
        "gates":{47:11,50:5,6:6,10:7,15:8,37:10,12:7,9:6,35:7,22:6,36:6,16:5},
        "antigates":{58:5,14:5,48:5,28:6,33:6,39:6,46:8,19:8,21:6,54:7,8:7,60:11},
        "channels": {
            (37, 40): 6,
            (6, 59): 4,
            (12, 22): 6,
        },
        "antichannels": {
            (18, 58): 7,
            (28, 38): 6,
        },
        "hdtypes":{"MF Generator":6},
        "antihdtypes":{"Projector":6},
        "centers":{},
        "anticenters":{},
        "profiles":{"3/5":5,"5/1":5},
        "antiprofiles":{"1/3":4,"2/4":4,"6/2":3},
        "authorities":{"Emotional":7},
        "antiauthorities":{"Sacral":5,"Splenic":3},
        "bazisigns":{"snake":3},
        "antibazisigns":{},
        "color":"#cc99ff",
        "motivation":"",
        "description":"",
        "quotes":{""},
    },
    "CHA" : { #looked at 147-400 charts. This was tricky to nail down - because what I find charismatic differs from public opinion quite a bit. So I started with a list of who I found charismatic, found norms. Then added who I thought other people find charismatic. Found norms. Mixed the two - found nothing. Tried to pick out just the MOST charismatic from both - found nothing. Picked out who I think are most universally agreed upon as charismatic, found patterns. The criteria below represent a mix of these findings.
        "signs":{
            "Gemini":3,"Capricorn":3,"Leo":3,"Taurus":2,
            #noteworthy: Virgo & Taurus were LEAST represented in "Least CHA": "Virgo":7, "Taurus":8
        },
        "antisigns":{
            "Libra":4,"Sagittarius":8, #absent from "Most CHA"
            "Aquarius":13 #present in "Least CHA", along with Sag:10
        },
        "houses":{
            10:5,4:10,3:5,2:6,11:4 #H10 is -4% in "Least CHA", H11 is -5%, H3 is -3%, H2 is -4% & H4 is -5%, too, so doubling down...
            #H8 is -5% in "Least CHA", but neutral in "Most CHA". Maybe people don't like being set on fire, but there's no denying its brilliance. lol
            #12:5 in "Most CHA", but also 12:6 in "Least CHA". All that tells us is what we expected: 12 is shifty.
        },
        "antihouses":{
            #12:6 in "Least CHA" so I took it out of "most CHA"
        },
        "bodies":{
            "Mercury":7,"Sun":2,"Jupiter":2, #Sun was +3% in "Most CHA" but neutral in "Least CHA". Jupiter was neutral in "Most CHA" but -3% in "Least CHA", so I split the difference.
            #least present in "Least CHA": "Mercury":8,"Jupiter":3. Sun was neutral.
        },
        "antibodies":{
            "Saturn":5,"Pluto":5,"Uranus":7 #most present in "Least CHA", neutral in "Most CHA"
        },
        "nakshatras":{
            "Rohini":4,"Bharani":4,"Ashlesha":5,"Purva Ashadha":3,"Mrigashira":1,"Revati":3, #Rohini & Bharani are underrepresented in "Least CHA" as well as being overrepresented in "Most CHA"
            "Purva Phalguni":6,"Mula":5 #may be neutral in "Most CHA", but is -6% in "Least CHA"
            #"Uttara Ashadha":3 was also overrepresented in "Least CHA" so I removed it as 'polarizing but not definitive'.
        }, 
        "antinakshatras":{
            "Hasta":2, #absent from "Most CHA"
            "Anuradha":6,"Chitra":4,"Jyestha":4,"Shravana":4,
            #Uttara Ashadha is also overrepresented in "Least CHA"
        }, 
        "positions":{
            "Sun in Gemini":4,"Sun in Taurus":4,"Sun in Leo":4,"Sun in Capricorn":4,"Sun in H2":9,
            "Moon in Capricorn":4,
            "Mercury in Taurus":3,"Mercury in Leo":3,"Mercury in H3":4,"Mercury in H2":4,
            "Venus in Taurus":2,"Venus in Gemini":5,"Venus in Aries":3,
            "Mars in Aries":3,"Mars in H4":3,
            "Jupiter in Aquarius":3,"Jupiter in Sagittarius":2,"Jupiter in H6":4,
            "Saturn in H11":4,"Saturn in H10":4,
            "Neptune in H6":5,"Neptune in Leo":4,
            "Uranus in Pisces":4,"Uranus in H1":4,
            "Pluto in Cancer":7,"Pluto in H4":5,
            "Lilith in H10":4,"Juno in H4":5,"Pallas in H3":4,"Fortune in H8":5,"Chiron in Aries":4,"Vesta in Taurus":5,"Ceres in Leo":5,"Rahu in Aquarius":4,"Lilith in Sagittarius":4,
            "Cancer in H1":2,"Taurus in H10":4,"Gemini in H12":4,"Pallas in Cancer":5,"Scorpio in H4":4,
            "Chiron in Pisces":8,"Pisces in H7":6,"Neptune in Libra":6,"Pallas in Pisces":6,"Ceres in Taurus":7,"Mars in Pisces":5,
        },
        "antipositions":{
            "Sun in Aquarius":5,"Sun in Libra":3,
            "Moon in Taurus":6,"Moon in H10":5,
            "Mercury in Aquarius":4,"Mercury in Libra":4,"Mercury in H11":8,
            "Venus in Leo":2,"Venus in Sagittarius":3,"Venus in Scorpio":3,
            "Mars in Cancer":8,"Mars in H10":13,
            "Jupiter in Aries":3,"Jupiter in Gemini":6,
            "Saturn in Libra":2,"Saturn in H10":4,"Saturn in H12":6,
            "Neptune in Capricorn":4,"Neptune in H5":6,"Neptune in H7":5, 
            "Uranus in Sagittarius":5,
            "Pluto in H4":9,
            "Fortune in Leo":4,"Fortune in H7":4, #fortune in leo being a neg is interesting...what the heck's up with that?
            "Chiron in Aquarius":6,"Chiron in H12":6,"Chiron in H5":8,
            "Juno in Leo":5,"Juno in Cancer":5,
            "Pallas in H10":7, "Pallas in Aquarius":5,"Pallas in H8":7,
            "Ceres in Pisces":6,
            "Ketu in Aries":8,"Ketu in H7":8,
            "Rahu in Libra":8,"Rahu in H1":8,
            "Fortune in Aquarius":5,
            "Vesta in Leo":6,"Vesta in H12":7,
            "Pisces in H10":9,"Cancer in H1":18,
        }, 
        "aspects":{
            "Saturn trine Vesta":5,"Pallas square Uranus":3,"Chiron trine Neptune":4,"Mercury trine Moon":6,"Neptune trine Fortune":4,"Lilith trine Vesta":4,"Mars conjunction Mercury":4,"Fortune trine Venus":4,"Rahu trine Venus":4,"Chiron sextile Venus":4,"Pluto sextile Vesta":4,"Ketu square Neptune":4,"Lilith sextile Uranus":5,"Jupiter square Pluto":4,"Jupiter trine Neptune":4,"Mercury square Neptune":4,"Neptune square Saturn":4,"DS square Sun":4,"IC trine Moon":4
        },
        "antiaspects":{
            "Chiron opposition Uranus":5,"Sun semisquare Venus":6, #absent from "Most CHA"
            "Pallas square Saturn":10,"Juno square Venus":8,"Ceres square Uranus":6,"Ketu square Fortune":6,"Mars square Neptune":5,"Lilith sextile Uranus":7,"Jupiter square Vesta":6,"Saturn sextile Uranus":7,"Sun square Vesta":6,"Ketu square Vesta":5, #overpresent in "Least CHA"
            
        },
        "gates":{
            7:7,62:7,1:6,37:6,53:5,40:4,61:4,13:4, #most present in "Most CHA"
            50:7,52:6,56:6,55:6,42:6,49:8,54:7,27:9,36:6,39:10,60:10,24:5, #least present in "Least CHA"
            4:21,16:12 #both most present in "Most CHA" and least present in "Least CHA": 4:12/4:9. 16:4/16:12.
        },
        "antigates":{
            59:5,28:5,18:5,10:7,11:6,9:7,15:7, #absent from "Most CHA"
            44:6,26:9,7:9,61:10,9:9,29:5,5:5,17:9,62:5,21:6,35:5,#present in "Least CHA"
            34:11,32:10,#both least present in "Most CHA" and most present in "Least CHA": 34:5/34:6, 32:4/32:6.
        },
        "channels": {
            (2, 14): 1,
            (4, 63): 1,
        },
        "antichannels": {
            (20, 34): 6,
            (26, 44): 8,
            (47, 64): 4,
        },
        "hdtypes":{},
        "antihdtypes":{"MF Generator":4},
        "centers":{},
        "anticenters":{},
        "profiles":{"6/2":5,"5/1":5},
        "antiprofiles":{"3/5":4,"1/3":3},
        "authorities":{"Emotional":2},
        "antiauthorities":{"Sacral":2},
        "bazisigns":{},
        "antibazisigns":{},
        "color":"#cc99ff",
        "motivation":"",
        "description":"",
        "quotes":{""},
    },
}

SPECIES_FAMILIES: List[str] = [
    "Aasimar",
    "Birdfolk",
    "Canids",
    "Cosmids",
    "Cyborgs",
    "Cyclops",  #no subtypes
    "Dragons",  #no subtypes
    "Dwarf",
    "Elf",
    "Fey",
    "Genasi",
    "Spirits",
    "Gnome", #no subtypes
    "Half-orcs",  #no subtypes
    "Halfling",
    "Human",
    "Tabaxi",
    "Lizardfolk (Reptilians)",
    "Merfolk",  #no subtypes
    "Minotaur",  #no subtypes
    "Nymph",  #no subtypes
    "Ogres",  #no subtypes
    "Orcs",  #no subtypes
    "Plasmoid",  #no subtypes
    "Robots",
    "Rodentfolk",
    "Shapeshifter",
    "Skeleton",
    "Stone People (Golems)",
    "Succubi/Incubi",
    "Tiefling",
    "Triton",  #no subtypes
    "Vampire",
    "Yuan-Ti (Serpentine)",
]

FAMILY_SUBTYPES: Dict[str, List[str]] = { #note: this is not a complete species list; it only includes species with subtypes, and excluse those without, such as: cyclops, dragons, half-orcs, merfolk, nymphs, ogres, orcs, minotaurs, plasmoids, and tritons
    "Aasimar": ["Protector", "Scourge", "Fallen"],
    "Birdfolk": ["Kenku", "Owlin", "Aarakocra", "Other (non-owl, non-kenku, non-aarakocra)"],
    "Canids": ["Shepherd Dogs", "Wolfkin", "Gnolls", "Houndfolk"],
    "Cosmids": ["Chronomancers", "Abysswalkers", "Starspawned", "Cometkin", "Eclipsians"],
    "Cyborgs": ["Advanced AI", "Combat-Oriented", "Light Augmented"],
    "Dwarf": ["Duergar (Underdark)", "Mark of Warding (Eberron)", "Mountain", "Hill"],
    "Elf": ["Drow (Dark Elf)", "Shadar-Kai", "Sea Elf", "High Elf", "Wood Elf", "Eladrin (Seasonal)", "Avariel"],
    "Fey": ["Hobgoblins", "Fairies", "Firbolgs", "Satyr/Fawn", "Trolls", "Leprechauns"],
    "Genasi": ["Fire", "Air", "Earth", "Water", "Electric", "Mud", "Ice"],
    "Spirits": ["Poltergeist", "Wraith", "Ghoul", "Vagrant Spirit"],
    "Halfling": ["Ghostwise", "Stout", "Mark of Hospitality (Eberron)", "Mark of Healing (Eberron)", "Lightfoot"],
    "Human": ["Variant", "Standard"],
    "Tabaxi": ["Pantherkin", "Tigerfolk", "Other (non-panther, non-tiger, non-lion, non-cat)"],
    "Lizardfolk (Reptilians)": ["Dinoboiz", "Other"],
    "Robots": ["Autognome", "Alternative Construct"],
    "Rodentfolk": ["Squirrelfolk", "Ratfolk", "Other (non-rat, non-squirrel)"],
    "Shapeshifter": ["Changelings", "Doppelgangers", "Lycanthropes"],
    "Skeleton": ["Lich", "Skeletal Mage", "Bone Warrior"],
    "Stone People (Golems)": ["Crystalborn", "Earth-Forged Golems", "Stoneborn"],
    "Succubi/Incubi": ["Dreamweaver Succubi", "Abyssal Succubi"],
    "Tiefling": ["Feral", "Bloodlines (e.g., Asmodeus)", "Bloodlines (e.g., Zariel)", "Bloodlines (e.g., Levistus)", "Standard"],
    "Vampire": ["True Vampire", "Nosferatu", "Dhampir"],
    "Yuan-Ti (Serpentine)": ["Pureblood", "Malison"],
}

SPECIES_DESCRIPTIONS: Dict[str, str] = {
    "Aasimar": "Locals remain uneasy around these suspiciously well-lit people.",
    "Aasimar::Protector": "Seen at dawn on hilltops, looking as though they personally approved the sunrise.",
    "Aasimar::Scourge": "Town reports another glowing moral enthusiast running several degrees too hot.",
    "Aasimar::Fallen": "Former angelic type arrives with singed dignity and no patience for follow-up questions.",

    "Birdfolk": "Feathered citizens continue noticing everything, especially whatever you hoped they had missed.",
    "Birdfolk::Kenku": "Crow-person repeats your exact sentence in a tone that improves it and ruins your day.",
    "Birdfolk::Owlin": "Soft-looking night bird turns head once and suddenly owns the room.",
    "Birdfolk::Aarakocra": "Cliff-built flyer attends ground meeting with the distant courtesy of someone forced indoors by weather.",
    "Birdfolk::Other (non-owl, non-kenku, non-aarakocra)": "General bird-person category includes elegance, shrieking, side-eye, and the occasional wet-footed aristocrat.",

    "Canids": "Dog-and-wolf people enter camp already aware of the mood, the menu, and who failed to latch the gate.",
    "Canids::Shepherd Dogs": "Practical canine manager once again prevents disaster nobody else had even noticed forming.",
    "Canids::Wolfkin": "Long-limbed moonlight partisan continues finding village law charming but not binding.",
    "Canids::Gnolls": "Hyena-shaped appetite arrives laughing in a way the furniture does not appreciate.",
    "Canids::Houndfolk": "Nose-first detective sorts the room by scent and quietly loses respect for everyone in it.",

    "Cosmids": "Witnesses describe them as 'roughly person-shaped,' then admit sky may have been involved.",
    "Cosmids::Chronomancers": "Conversation with time specialist delayed slightly by the fact that they are already in next Tuesday.",
    "Cosmids::Abysswalkers": "Deep-space pedestrian makes tavern feel temporary and provincial.",
    "Cosmids::Starspawned": "Beautiful remote being continues treating brunch as an unfortunate local custom.",
    "Cosmids::Cometkin": "Fast-looking citizen appears to be leaving even while standing perfectly still.",
    "Cosmids::Eclipsians": "Threshold enthusiast enters dramatically, then becomes useless in committee for exactly the same reason.",

    "Cyborgs": "Part-person, part-machine individual continues giving off the faint impression of warranty paperwork.",
    "Cyborgs::Advanced AI": "Overdesigned intellect attends dinner and quietly converts it into a systems problem.",
    "Cyborgs::Combat-Oriented": "Reinforced model arrives with bolts, plating, and the settled confidence of a device tested on doors.",
    "Cyborgs::Light Augmented": "Subtle upgrade type keeps hearing, seeing, and tracking six things more than everyone else at table.",

    "Cyclops": "One-eyed giant again proves that depth perception is for people with smaller opinions.",
    "Dragons": "Flying treasury with self-esteem issues circles overhead, evaluating local property values.",

    "Dwarf": "Compact expert in weight, heat, and workmanship continues being right in a highly portable form.",
    "Dwarf::Duergar (Underdark)": "Underground cousin emerges pale, practical, and unimpressed by all this unnecessary daylight.",
    "Dwarf::Mark of Warding (Eberron)": "Security-minded dwarf enters room looking as though even their cufflinks require authorization.",
    "Dwarf::Mountain": "Broad alpine model proceeds uphill with the emotional flexibility of a locked gate.",
    "Dwarf::Hill": "Rounder agricultural edition smells faintly of grain, cellars, and excellent long-term planning.",

    "Elf": "Improbably composed person glides by, giving time itself the air of a solvable inconvenience.",
    "Elf::Drow (Dark Elf)": "Subterranean beauty arrives polished, dangerous, and apparently sponsored by candlelight.",
    "Elf::Shadar-Kai": "Severe shadow elf continues treating joy as a rare but acceptable scheduling exception.",
    "Elf::Sea Elf": "Marine aristocrat moves across dry land with the indulgent patience of a visiting seal expert.",
    "Elf::High Elf": "Refined elf surveys room with the weary look of someone raised among books and let down by people.",
    "Elf::Wood Elf": "Forest-built archer materializes from leaves already disapproving of your foot placement.",
    "Elf::Eladrin (Seasonal)": "Mood-based elf changes emotional climate three times before soup arrives.",
    "Elf::Avariel": "Winged elf attends mud-level society with admirable grace and visible reluctance.",

    "Fey": "Decorative natural force enters scene, immediately making cups, promises, and nicknames far too significant.",
    "Fey::Hobgoblins": "Well-lacquered fey disciplinarian continues folding banners with almost religious hostility.",
    "Fey::Fairies": "Tiny winged opportunist lands near pastry, coin purse, and unattended gossip at once.",
    "Fey::Firbolgs": "Large gentle forest person pauses long enough before speaking that everyone else's sentence seems unnecessary.",
    "Fey::Satyr/Fawn": "Goat-legged reveler once again mistakes civilization for a helpful source of cups and listeners.",
    "Fey::Trolls": "Marsh-assembled woodland issue stands near bridge looking ancestral and inconvenient.",
    "Fey::Leprechauns": "Small polished trickster exits hedge with your ring, your purse, and a stronger reading of the contract than yours.",

    "Genasi": "Elementally sponsored citizen continues bringing weather, geology, or plumbing concerns directly into the conversation.",
    "Genasi::Fire": "Warm-looking individual enters room with the confident crackle of a hearth that knows exactly what it’s doing.",
    "Genasi::Air": "Light, breezy person remains only loosely committed to chairs, gravity, and linear conversation.",
    "Genasi::Earth": "Solid mineral-flavored citizen stands there with the unhurried certainty of a hillside.",
    "Genasi::Water": "Fluid-tempered person continues slipping around social edges like a tide around pilings.",
    "Genasi::Electric": "Static-haired storm enthusiast arrives already one spark ahead of the furniture.",
    "Genasi::Mud": "Practical elemental hybrid proves, once again, that useful and glamorous are rarely close relatives.",
    "Genasi::Ice": "Cool, crystalline individual lowers room temperature and expectations with admirable efficiency.",

    "Gnome": "Small overclocked citizen arrives with bright eyes, quick hands, and the unmistakable air of someone about to 'improve' things beyond your ability to recognize or possibly use them.",
    "Half-orcs": "Large practical citizen continues combining blunt force, bruised dignity, and better judgment than locals gave them credit for.",

    "Spirits": "Formerly alive presence continues declining to let material inconvenience settle the matter.",
    "Spirits::Poltergeist": "Invisible resident reorganizes crockery with the energy of a tenant denied a security deposit.",
    "Spirits::Wraith": "Dark floating grievance enters scene and immediately lowers resale value.",
    "Spirits::Ghoul": "Gaunt cemetery regular arrives looking like table manners were somebody else’s department.",
    "Spirits::Vagrant Spirit": "Unhoused afterlife drifter hovers in doorway with the apologetic air of a person between destinations.",

    "Halfling": "Compact citizen continues solving adult problems with snacks, timing, and better sense than taller people.",
    "Halfling::Ghostwise": "Quiet little mind-reader watches group discussion the way a cat watches a complicated bug.",
    "Halfling::Stout": "Portable brick of a person remains cheerfully resistant to weather, worry, and being moved.",
    "Halfling::Mark of Hospitality (Eberron)": "Innkeeper-grade halfling somehow turns tea, blankets, and eye contact into infrastructure.",
    "Halfling::Mark of Healing (Eberron)": "Small practical healer arrives smelling of herbs, clean linen, and being taken seriously.",
    "Halfling::Lightfoot": "Friendly pocket-sized operator disappears in plain sight and returns with information.",

    "Human": "General-purpose mammal continues thriving through adaptability, confidence, and baffling amounts of improvisation.",
    "Human::Variant": "Custom-built human arrives with one suspiciously early specialization and every intention of using it.",
    "Human::Standard": "Baseline human once again demonstrates that versatility is just ambition with comfortable shoes.",

    "Tabaxi": "Feline biped enters room already evaluating curtains, shelves, and your general suitability.",
    "Tabaxi::Pantherkin": "Sleek dark cat-person glides in looking like the lighting was arranged in advance.",
    "Tabaxi::Tigerfolk": "Striped aristocrat of the food chain surveys locals with regal patience and moderate appetite.",
    "Tabaxi::Other (non-panther, non-tiger, non-lion, non-cat)": "Assorted feline model includes spots, tufted ears, and the usual whiskered confidence surplus.",

    "Lizardfolk (Reptilians)": "Scaled pragmatist continues treating emotion as interesting weather rather than management policy.",
    "Lizardfolk (Reptilians)::Dinoboiz": "Prehistoric enthusiast arrives looking like evolution briefly got theatrical.",
    "Lizardfolk (Reptilians)::Other": "General reptile edition stands very still until suddenly becoming the most relevant thing present.",

    "Merfolk": "Aquatic resident surfaces briefly to confirm that land culture is still doing several things incorrectly.",
    "Minotaur": "Bull-headed powerhouse enters hallway and instantly makes architecture feel like a personal challenge.",
    "Nymph": "Local embodiment of scenic beauty arrives looking like the landscape has begun taking sides.",
    "Ogres": "Oversized problem dressed considerately in a fig leaf lumbers in with strength, appetite, and only passing interest in refinement.",
    "Orcs": "Broad-shouldered force of nature continues treating hesitation as a hobby for weaker species.",
    "Plasmoid": "Sentient Jell-o oozes into view and immediately raises several furniture-related questions.",

    "Robots": "Constructed person continues forcing philosophers to earn their lunch.",
    "Robots::Autognome": "Clockwork little fellow bustles in with polished joints and the air of a toolbox granted citizenship.",
    "Robots::Alternative Construct": "General-purpose manufactured being stands there making 'artificial' seem oddly judgmental.",

    "Rodentfolk": "Small alert mammal-person arrives with quick hands, bright eyes, and a suspiciously efficient relationship to leftovers.",
    "Rodentfolk::Squirrelfolk": "Tree-running acrobat pauses just long enough to look busy in three directions at once.",
    "Rodentfolk::Ratfolk": "Urban survival specialist appears from somewhere structurally improbable and already knows the alleys better than you.",
    "Rodentfolk::Other (non-rat, non-squirrel)": "Miscellaneous rodent model includes whiskers, paws, vigilance, and a deeply professional relationship to storage.",

    "Shapeshifter": "Identity-flexible person continues treating fixed form as more of a suggestion than a rule.",
    "Shapeshifter::Changelings": "Socially adaptable face-swapping citizen somehow makes introductions feel provisional.",
    "Shapeshifter::Doppelgangers": "Unsettling copy specialist enters room already prepared to improve on original material.",
    "Shapeshifter::Lycanthropes": "Civilian with moon-related staffing issues again requests understanding from the village.",

    "Skeleton": "Animated bone arrangement continues proving that posture can outlive almost anything.",
    "Skeleton::Lich": "Ancient spell bureaucrat refuses retirement, decomposition, and common decency in equal measure.",
    "Skeleton::Skeletal Mage": "Bony scholar rattles in carrying exactly the sort of spellbook everyone hoped had burned years ago.",
    "Skeleton::Bone Warrior": "Minimalist soldier arrives with no spare flesh and no apparent complaints.",

    "Stone People (Golems)": "Large mineral person stands where placed and quietly improves the load-bearing profile of the district.",
    "Stone People (Golems)::Crystalborn": "Facet-covered being catches the light like a chandelier that learned boundaries.",
    "Stone People (Golems)::Earth-Forged Golems": "Purpose-built dirt-and-stone labor titan continues making architecture feel underqualified.",
    "Stone People (Golems)::Stoneborn": "Plain rock citizen remains calm, durable, and almost offensively difficult to hurry.",

    "Succubi/Incubi": "Beautifully persuasive outsider arrives with excellent posture and a completely unwholesome agenda.",
    "Succubi/Incubi::Dreamweaver Succubi": "Soft-spoken enchantress drifts in smelling of perfume, poor judgment, and late-hour decisions.",
    "Succubi/Incubi::Abyssal Succubi": "Infernal seduction specialist enters like a bad idea wearing very expensive confidence.",

    "Tiefling": "Horned citizen once again pays socially for ancestry they did not personally design.",
    "Tiefling::Feral": "Less polished infernal edition arrives looking as though civilization was tried and found negotiable.",
    "Tiefling::Bloodlines (e.g., Asmodeus)": "Classic devil-blood scion enters with formal manners and highly suspicious composure.",
    "Tiefling::Bloodlines (e.g., Zariel)": "Martial infernal descendant appears ready to settle ethics as a field exercise.",
    "Tiefling::Bloodlines (e.g., Levistus)": "Chilled, elegant tiefling continues making courtesy sound faintly refrigerated.",
    "Tiefling::Standard": "Ordinary infernal-touched citizen stands there with horns, tail, and the usual burden of other people’s imagination.",

    "Triton": "Sea-noble strides ashore with saltwater dignity and the air of an inspector from a stricter kingdom.",

    "Vampire": "Nocturnal aristocrat continues turning excellent grooming into a public hazard.",
    "Vampire::True Vampire": "Full vintage model arrives in immaculate condition and immediately starts improving the atmosphere for all the wrong reasons.",
    "Vampire::Nosferatu": "Less decorative version emerges from the dark like a tax audit with teeth.",
    "Vampire::Dhampir": "Halfway blood-suspicious citizen tries, not always convincingly, to keep things civil.",

    "Yuan-Ti (Serpentine)": "Serpentine schemer enters room with scales, composure, and no sentimental attachment to trust.",
    "Yuan-Ti (Serpentine)::Pureblood": "Mostly human-passing snake person continues relying on manners to do a great deal of dangerous work.",
    "Yuan-Ti (Serpentine)::Malison": "More visibly serpent-shaped edition arrives having given up entirely on passing and perhaps improved for it.",
}

DND_5E_MASTER = {
    "official_wotc": {
        "Artificer": [
            "Alchemist",
            "Armorer",
            "Artillerist",
            "Battle Smith",
            "Cartographer",
        ],
        "Barbarian": [
            "Ancestral Guardian",
            "Battlerager",
            "Beast",
            "Berserker",
            "Giant",
            "Storm Herald",
            #"Totem Warrior",
            "Wild Magic",
            #"World Tree",
            "Zealot",
        ],
        "Bard": [
            "Creation",
            "Dance",
            "Eloquence",
            "Glamour",
            "Lore",
            #"Spirits",
            "Swords",
            "Valor",
            "Whispers",
        ],
        "Cleric": [
            "Arcana",
            "Death",
            "Forge",
            "Grave",
            "Knowledge",
            "Life",
            "Light",
            "Nature",
            "Order",
            "Peace",
            "Tempest",
            "Trickery",
            "Twilight",
            "War",
        ],
        "Druid": [
            "Dreams",
            "Land",
            "Moon",
            "Sea",
            "Shepherd",
            "Spores",
            "Stars",
            "Wildfire",
        ],
        "Fighter": [
            "Arcane Archer",
            #"Banneret / Purple Dragon Knight",
            "Battle Master",
            "Cavalier",
            "Champion",
            "Echo Knight",
            "Eldritch Knight",
            "Psi Warrior",
            "Rune Knight",
            "Samurai",
        ],
        "Monk": [
            #"Ascendant Dragon",
            "Astral Self",
            "Drunken Master",
            #"Kensei",
            "Long Death",
            "Mercy",
            "Open Hand",
            "Shadow",
            #"Sun Soul",
            "Warrior of the Elements / Four Elements",
        ],
        "Paladin": [
            "Ancients",
            "Conquest",
            "Crown",
            "Devotion",
            "Glory",
            "Oathbreaker",
            "Redemption",
            "Vengeance",
            "Watchers",
        ],
        "Ranger": [
            "Beast Master",
            "Drakewarden",
            "Fey Wanderer",
            "Gloom Stalker",
            "Horizon Walker",
            "Hunter",
            "Monster Slayer",
            "Swarmkeeper",
        ],
        "Rogue": [
            "Arcane Trickster",
            "Assassin",
            "Inquisitive",
            "Mastermind",
            "Phantom",
            "Scout",
            "Soulknife",
            "Swashbuckler",
            "Thief",
        ],
        "Sorcerer": [
            "Aberrant Mind",
            "Clockwork Soul",
            "Divine Soul",
            "Draconic Sorcery / Draconic Bloodline",
            "Lunar Sorcery",
            "Shadow Magic",
            "Storm Sorcery",
            "Wild Magic",
        ],
        "Warlock": [
            "Archfey",
            "Celestial",
            "Fathomless",
            "Fiend",
            "Genie",
            "Great Old One",
            "Hexblade",
            "Undead",
            "Undying",
        ],
        "Wizard": [
            "Abjuration",
            "Bladesinger",
            "Chronurgy Magic",
            "Conjuration",
            "Divination",
            "Enchantment",
            "Evocation",
            "Graviturgy Magic",
            "Illusion",
            "Necromancy",
            "Order of Scribes",
            "Transmutation",
            "War Magic",
        ],
    },

    # "partner_published_on_dndbeyond": {
    #     "Bard": [
    #         "College of Masks",
    #         "College of Requiems",
    #         "College of Shadow",
    #         "College of the Road",
    #         "College of Tragedy",
    #     ],
    #     "Cleric": [
    #         "Blood Domain",
    #         "Community Domain",
    #         "Inquisition Domain",
    #         "Keeper Domain",
    #         "Moon Domain",
    #         "Night Domain",
    #         "Shadow Domain",
    #     ],
    #     "Druid": [
    #         "Circle of the Blighted",
    #         "Circle of Shadows",
    #     ],
    #     "Fighter": [
    #         "Gunslinger",
    #         "Scofflaw",
    #     ],
    #     "Monk": [
    #         "Way of the Prophet",
    #     ],
    #     "Paladin": [
    #         "Oath of the Open Sea",
    #         "Oath of the River",
    #         "Oath of Zeal",
    #     ],
    #     "Warlock": [
    #         "Mother of Sorrows",
    #     ],
    #     "Wizard": [
    #         "Blood Magic",
    #     ],
    # },
}


DND_CLASS_SUBCLASS_EXPLAINERS: Dict[str, str] = {
    "Artificer": "Local inventor creates three new tools, five new hazards, and one new reason everyone misses the old broom.",
    "Artificer::Alchemist": "Area bottle wizard once again insists the smoking beaker means it’s working.",
    "Artificer::Armorer": "Man spends eight thousand gold to become his own unpleasant furniture.",
    "Artificer::Artillerist": "Witnesses report he solved the puzzle by attaching a cannon to it.",
    "Artificer::Battle Smith": "Inventor and iron dog arrive with the settled confidence of people who have already judged your fence.",
    "Artificer::Cartographer": "Explorer unfolds map large enough to frighten weather systems.",

    "Barbarian": "Scholars continue to debate whether this is a person or a weather event with trousers.",
    "Barbarian::Ancestral Guardian": "Man attempts private outburst, accidentally includes entire family line.",
    "Barbarian::Beast": "Neighbors describe transformation as 'animal-like,' then clarify, 'No, more paperwork-destroying than that.'",
    "Barbarian::Berserker": "Experts confirm plan was solid right up until the screaming improved it.",
    "Barbarian::Giant": "Villager notes barbarian has begun solving emotional problems at a much larger scale.",
    "Barbarian::Totem Warrior": "Hunter returns from spiritual journey with new tattoos and very strong opinions about elk.",
    "Barbarian::Wild Magic": "Observers agree the rage was normal; the flying turnips were less so.",
    "Barbarian::World Tree": "Large person demonstrates that 'rooted presence' can, in fact, throw you across a ditch.",
    "Barbarian::Zealot": "Clergy admit he is technically devout, though perhaps in the way lightning is technically bright.",

    "Bard": "Traveling performer once again defeats armed opposition through melody, posture, and administrative overconfidence.",
    "Bard::Creation": "Artist produces chair, bridge, and possibly tax problem out of thin air.",
    "Bard::Dance": "Witnesses describe battle as 'less a fight than an aggressively elegant misunderstanding.'",
    "Bard::Eloquence": "Speaker convinces three guards, a magistrate, and one goat to reconsider their positions.",
    "Bard::Glamour": "Entire room briefly forgets its original goals and becomes decorative.",
    "Bard::Lore": "Historian ruins tavern mood by being correct in six languages.",
    "Bard::Swords": "Man claims he is both artist and duelist; furniture remains unconvinced.",
    "Bard::Valor": "Musician enters battlefield and, against every sensible expectation, improves it.",
    "Bard::Whispers": "Quiet entertainer compliments nobleman in tone normally reserved for extortion notes.",

    "Cleric": "Field representative of the divine arrives carrying medicine, judgment, and a travel-sized lecture.",
    "Cleric::Arcana": "Temple mage continues delicate balancing act between incense and footnotes.",
    "Cleric::Death": "Parish notes that funeral specialist is excellent company right up until dessert.",
    "Cleric::Forge": "Priest insists hammering metal is prayer, congregation reluctantly agrees after seeing breastplate.",
    "Cleric::Grave": "Local undertaker of souls requests, once again, that the dead stay organized.",
    "Cleric::Knowledge": "Scholar-priest can identify twelve heresies before breakfast and usually does.",
    "Cleric::Life": "Healer enters room smelling of herbs, soap, and the end of everyone else’s drama.",
    "Cleric::Light": "Temple radiant arrives with the subtle bedside manner of noon.",
    "Cleric::Nature": "Priest of leaves, rain, and moss continues awkward but sincere effort to civilize beetles.",
    "Cleric::Order": "Officials pleased to learn the universe finally has a middle manager.",
    "Cleric::Peace": "Diplomat achieves calm so forcefully that several combatants apologize on instinct.",
    "Cleric::Tempest": "Storm priest enters meeting with sea air, wet boots, and immediate executive authority.",
    "Cleric::Trickery": "Parishioners remain unsure whether sermon was blessed, stolen, or both.",
    "Cleric::Twilight": "Evening warden appears at sundown looking like a lamp learned boundaries.",
    "Cleric::War": "Battle priest once again confuses worship with marching orders.",

    "Druid": "Naturalist arrives wearing leaves, weather, and the settled superiority of someone trusted by owls.",
    "Druid::Dreams": "Forest mystic drifts in smelling faintly of sleep, moss, and poor scheduling.",
    "Druid::Land": "Regional specialist can identify local mud by taste, which has not improved dinner.",
    "Druid::Moon": "Woman turns into bear, then back into woman, then into bear again just to settle the tone.",
    "Druid::Sea": "Coastal sage enters room with salt in hair and tide tables in soul.",
    "Druid::Shepherd": "Quiet field manager continues organizing animals with the efficiency of a mildly magical aunt.",
    "Druid::Spores": "Mushroom enthusiast explains decomposition with a warmth others find difficult to share.",
    "Druid::Stars": "Astronomer of the marsh points at sky and somehow makes it everyone’s problem.",
    "Druid::Wildfire": "Conservationist clarifies that controlled burning is still burning.",

    "Fighter": "Career professional demonstrates ancient art of being prepared before the nonsense starts.",
    "Fighter::Battle Master": "Tactician surveys room the way a carpenter surveys warped shelving.",
    "Fighter::Cavalier": "Mounted noble arrives looking like etiquette grew a lance.",
    "Fighter::Champion": "Athlete of violence continues disappointing poets by being exactly what he appears to be.",
    "Fighter::Echo Knight": "Witnesses uncomfortable as swordsman arrives with an additional swordsman.",
    "Fighter::Eldritch Knight": "Soldier adds just enough magic to become insufferable at strategy meetings.",
    "Fighter::Psi Warrior": "Veteran defeats opponents using blade, discipline, and what doctors are calling unusual concentration.",
    "Fighter::Rune Knight": "Large armored scholar of giant script now technically counts as architecture.",
    "Fighter::Samurai": "Polite warrior bows once, judges everything, and then begins correcting the scene.",

    "Monk": "Person in simple clothes continues alarming public by needing nothing and proving it.",
    "Monk::Astral Self": "Meditator becomes so internally aligned that a second, brighter self files out to assist.",
    "Monk::Long Death": "Scholar of mortality studies life with the same expression one uses for compost.",
    "Monk::Mercy": "Masked healer strikes patient, cures patient, refuses to elaborate.",
    "Monk::Open Hand": "Technician of the obvious demonstrates that fundamentals can still humiliate you.",
    "Monk::Shadow": "Quiet figure in corner remains there until suddenly not.",
    "Monk::Warrior of the Elements": "Ascetic decides fists were good, but weather deserved a turn.",

    "Paladin": "Traveling oath in polished boots arrives to improve ethics by direct contact.",
    "Paladin::Ancients": "Knight of old groves enters glowing faintly like sunlight with legal standing.",
    "Paladin::Conquest": "Commander explains peace in the same tone others reserve for furniture assembly.",
    "Paladin::Devotion": "Painfully sincere champion continues being exactly as advertised.",
    "Paladin::Redemption": "Armed idealist requests, one last time, that everyone please behave before the steel starts.",
    "Paladin::Vengeance": "Purpose-built pursuer advances with the unhurried certainty of a bill arriving.",
    "Paladin::Watchers": "Reality’s border guard remains professionally disappointed in other dimensions.",

    "Ranger": "Field expert identifies tracks, wind, and your mistake in one smooth glance.",
    "Ranger::Beast Master": "Hunter and animal companion display the kind of teamwork that makes married couples defensive.",
    "Ranger::Drakewarden": "Practical outdoorsman solves long-standing travel concerns by acquiring small dragon.",
    "Ranger::Fey Wanderer": "Hiker returns from strange woods improved, unsettling, and faintly decorative.",
    "Ranger::Gloom Stalker": "Low-light specialist continues making caves feel personally supervised.",
    "Ranger::Horizon Walker": "Interplanar scout has boots dusty from places maps mention only in apology.",
    "Ranger::Hunter": "Classic predator type carries knife, rope, patience, and no interest in your speech.",
    "Ranger::Swarmkeeper": "Naturalist arrives attended by many tiny coworkers with no concept of personal space.",

    "Rogue": "Mobile opportunist spots latch, purse, blind angle, and weakness before you finish waving.",
    "Rogue::Arcane Trickster": "Thief adds magic to already unreasonable job description.",
    "Rogue::Phantom": "Afterlife-adjacent burglar enters room with the calm of someone on speaking terms with old regrets.",
    "Rogue::Soulknife": "Psychic cutpurse continues alarming public by being visibly unarmed right up until the stabbing.",
    "Rogue::Swashbuckler": "Peacock with rapier enters scene determined to improve it for spectators.",
    "Rogue::Thief": "Traditional specialist in windows, locks, and unattended confidence.",

    "Sorcerer": "Innately magical citizen once again demonstrates the dangers of being born preloaded.",
    "Sorcerer::Aberrant Mind": "Charming eccentric smiles politely while receiving entirely unacceptable thoughts from elsewhere.",
    "Sorcerer::Clockwork Soul": "Unnaturally orderly spellcaster continues trying to iron the universe flat.",
    "Sorcerer::Divine Soul": "Blessed prodigy appears lit from above despite being indoors.",
    "Sorcerer::Draconic Bloodline": "Scaly aristocrat of raw power enters with excellent posture and zero humility.",
    "Sorcerer::Shadow Magic": "Dimly luminous caster makes noon seem like an overstatement.",
    "Sorcerer::Wild Magic": "Public warned that caster remains talented, unstable, and technically indoors.",

    "Warlock": "Citizen signs one questionable arrangement and suddenly develops remarkable cheekbones and unusual mail.",
    "Warlock::Archfey": "Smiling court stray smells of flowers, old rules, and incoming complications.",
    "Warlock::Celestial": "Bright pact-bearer arrives looking like a hymn with backup plans.",
    "Warlock::Fathomless": "Sea-dark contractor brings brine, rope, and the feeling of deep water under floorboards.",
    "Warlock::Fiend": "Polished infernal employee continues exceeding expectations no one should have had.",
    "Warlock::Genie": "Silk-lined negotiator enters as though every room ought to have cushions and servants.",
    "Warlock::Great Old One": "Composed antenna for unacceptable truths asks whether anyone else heard that.",
    "Warlock::Hexblade": "Gloomy weapon enthusiast at last finds sword capable of matching the mood.",
    "Warlock::Undead": "Impeccably preserved pact-holder smells faintly of old coins and unfinished authority.",

    "Wizard": "Trained arcane specialist remains convinced all mysteries can be solved with notes, diagrams, and poor sleep.",
    "Wizard::Abjuration": "Magical risk manager continues wrapping reality in protective padding.",
    "Wizard::Bladesinger": "Elegant overachiever combines scholarship and swordplay just to make everyone else feel drafted.",
    "Wizard::Conjuration": "Spatial cheat produces needed object with the offensive ease of a man finding keys.",
    "Wizard::Divination": "Future-peeper keeps reacting to tomorrow during today’s lunch.",
    "Wizard::Enchantment": "Polite manipulator speaks to the mind the way a locksmith speaks to tumblers.",
    "Wizard::Evocation": "Fire-minded academic insists the blast radius was, in fact, part of the lesson.",
    "Wizard::Illusion": "Specialist in attractive nonsense remains technically honest only under hostile questioning.",
    "Wizard::Necromancy": "Grave scholar regards mortality as a research delay.",
    "Wizard::Order of Scribes": "Walking filing system continues proving that stationery can become a personality.",
    "Wizard::Transmutation": "Matter-tinkerer remains one adjustment away from fixing the chair, the world, and possibly lunch.",
}

from typing import Dict, List, Union

DND_CLASS_SUBCLASS_STATS: Dict[str, Dict[str, Union[List[str], Dict[str, List[str]]]]] = {
    "Artificer": {
        "stats": ["INT", "CON"],
        "subclasses": {
            "Alchemist": ["INT", "CON"],
            "Armorer": ["INT", "CON"],
            "Artillerist": ["INT", "CON"],
            "Battle Smith": ["INT", "CON"],
            "Cartographer": ["INT", "WIS"],
        },
    },

    "Barbarian": {
        "stats": ["STR", "CON"],
        "subclasses": {
            "Ancestral Guardian": ["STR", "CON"],
            "Beast": ["STR", "CON"],
            "Berserker": ["STR", "CON"],
            "Giant": ["STR", "CON"],
            "Totem Warrior": ["STR", "CON"],
            "Wild Magic": ["STR", "CON"],
            "World Tree": ["STR", "CON"],
            "Zealot": ["STR", "CON"],
        },
    },

    "Bard": {
        "stats": ["CHA", "DEX"],
        "subclasses": {
            "Creation": ["CHA", "DEX"],
            "Dance": ["DEX", "CHA"],
            "Eloquence": ["CHA", "DEX"],
            "Glamour": ["CHA", "DEX"],
            "Lore": ["CHA", "DEX"],
            "Swords": ["DEX", "CHA"],
            "Valor": ["CHA", "DEX"],
            "Whispers": ["CHA", "DEX"],
        },
    },

    "Cleric": {
        "stats": ["WIS", "CON"],
        "subclasses": {
            "Arcana": ["WIS", "INT"],
            "Death": ["WIS", "CON"],
            "Forge": ["WIS", "CON"],
            "Grave": ["WIS", "CON"],
            "Knowledge": ["WIS", "INT"],
            "Life": ["WIS", "CON"],
            "Light": ["WIS", "CON"],
            "Nature": ["WIS", "CON"],
            "Order": ["WIS", "CHA"],
            "Peace": ["WIS", "CON"],
            "Tempest": ["WIS", "STR"],
            "Trickery": ["WIS", "DEX"],
            "Twilight": ["WIS", "CON"],
            "War": ["WIS", "STR"],
        },
    },

    "Druid": {
        "stats": ["WIS", "CON"],
        "subclasses": {
            "Dreams": ["WIS", "CON"],
            "Land": ["WIS", "CON"],
            "Moon": ["WIS", "CON"],
            "Sea": ["WIS", "CON"],
            "Shepherd": ["WIS", "CON"],
            "Spores": ["WIS", "CON"],
            "Stars": ["WIS", "CON"],
            "Wildfire": ["WIS", "CON"],
        },
    },

    "Fighter": {
        "stats": ["STR|DEX", "CON"],
        "subclasses": {
            "Battle Master": ["STR|DEX", "CON"],
            "Cavalier": ["STR", "CON"],
            "Champion": ["STR|DEX", "CON"],
            "Echo Knight": ["STR|DEX", "CON"],
            "Eldritch Knight": ["STR|DEX", "INT"],
            "Psi Warrior": ["STR|DEX", "INT"],
            "Rune Knight": ["STR", "CON"],
            "Samurai": ["STR|DEX", "CON"],
        },
    },

    "Monk": {
        "stats": ["DEX", "WIS"],
        "subclasses": {
            "Astral Self": ["WIS", "DEX"],
            "Long Death": ["DEX", "WIS"],
            "Mercy": ["DEX", "WIS"],
            "Open Hand": ["DEX", "WIS"],
            "Shadow": ["DEX", "WIS"],
            "Warrior of the Elements": ["DEX", "WIS"],
        },
    },

    "Paladin": {
        "stats": ["STR", "CHA"],
        "subclasses": {
            "Ancients": ["CHA", "STR"],
            "Conquest": ["CHA", "STR"],
            "Devotion": ["STR", "CHA"],
            "Redemption": ["CHA", "STR"],
            "Vengeance": ["STR", "CHA"],
            "Watchers": ["CHA", "STR"],
        },
    },

    "Ranger": {
        "stats": ["DEX|STR", "WIS"],
        "subclasses": {
            "Beast Master": ["DEX|STR", "WIS"],
            "Drakewarden": ["DEX|STR", "WIS"],
            "Fey Wanderer": ["WIS", "DEX|STR"],
            "Gloom Stalker": ["DEX", "WIS"],
            "Horizon Walker": ["DEX|STR", "WIS"],
            "Hunter": ["DEX|STR", "WIS"],
            "Swarmkeeper": ["DEX|STR", "WIS"],
        },
    },

    "Rogue": {
        "stats": ["DEX", "CON"],
        "subclasses": {
            "Arcane Trickster": ["DEX", "INT"],
            "Phantom": ["DEX", "CON"],
            "Soulknife": ["DEX", "CON"],
            "Swashbuckler": ["DEX", "CHA"],
            "Thief": ["DEX", "CON"],
        },
    },

    "Sorcerer": {
        "stats": ["CHA", "CON"],
        "subclasses": {
            "Aberrant Mind": ["CHA", "CON"],
            "Clockwork Soul": ["CHA", "CON"],
            "Divine Soul": ["CHA", "CON"],
            "Draconic Bloodline": ["CHA", "CON"],
            "Shadow Magic": ["CHA", "CON"],
            "Wild Magic": ["CHA", "CON"],
        },
    },

    "Warlock": {
        "stats": ["CHA", "CON"],
        "subclasses": {
            "Archfey": ["CHA", "CON"],
            "Celestial": ["CHA", "CON"],
            "Fathomless": ["CHA", "CON"],
            "Fiend": ["CHA", "CON"],
            "Genie": ["CHA", "CON"],
            "Great Old One": ["CHA", "CON"],
            "Hexblade": ["CHA", "CON"],
            "Undead": ["CHA", "CON"],
        },
    },

    "Wizard": {
        "stats": ["INT", "CON"],
        "subclasses": {
            "Abjuration": ["INT", "CON"],
            "Bladesinger": ["INT", "DEX"],
            "Conjuration": ["INT", "CON"],
            "Divination": ["INT", "CON"],
            "Enchantment": ["INT", "CON"],
            "Evocation": ["INT", "CON"],
            "Illusion": ["INT", "CON"],
            "Necromancy": ["INT", "CON"],
            "Order of Scribes": ["INT", "CON"],
            "Transmutation": ["INT", "CON"],
        },
    },
}
