# Master reference for species + subtype data and explainer text.
from typing import Dict, List

SPECIES_FAMILIES: List[str] = [
    "Aasimar",
    "Birdfolk",
    "Canids",
    "Cosmids",
    "Cyborgs",
    "Cyclops",
    "Dragons",
    "Dwarf",
    "Elf",
    "Fey",
    "Genasi",
    "Spirits",
    "Gnome",
    "Half-orcs",
    "Halfling",
    "Human",
    "Tabaxi",
    "Lizardfolk (Reptilians)",
    "Merfolk",
    "Minotaur",
    "Nymph",
    "Ogres",
    "Orcs",
    "Plasmoid",
    "Robots",
    "Rodentfolk",
    "Shapeshifter",
    "Skeleton",
    "Stone People (Golems)",
    "Succubi/Incubi",
    "Tiefling",
    "Triton",
    "Vampire",
    "Yuan-Ti (Serpentine)",
]

FAMILY_SUBTYPES: Dict[str, List[str]] = {
    "Aasimar": ["Protector", "Scourge", "Fallen"],
    "Birdfolk": ["Kenku", "Owlin", "Aarakocra", "Other (non-owl, non-kenku, non-aarakocra)"],
    "Canids": ["Shepherd Dogs", "Wolfkin", "Gnolls", "Houndfolk"],
    "Cosmids": ["Chronomancers", "Abysswalkers", "Starspawned", "Cometkin", "Eclipsians"],
    "Cyborgs": ["Advanced AI", "Combat-Oriented", "Light Augmented"],
    "Dwarf": ["Duergar (Underdark)", "Mark of Warding (Eberron)", "Mountain", "Hill"],
    "Elf": ["Drow (Dark Elf)", "Shadar-Kai", "Sea Elf", "High Elf", "Wood Elf", "Eladrin (Seasonal)", "Avariel"],
    "Fey": ["Hobgoblins", "Fairies", "Firbolgs", "Satyr/Fawn", "Trolls", "Leprechauns"],
    "Genasi": ["Fire", "Air", "Earth", "Water", "Electric", "Mud", "Ice"],
    "Spirits": ["Poltergeist", "Wraith", "Ghoul", "Vagrant Spirit"],
    "Halfling": ["Ghostwise", "Stout", "Mark of Hospitality (Eberron)", "Mark of Healing (Eberron)", "Lightfoot"],
    "Human": ["Variant", "Standard"],
    "Tabaxi": ["Pantherkin", "Tigerfolk", "Other (non-panther, non-tiger, non-lion, non-cat)"],
    "Lizardfolk (Reptilians)": ["Dinoboiz", "Other"],
    "Robots": ["Autognome", "Alternative Construct"],
    "Rodentfolk": ["Squirrelfolk", "Ratfolk", "Other (non-rat, non-squirrel)"],
    "Shapeshifter": ["Changelings", "Doppelgangers", "Lycanthropes"],
    "Skeleton": ["Lich", "Skeletal Mage", "Bone Warrior"],
    "Stone People (Golems)": ["Crystalborn", "Earth-Forged Golems", "Stoneborn"],
    "Succubi/Incubi": ["Dreamweaver Succubi", "Abyssal Succubi"],
    "Tiefling": ["Feral", "Bloodlines (e.g., Asmodeus)", "Bloodlines (e.g., Zariel)", "Bloodlines (e.g., Levistus)", "Standard"],
    "Vampire": ["True Vampire", "Nosferatu", "Dhampir"],
    "Yuan-Ti (Serpentine)": ["Pureblood", "Malison"],
}

SPECIES_SUBVARIANT_EXPLAINER_TEMPLATE: Dict[str, str] = {
    "Aasimar": "Aasimar look like people who have been lit slightly better than the rest of us, as if the air around them has been quietly retouched. They tend to smell faintly of cold morning air, old linen, and the last inch of beeswax candle. Being near one can feel oddly clarifying, which is pleasant right up until they start speaking as though conscience were a public utility.",
    "Aasimar::Protector": "Protector aasimar have the unmistakable air of someone who would arrive on a hilltop at dawn for no practical reason and somehow make it seem justified. Their presence has the clean, thin quality of high altitude: bright, dry, and a little severe. They are reassuring in the way a well-built bridge is reassuring, which is lovely unless you were hoping for mischief.",
    "Aasimar::Scourge": "Scourge aasimar do not so much glow as overheat. Their beauty has the hard, white edge of metal left too long in a forge, and the room around them can feel one bad mood away from becoming a sermon. They are what happens when moral clarity decides that subtlety is for later.",
    "Aasimar::Fallen": "Fallen aasimar look like grace that missed a step and kept walking. There is usually something singed about them, not literally, but in the sense that their elegance has acquired corners, smoke, and a private grievance. They give off the feeling of cathedral stone after a storm: still grand, still cold, and no longer taking questions.",

    "Birdfolk": "Birdfolk are the general case for feathered humanoids: beaks, talons, wings, down, pinfeathers, head-cocks, and the distinct sense that they noticed three things behind you while you were still introducing yourself. They often smell of sun-warmed feathers, dust, rainwater, and whatever passes for grooming in a species that regards bathing as both practical and theatrical.",
    "Birdfolk::Kenku": "Kenku are compact, dark-feathered, bright-eyed little opportunists who move with the start-stop precision of creatures that have spent centuries surviving by noticing absolutely everything. Their voices often sound borrowed because, in a sense, they are. Being around one feels like standing in an alley behind a theatre and realizing the alley is smarter than the play.",
    "Birdfolk::Owlin": "Owlin tend to look soft until they turn their heads and remind you that softness and predation have never actually been enemies. They smell faintly of dry bark, old paper, dust, and night air through a half-open window. They experience the world as a series of quiet motions in darkness, which makes daylight society seem to them exactly as clumsy as it is.",
    "Birdfolk::Aarakocra": "Aarakocra have the rangy, weather-polished look of things built by cliff edges and wind shear rather than by towns. Their feathers often carry the smell of clean air, stone, and distant rain. They experience ground life the way sailors experience long meetings in basements: with patience, but not respect.",
    "Birdfolk::Other (non-owl, non-kenku, non-aarakocra)": "The rest of birdfolk run the full avian catalog: glossy, scruffy, shrill, stately, ridiculous, impeccable, and everything between. Some arrive all swan-neck elegance, some all gull-nerved audacity, some with the grave self-importance of a heron in shallow water. As a class, they are ornamental only until they open their beaks.",

    "Canids": "Canids are dog-, wolf-, jackal-, and hyena-flavored humanoids built around nose, ear, pack, pace, and the useful belief that the world usually means something if you sniff it long enough. They often smell of fur, leather, weather, woodsmoke, and the outer edge of the camp. They tend to experience a place socially first and aesthetically second, which frankly is how most places deserve to be experienced.",
    "Canids::Shepherd Dogs": "Shepherd-dog folk look like practical competence grew a coat and learned to stand upright. They have the alert, domestic, faintly managerial energy of a creature that has spent generations preventing disorder and being rewarded with more disorder. They notice open gates, fraying ropes, unattended children, and your bad plan before you do.",
    "Canids::Wolfkin": "Wolfkin are all rangy limbs, watchful eyes, winter breath, and the feeling that they would trust moonlight over municipal law. They smell of pine bark, cold fur, damp earth, and distance. They experience the world in terms of border, pursuit, silence, and hunger, which makes taverns feel to them like an odd and temporary truce.",
    "Canids::Gnolls": "Gnolls have the rough, powerful, slightly disreputable look of a laugh that got teeth involved. Their presence often brings with it the smell of hide, dust, old blood, sun-baked grass, and bad judgment. They experience appetite as a structural principle rather than a passing inconvenience, which is very dynamic of them and very tiresome for everyone else.",
    "Canids::Houndfolk": "Houndfolk are long-faced, keen-nosed, and built with the air of something designed to follow the one true line through a baffling world. They tend to carry scents the way scholars carry footnotes: obsessively, hierarchically, and with a grim sense of duty. To them, every room is a layered archive of where everyone has been and what they were too polite to mention.",

    "Cosmids": "Cosmids look as though some part of them was assembled using sky instead of ordinary childhood. Their skin, eyes, or manner often suggest moonlight, eclipses, starfields, deep water at midnight, or the sort of clock that makes you nervous. Being near one can feel mildly dislocating, like discovering the evening has become larger than advertised.",
    "Cosmids::Chronomancers": "Chronomancer cosmids often have a faintly delayed quality, as though their gestures arrive in several drafts and their attention is standing half a minute to one side of the present. They may smell of old books, iron filings, cold tea, and the air inside watchmakers' shops. They experience time less as a line and more as a crowded hallway.",
    "Cosmids::Abysswalkers": "Abysswalkers carry the cold vastness of unlit distances: not theatrical menace, just scale, quiet, and the unnerving suggestion that human concerns are very local weather. Their colors tend toward dark glass, deep blue, black, silver, and other shades found where sunlight has resigned. They make ordinary rooms feel like provisional shelters.",
    "Cosmids::Starspawned": "Starspawned beings have a polished, remote beauty, as though they were designed for admiration from far away and unfortunate clarity up close. There is often something glittering, crystalline, or over-precise about them, like frost on dark metal. They experience the world as pattern first, event second, which makes them good at prophecy-adjacent behavior and terrible at brunch.",
    "Cosmids::Cometkin": "Cometkin look fast even when standing still. Hair, eyes, clothing, aura, whatever they have always seems to imply motion, sparks, streaks, and the possibility of immediate departure. They smell of ozone, hot stone, and the first five seconds of a storm.",
    "Cosmids::Eclipsians": "Eclipsians are creatures of dimming and revelation: a face in shadow with a ring of light around it, a voice that seems nearer when it lowers, an atmosphere of thresholds. They experience the world in terms of appearance, disappearance, and timing, which makes them excellent at entrances and deeply unhelpful in committees.",

    "Cyborgs": "Cyborgs are part person, part engineered amendment, with flesh and mechanism forced into a truce that may or may not be elegant. They can smell of machine oil, warm copper, antiseptic, leather straps, rain on metal, or simply clean skin with one wrong note underneath. They experience the world through sensation plus calibration, which means they are rarely fully off-duty.",
    "Cyborgs::Advanced AI": "Advanced AI cyborgs often have the slightly overfinished quality of objects built after too much thought. Their gaze can be unsettling not because it is cold, but because it is busy in ways yours is not. They tend to parse rooms as data-rich negotiation zones, which is probably correct and still a dreadful way to attend a birthday dinner.",
    "Cyborgs::Combat-Oriented": "Combat cyborgs look reinforced in the manner of things designed after a lawsuit. Plates, braces, subdermal housings, hard edges, and a gait that suggests momentum has legal standing. They smell of oil, solvent, hot wiring, wool padding, and the practical side of fear.",
    "Cyborgs::Light Augmented": "Lightly augmented cyborgs are the subtle model: a lens where an eye ought to be ordinary, a joint that moves too smoothly, fingertips with improbable steadiness, hearing tuned half a notch beyond comfort. They are often most noticeable in silence, when nothing is happening and they are still detecting six things more than you.",

    "Cyclops": "Cyclopes are huge one-eyed humanoids whose central eye gives them an unnervingly direct presence, like being personally addressed by geology. They often smell of lanolin, stone dust, forge heat, wet earth, and old timber. The world comes to them in mass, distance, line, and impact; fine print is not their chosen art form.",

    "Dragons": "Dragons look the way a treasury, a thunderstorm, and an ego problem would look if forced to share a skeleton. Their scents vary wildly by kind—sulfur, cedar, river mud, snow, spice, hot coin, damp cave—but always feel expensive in one way or another. They experience place three-dimensionally and proprietorially: sky above, hoard below, everything else under review.",

    "Dwarf": "Dwarves are compact, broad, weather-resistant people who tend to look as though they were designed by someone suspicious of both waste and ornament. They often smell of clean wool, yeast, iron, soap, cedar chests, and last night's fire. They experience the world through weight, workmanship, temperature, and whether a thing was made properly, which is an excellent way to move through life if you don't mind being right all the time.",
    "Dwarf::Duergar (Underdark)": "Duergar have the pale, drawn, pressure-cooked look of people shaped by depth, stone, labor, and a chronic shortage of sunlight. They smell of metal filings, lamp smoke, stale air, and underground water. The surface world often strikes them as glaring, flimsy, and much too enthusiastic.",
    "Dwarf::Mark of Warding (Eberron)": "These dwarves tend to look groomed, guarded, and professionally difficult to steal from. Even their clothes often seem arranged with the logic of locks and ledgers. They experience the world as a series of vulnerabilities to be anticipated, priced, and quietly prevented.",
    "Dwarf::Mountain": "Mountain dwarves are the blockier, heavier, more fortress-like branch: thick wrists, deep chests, stride like a loaded cart that has no intention of tipping. They fit high cold places, strong doors, and dark ale with a sort of ancestral precision. One gets the sense they would survive the end of an age mainly by considering it overblown.",
    "Dwarf::Hill": "Hill dwarves are still sturdy, but in a warmer, rounder, more lived-in way, like a good farmhouse built on bedrock. They smell of root vegetables, grain, pipe leaf, beeswax, and cellars that keep excellent records. They experience land in seasons and yield, not conquest.",

    "Elf": "Elves tend to look too composed for ordinary biology, as if they were given more time in the drying rack. Their movements are usually economical, their clothes annoying in their effortless drape, and their senses tuned toward leaf-rustle, distant water, moonlight, and insult. They experience time with enough slack in it to make the rest of us seem like panicked shoppers.",
    "Elf::Drow (Dark Elf)": "Drow have the dark, polished beauty of things that evolved away from sun glare and into candlelight, fungus light, polished obsidian, and dangerous court manners. They often smell faintly of mineral water, incense, spider silk, oil, and enclosed stone. They experience space vertically, politically, and with no sentimental attachment to innocence.",
    "Elf::Shadar-Kai": "Shadar-Kai are severe, pale, dark-clad, and edged with the exhausted glamour of people who have spent too long standing near endings. Their beauty is spare rather than lush: chain, bone, ash, salt, black cloth, pale hands. They experience joy like a brief clear bell in winter air: real, sharp, and not to be wasted.",
    "Elf::Sea Elf": "Sea elves move with the smooth economy of swimmers even on land, which has the side effect of making everyone else look roughly assembled. They smell of salt, kelp, wet stone, shell, and cool currents. They experience the world in layers and pressure: surface glitter, middle drift, deep quiet.",
    "Elf::High Elf": "High elves have the curated look of people who were introduced to language, music, and passive disappointment at an impressionable age and never looked back. They tend to carry scents like parchment, herbs, polished wood, expensive soap, and garden air at dusk. They experience civilization aesthetically first and morally second, which explains rather a lot.",
    "Elf::Wood Elf": "Wood elves look sun-browned or leaf-shadowed, quick on the feet, and naturally dressed by bark, moss, leather, and very irritating good taste. They smell of resin, crushed leaves, clean fur, and rain caught in branches. The world comes to them as track, wind, rustle, and line of sight.",
    "Elf::Eladrin (Seasonal)": "Eladrin shift with the seasons, and it shows. Spring eladrin feel like wet earth and blossom air; summer like warm fruit and lightning far off; autumn like smoke, apples, and copper leaves; winter like frost on stone and a pause before speech. They experience mood as climate, which is poetic in theory and a public hazard in practice.",
    "Elf::Avariel": "Avariel are winged elves, all long bones, high shoulders, feathers, and the expensive look of creatures not intended for mud. They smell of cold air, feather dust, cliff grass, and sun on linen. On the ground they are patient, the way a hawk is patient on a glove.",

    "Fey": "Fey look, smell, and behave as though natural beauty were given opinions and then insufficient supervision. Flowers, bark, wet moss, honey, loam, dusk, mushrooms, cold streams, perfume that is half nectar and half warning: all of it belongs here. They experience the world as charged with meaning, and unfortunately so are teaspoons, promises, nicknames, and Tuesdays.",
    "Fey::Hobgoblins": "Fey hobgoblins have a martial tidiness to them: lacquered gear, measured posture, sharp eyes, and the air of people who keep banners folded correctly. They smell of oiled leather, campfire ash, cedar, and damp leaves. They experience community as a thing to be maintained deliberately, not wished into existence by flute music.",
    "Fey::Fairies": "Fairies are tiny, bright, quick, and entirely too comfortable with the fact that their size encourages underestimation. They often smell like nectar, crushed herbs, pollen, rain on petals, or whatever passes for confectionery in a flowerbed. They experience a room as a landscape, a table as a district, and your drink as an opportunity.",
    "Fey::Firbolgs": "Firbolgs are large, gentle, long-faced forest people with the kindly melancholy of old paths and weathered barns. They smell of moss, damp wool, bark, mushrooms, and soup that has been simmering for a respectable length of time. They experience speech as something to use when silence has had a fair chance.",
    "Fey::Satyr/Fawn": "Satyrs and fawns are goat-legged creatures of music, appetite, dancing, dust, wine, grass, and the ancient conviction that evening ought to go on longer. They smell of crushed thyme, sweat, cedar cups, spilled fruit, and hillside heat. They experience civilization as a useful source of cups and audiences.",
    "Fey::Trolls": "Fey-flavored trolls are less 'civilized giant' and more 'woodland problem with ancestry.' They tend to look damp, broad, rooty, licheny, and assembled by a marsh with strong feelings. They smell of peat, wet bark, pond water, mushrooms, and whatever was under the bridge before the bridge arrived.",
    "Fey::Leprechauns": "Leprechauns are small, neat, bright-eyed beings with the trim, polished appearance of people who could vanish into a hedge and come out with your ring, your purse, and a legal argument. They smell of clover, tobacco, old coins, rain on stone, and very expensive mischief. They experience rules the way musicians experience rhythm: as something to play with brilliantly."
}