ZODIAC_DECANS = {
    "Aries": [
        {
            "decan": 1,
            "degree_start": 0,
            "degree_end": 10,
            "degree_range": "0°00'–9°59'",
            "traditional_face_ruler": "Mars",
            "elemental_subsign": "Aries",
            "subsign_ruler": "Mars",
            "keywords": ["initiation", "force", "speed", "competition", "directness"],
            "description": "The blunt ignition point of Aries. This decan acts first, learns by impact, and has little patience for excessive deliberation. Strong for courage, assertion, physical drive, and immediate action; weak when it confuses momentum with strategy.",
        },
        {
            "decan": 2,
            "degree_start": 10,
            "degree_end": 20,
            "degree_range": "10°00'–19°59'",
            "traditional_face_ruler": "Sun",
            "elemental_subsign": "Leo",
            "subsign_ruler": "Sun",
            "keywords": ["confidence", "display", "command", "pride", "creative force"],
            "description": "Aries with a theatrical solar engine. This decan wants to be seen acting, winning, creating, or leading. It is more self-aware and image-conscious than the first decan, with stronger needs for recognition, authorship, and visible victory.",
        },
        {
            "decan": 3,
            "degree_start": 20,
            "degree_end": 30,
            "degree_range": "20°00'–29°59'",
            "traditional_face_ruler": "Venus",
            "elemental_subsign": "Sagittarius",
            "subsign_ruler": "Jupiter",
            "keywords": ["pursuit", "appetite", "risk", "freedom", "persuasion"],
            "description": "Aries becomes more exploratory, desirous, and socially combustible. This decan chases meaning, pleasure, conquest, or possibility. It can be charming and daring, but it may overestimate the wisdom of whatever currently feels exciting.",
        },
    ],

    "Taurus": [
        {
            "decan": 1,
            "degree_start": 0,
            "degree_end": 10,
            "degree_range": "0°00'–9°59'",
            "traditional_face_ruler": "Mercury",
            "elemental_subsign": "Taurus",
            "subsign_ruler": "Venus",
            "keywords": ["possession", "sensory judgment", "value", "stability", "material instinct"],
            "description": "The most direct Taurus decan: slow to move, difficult to dislodge, and strongly oriented toward comfort, value, food, money, land, texture, and bodily preference. It knows what it likes and generally sees no reason to apologize for that.",
        },
        {
            "decan": 2,
            "degree_start": 10,
            "degree_end": 20,
            "degree_range": "10°00'–19°59'",
            "traditional_face_ruler": "Moon",
            "elemental_subsign": "Virgo",
            "subsign_ruler": "Mercury",
            "keywords": ["maintenance", "craft", "routine", "usefulness", "cultivation"],
            "description": "Taurus becomes more technical, selective, and improvement-oriented. This decan preserves by tending, repairing, sorting, and refining. It is less indulgent than the first decan and more focused on practical competence.",
        },
        {
            "decan": 3,
            "degree_start": 20,
            "degree_end": 30,
            "degree_range": "20°00'–29°59'",
            "traditional_face_ruler": "Saturn",
            "elemental_subsign": "Capricorn",
            "subsign_ruler": "Saturn",
            "keywords": ["endurance", "ownership", "control", "legacy", "resource discipline"],
            "description": "Taurus hardens into long-term structure. This decan thinks in assets, obligations, inheritance, scarcity, and durability. It can build something that lasts, but it may also become too attached to what has already been secured.",
        },
    ],

    "Gemini": [
        {
            "decan": 1,
            "degree_start": 0,
            "degree_end": 10,
            "degree_range": "0°00'–9°59'",
            "traditional_face_ruler": "Jupiter",
            "elemental_subsign": "Gemini",
            "subsign_ruler": "Mercury",
            "keywords": ["curiosity", "language", "exchange", "mobility", "multiplicity"],
            "description": "The pure signal-sampling decan of Gemini. It collects data, names things, compares options, and moves quickly between people, ideas, and formats. Strong for language, trade, wit, and adaptation; weak when it mistakes motion for depth.",
        },
        {
            "decan": 2,
            "degree_start": 10,
            "degree_end": 20,
            "degree_range": "10°00'–19°59'",
            "traditional_face_ruler": "Mars",
            "elemental_subsign": "Libra",
            "subsign_ruler": "Venus",
            "keywords": ["debate", "social tactics", "comparison", "argument", "style"],
            "description": "Gemini becomes socially sharpened. This decan thinks through contrast, disagreement, flirtation, alliance, and rivalry. It is persuasive and mentally agile, but can turn conversation into sport even when nobody else agreed to play.",
        },
        {
            "decan": 3,
            "degree_start": 20,
            "degree_end": 30,
            "degree_range": "20°00'–29°59'",
            "traditional_face_ruler": "Sun",
            "elemental_subsign": "Aquarius",
            "subsign_ruler": "Saturn",
            "keywords": ["systems", "abstraction", "networks", "detachment", "strange intelligence"],
            "description": "Gemini becomes more conceptual, detached, and pattern-oriented. This decan is interested in systems, groups, theories, technologies, and unusual social arrangements. It can read the room from a distance, but may treat people like case studies.",
        },
    ],

    "Cancer": [
        {
            "decan": 1,
            "degree_start": 0,
            "degree_end": 10,
            "degree_range": "0°00'–9°59'",
            "traditional_face_ruler": "Venus",
            "elemental_subsign": "Cancer",
            "subsign_ruler": "Moon",
            "keywords": ["protection", "memory", "belonging", "attachment", "emotional weather"],
            "description": "The most immediate Cancer decan: receptive, protective, impressionable, and strongly tied to kinship, place, and private feeling. It tracks safety through emotional tone and remembers what others pretend was minor.",
        },
        {
            "decan": 2,
            "degree_start": 10,
            "degree_end": 20,
            "degree_range": "10°00'–19°59'",
            "traditional_face_ruler": "Mercury",
            "elemental_subsign": "Scorpio",
            "subsign_ruler": "Mars",
            "keywords": ["depth", "secrecy", "loyalty", "defense", "emotional leverage"],
            "description": "Cancer becomes more guarded, intense, and psychologically strategic. This decan does not merely feel; it studies attachment, threat, trust, and betrayal. Protective instincts become sharper and less innocent.",
        },
        {
            "decan": 3,
            "degree_start": 20,
            "degree_end": 30,
            "degree_range": "20°00'–29°59'",
            "traditional_face_ruler": "Moon",
            "elemental_subsign": "Pisces",
            "subsign_ruler": "Jupiter",
            "keywords": ["empathy", "imagination", "porosity", "devotion", "mood"],
            "description": "Cancer becomes more porous, imaginative, and spiritually or artistically receptive. This decan absorbs atmosphere easily and may blur its own needs with the needs of others. Strong for compassion and symbolic thinking; weak on clean separation.",
        },
    ],

    "Leo": [
        {
            "decan": 1,
            "degree_start": 0,
            "degree_end": 10,
            "degree_range": "0°00'–9°59'",
            "traditional_face_ruler": "Saturn",
            "elemental_subsign": "Leo",
            "subsign_ruler": "Sun",
            "keywords": ["presence", "authority", "pride", "performance", "centrality"],
            "description": "The core Leo decan: visible, proud, expressive, and authority-seeking. It wants to radiate from the center rather than negotiate from the edge. Strong for leadership and creative selfhood; brittle when dignity becomes dependency on applause.",
        },
        {
            "decan": 2,
            "degree_start": 10,
            "degree_end": 20,
            "degree_range": "10°00'–19°59'",
            "traditional_face_ruler": "Jupiter",
            "elemental_subsign": "Sagittarius",
            "subsign_ruler": "Jupiter",
            "keywords": ["grandeur", "belief", "generosity", "teaching", "mythmaking"],
            "description": "Leo becomes bigger, louder, more philosophical, and more evangelical. This decan wants meaning attached to self-expression. It can inspire and uplift, but may also inflate personal preference into universal law.",
        },
        {
            "decan": 3,
            "degree_start": 20,
            "degree_end": 30,
            "degree_range": "20°00'–29°59'",
            "traditional_face_ruler": "Mars",
            "elemental_subsign": "Aries",
            "subsign_ruler": "Mars",
            "keywords": ["will", "dominance", "bravery", "heat", "creative aggression"],
            "description": "Leo becomes more combative, athletic, and forceful. This decan does not just want admiration; it wants proof of strength. Powerful for bold creation and decisive action, but prone to theatrical escalation when challenged.",
        },
    ],

    "Virgo": [
        {
            "decan": 1,
            "degree_start": 0,
            "degree_end": 10,
            "degree_range": "0°00'–9°59'",
            "traditional_face_ruler": "Sun",
            "elemental_subsign": "Virgo",
            "subsign_ruler": "Mercury",
            "keywords": ["analysis", "discernment", "function", "repair", "precision"],
            "description": "The pure Virgo decan: analytical, observant, corrective, and concerned with function. It notices what is missing, excessive, inefficient, mislabeled, or poorly maintained. Excellent for diagnostics; irritating when every room becomes a draft needing edits.",
        },
        {
            "decan": 2,
            "degree_start": 10,
            "degree_end": 20,
            "degree_range": "10°00'–19°59'",
            "traditional_face_ruler": "Venus",
            "elemental_subsign": "Capricorn",
            "subsign_ruler": "Saturn",
            "keywords": ["competence", "standards", "discipline", "useful beauty", "professionalism"],
            "description": "Virgo becomes more ambitious, structured, and standards-driven. This decan wants usefulness to produce durable results. It is less nervous than the first decan and more interested in mastery, rank, skill, and visible competence.",
        },
        {
            "decan": 3,
            "degree_start": 20,
            "degree_end": 30,
            "degree_range": "20°00'–29°59'",
            "traditional_face_ruler": "Mercury",
            "elemental_subsign": "Taurus",
            "subsign_ruler": "Venus",
            "keywords": ["craft", "sensory refinement", "stewardship", "patience", "material skill"],
            "description": "Virgo becomes more tactile, grounded, and craft-oriented. This decan refines through repetition, material intelligence, and practical taste. It prefers improvements that can be touched, used, eaten, worn, counted, or maintained.",
        },
    ],

    "Libra": [
        {
            "decan": 1,
            "degree_start": 0,
            "degree_end": 10,
            "degree_range": "0°00'–9°59'",
            "traditional_face_ruler": "Moon",
            "elemental_subsign": "Libra",
            "subsign_ruler": "Venus",
            "keywords": ["balance", "aesthetics", "agreement", "comparison", "social intelligence"],
            "description": "The pure Libra decan: relational, aesthetic, comparative, and negotiation-minded. It understands proportion, tone, fairness, and presentation. Strong for diplomacy and design; weak when it delays action to keep every option politely undead.",
        },
        {
            "decan": 2,
            "degree_start": 10,
            "degree_end": 20,
            "degree_range": "10°00'–19°59'",
            "traditional_face_ruler": "Saturn",
            "elemental_subsign": "Aquarius",
            "subsign_ruler": "Saturn",
            "keywords": ["principle", "systems", "contracts", "detachment", "social architecture"],
            "description": "Libra becomes more abstract, principled, and socially structural. This decan cares about rules, networks, agreements, institutions, and group order. Less romantic than the first decan; more interested in whether the arrangement works.",
        },
        {
            "decan": 3,
            "degree_start": 20,
            "degree_end": 30,
            "degree_range": "20°00'–29°59'",
            "traditional_face_ruler": "Jupiter",
            "elemental_subsign": "Gemini",
            "subsign_ruler": "Mercury",
            "keywords": ["conversation", "wit", "mediation", "social mobility", "cleverness"],
            "description": "Libra becomes faster, more verbal, and more mentally playful. This decan negotiates through language, charm, framing, and social agility. It can mediate brilliantly, but may also over-intellectualize desire.",
        },
    ],

    "Scorpio": [
        {
            "decan": 1,
            "degree_start": 0,
            "degree_end": 10,
            "degree_range": "0°00'–9°59'",
            "traditional_face_ruler": "Mars",
            "elemental_subsign": "Scorpio",
            "subsign_ruler": "Mars",
            "keywords": ["intensity", "defense", "desire", "control", "investigation"],
            "description": "The pure Scorpio decan: penetrating, private, strategic, and difficult to fool. It is drawn to motives, hidden costs, power exchange, sex, fear, loyalty, and survival math. Strong for investigation; hazardous when suspicion becomes a lifestyle.",
        },
        {
            "decan": 2,
            "degree_start": 10,
            "degree_end": 20,
            "degree_range": "10°00'–19°59'",
            "traditional_face_ruler": "Sun",
            "elemental_subsign": "Pisces",
            "subsign_ruler": "Jupiter",
            "keywords": ["emotional depth", "devotion", "magnetism", "sacrifice", "psychic sensitivity"],
            "description": "Scorpio becomes more emotionally porous, devotional, and symbolically loaded. This decan feels the undertow beneath events and relationships. It can be healing and profound, but may confuse intensity with truth.",
        },
        {
            "decan": 3,
            "degree_start": 20,
            "degree_end": 30,
            "degree_range": "20°00'–29°59'",
            "traditional_face_ruler": "Venus",
            "elemental_subsign": "Cancer",
            "subsign_ruler": "Moon",
            "keywords": ["attachment", "loyalty", "memory", "protection", "emotional possession"],
            "description": "Scorpio becomes more bonded, protective, and memory-driven. This decan wants total trust, not casual access. It can guard what it loves with exceptional tenacity, but may hold old emotional accounts open for too long.",
        },
    ],

    "Sagittarius": [
        {
            "decan": 1,
            "degree_start": 0,
            "degree_end": 10,
            "degree_range": "0°00'–9°59'",
            "traditional_face_ruler": "Mercury",
            "elemental_subsign": "Sagittarius",
            "subsign_ruler": "Jupiter",
            "keywords": ["quest", "belief", "distance", "teaching", "expansion"],
            "description": "The pure Sagittarius decan: restless, broad-seeking, opinionated, and hungry for scale. It wants the map, the principle, the horizon, the doctrine, or the joke that makes the room less small. Strong for exploration; weak on detail retention.",
        },
        {
            "decan": 2,
            "degree_start": 10,
            "degree_end": 20,
            "degree_range": "10°00'–19°59'",
            "traditional_face_ruler": "Moon",
            "elemental_subsign": "Aries",
            "subsign_ruler": "Mars",
            "keywords": ["adventure", "impulse", "boldness", "provocation", "independence"],
            "description": "Sagittarius becomes more physically daring, reactive, and combative. This decan does not merely want freedom; it tests freedom by moving, risking, challenging, and refusing to be managed.",
        },
        {
            "decan": 3,
            "degree_start": 20,
            "degree_end": 30,
            "degree_range": "20°00'–29°59'",
            "traditional_face_ruler": "Saturn",
            "elemental_subsign": "Leo",
            "subsign_ruler": "Sun",
            "keywords": ["conviction", "performance", "honor", "teaching", "personal doctrine"],
            "description": "Sagittarius becomes more expressive, proud, and declarative. This decan wants its beliefs to have style, audience, and dramatic force. It can teach with fire, but may turn opinions into personal branding.",
        },
    ],

    "Capricorn": [
        {
            "decan": 1,
            "degree_start": 0,
            "degree_end": 10,
            "degree_range": "0°00'–9°59'",
            "traditional_face_ruler": "Jupiter",
            "elemental_subsign": "Capricorn",
            "subsign_ruler": "Saturn",
            "keywords": ["ambition", "discipline", "hierarchy", "structure", "achievement"],
            "description": "The pure Capricorn decan: strategic, restrained, status-aware, and built for delayed reward. It understands systems, rank, scarcity, responsibility, and the price of incompetence. Strong for building; cold when everything becomes a ladder.",
        },
        {
            "decan": 2,
            "degree_start": 10,
            "degree_end": 20,
            "degree_range": "10°00'–19°59'",
            "traditional_face_ruler": "Mars",
            "elemental_subsign": "Taurus",
            "subsign_ruler": "Venus",
            "keywords": ["resources", "persistence", "wealth", "craft", "material control"],
            "description": "Capricorn becomes more material, possessive, and resource-focused. This decan builds through patience, accumulation, practical skill, and hard limits. It respects comfort, but usually wants it earned, owned, and insured.",
        },
        {
            "decan": 3,
            "degree_start": 20,
            "degree_end": 30,
            "degree_range": "20°00'–29°59'",
            "traditional_face_ruler": "Sun",
            "elemental_subsign": "Virgo",
            "subsign_ruler": "Mercury",
            "keywords": ["expertise", "management", "precision", "systems work", "accountability"],
            "description": "Capricorn becomes more technical, managerial, and exacting. This decan wants competence at scale: procedures, audits, standards, planning, and measurable improvement. It can run the machine; it may forget people are not widgets.",
        },
    ],

    "Aquarius": [
        {
            "decan": 1,
            "degree_start": 0,
            "degree_end": 10,
            "degree_range": "0°00'–9°59'",
            "traditional_face_ruler": "Venus",
            "elemental_subsign": "Aquarius",
            "subsign_ruler": "Saturn",
            "keywords": ["distance", "systems", "difference", "groups", "principle"],
            "description": "The pure Aquarius decan: detached, principled, socially observant, and structurally minded. It sees patterns in groups, norms, institutions, and collective behavior. Strong for reform and analysis; weak when it becomes allergic to ordinary human need.",
        },
        {
            "decan": 2,
            "degree_start": 10,
            "degree_end": 20,
            "degree_range": "10°00'–19°59'",
            "traditional_face_ruler": "Mercury",
            "elemental_subsign": "Gemini",
            "subsign_ruler": "Mercury",
            "keywords": ["invention", "language", "networks", "experimentation", "cleverness"],
            "description": "Aquarius becomes faster, more verbal, and more experimental. This decan likes systems that talk to other systems: code, media, communities, theories, jokes, protocols, and strange little frameworks with surprisingly sharp utility.",
        },
        {
            "decan": 3,
            "degree_start": 20,
            "degree_end": 30,
            "degree_range": "20°00'–29°59'",
            "traditional_face_ruler": "Moon",
            "elemental_subsign": "Libra",
            "subsign_ruler": "Venus",
            "keywords": ["alliances", "aesthetic theory", "social design", "mediation", "cool charm"],
            "description": "Aquarius becomes more relational, aesthetic, and socially diplomatic. This decan wants better arrangements between people, not merely better ideas. It can design elegant social systems, but may keep intimacy at a tasteful museum distance.",
        },
    ],

    "Pisces": [
        {
            "decan": 1,
            "degree_start": 0,
            "degree_end": 10,
            "degree_range": "0°00'–9°59'",
            "traditional_face_ruler": "Saturn",
            "elemental_subsign": "Pisces",
            "subsign_ruler": "Jupiter",
            "keywords": ["imagination", "mercy", "dissolution", "faith", "sensitivity"],
            "description": "The pure Pisces decan: receptive, imaginative, compassionate, and hard to fully define. It moves through feeling, symbol, music, dream, faith, and subtle atmosphere. Strong for art and mercy; weak when boundaries become decorative.",
        },
        {
            "decan": 2,
            "degree_start": 10,
            "degree_end": 20,
            "degree_range": "10°00'–19°59'",
            "traditional_face_ruler": "Jupiter",
            "elemental_subsign": "Cancer",
            "subsign_ruler": "Moon",
            "keywords": ["care", "memory", "devotion", "protection", "emotional absorption"],
            "description": "Pisces becomes more familial, nostalgic, and emotionally sheltering. This decan absorbs the moods and histories around it. It can be profoundly caring, but may struggle to distinguish compassion from over-identification.",
        },
        {
            "decan": 3,
            "degree_start": 20,
            "degree_end": 30,
            "degree_range": "20°00'–29°59'",
            "traditional_face_ruler": "Mars",
            "elemental_subsign": "Scorpio",
            "subsign_ruler": "Mars",
            "keywords": ["depth", "surrender", "obsession", "mysticism", "emotional force"],
            "description": "Pisces becomes darker, more intense, and more psychologically charged. This decan is drawn to hidden motives, spiritual extremity, erotic mystery, grief, and transformation. It can reach deep waters, but may romanticize losing the plot.",
        },
    ],
}