HOUSE_PROPERTIES_EXPLAINED = {
    "domain_layers": {
        "core_domains": "irreducible function",
        "derived_domains": "contemporary extensions",
        "traditional_domains": "inherited historical assignments",
        "esoteric_domains": "symbolic and mythic register",
    },
    "axes": {
        "visibility": "how exposed the house is to social perception",
        "relationality": "how dependent the house is on interaction with others",
        "materiality": "how tied it is to body, matter, resources, or land",
        "institutionality": "how much it depends on formal roles, rules, or social structures",
        "immediacy": "how present-tense, proximal, and situational the house's operations are vs ancestry, legacy, duration, decline, or long arcs of time",
        "agency": "how much direct volition operates there",
        "publicness": "how socially externalized the house is",
        "symbolic_density": "how naturally the house attracts mythic, psychic, or interpretive meaning",
    }
}

HOUSE_DEFINITIONS = { #Areas of Life
    1: {
        "name": "First House",
        "archetypal_title": "The Visible Incarnation Point",

        "core_domains": [ #irreducible function
            "self",
            "body",
            "appearance",
            "physical presence",
            "identity",
            "name",
            "embodiment",
            "temperament",
            "approach",
            "self-presentation",
            "first impression",
            "surface vitality",
        ],

        "derived_domains": [ #contemporary extensions
            "personal style",
            "attitude",
            "confidence",
            "social legibility",
            "physical manner",
            "posture",
            "gait",
            "facial expression",
            "signature",
            "immediate impact",
            "visible health",
            "visible mood",
            "voice",
        ],

        "traditional_domains": [ #inherited historical assignments
            "the native",
            "constitution",
            "complexion",
            "stature",
            "manners",
            "bodily form",
            "disposition",
            "vital force",
            "visage",
            "temper",
            "mien",
        ],

        "esoteric_domains": [ #symbolic and mythic register
            "threshold self",
            "daylight identity",
            "face turned toward the world",
            "body's declaration",
            "locus of arrival",
            "visible seal of being",
            "animating presence",
        ],

        "axes": {
            "visibility": 1.00, #how exposed the house is to social perception
            "relationality": 0.20, #how dependent the house is on interaction with others
            "materiality": 0.82, #how tied it is to body, matter, resources, land
            "institutionality": 0.08, #how much it depends on formal social structures
            "agency": 0.88, #how much direct volition operates there
            "publicness": 0.42, #how socially externalized it is
            "immediacy": 0.96, #how immediate
            "symbolic_density": 0.62, #how naturally mythic/psychic/interpretive it is
        },

        "logic": {
            "entry_mode": "arrival",
            "resource_mode": "presence",
            "failure_mode": "fragile embodiment, depleted vitality, incoherent self-presentation",
            "distortion_mode": "overidentification with appearance, persona, or immediate impact",
        },
        "notes": [
        ],
    },
    2: {
        "name": "Second House",
        "archetypal_title": "The House of Possession",

        "core_domains": [
            "money",
            "income",
            "possessions",
            "resources",
            "savings",
            "reserves",
            "food",
            "appetite",
            "security",
            "continuity",
            "holdings",
            "material support",
        ],

        "derived_domains": [
            "budget",
            "spending",
            "comfort",
            "hoard",
            "stored goods",
            "provisions",
            "livelihood",
            "revenue-generating skills", #"employable skills",
            "self-worth",
            "personal values",
            "taste",
            "resource management",
            "what-can-be-relied-upon",
            "supplies",
            "stockpiles",
        ],

        "traditional_domains": [
            "movable goods",
            "wealth",
            "substance",
            "livelihood",
            "gain",
            "loss of substance",
            "treasury",
            "stores",
            "acquisition",
            "chattels",
            "treasure",
        ],

        "esoteric_domains": [
            "storehouse of being",
            "mouth and purse",
            "kept substance",
            "private reserve",
            "what feeds continuity",
            "counted and the carried",
            "what-keeps-the-organism-going",
            "right to retain",
            "grammar of possession",
            "earthly retention",
            "body's claim on matter",
        ],

        "axes": {
            "visibility": 0.28,
            "relationality": 0.18,
            "materiality": 0.96,
            "institutionality": 0.18,
            "agency": 0.72,
            "publicness": 0.20,
            "immediacy":0.51,
            "symbolic_density": 0.58,
        },

        "logic": {
            "entry_mode": "acquisition",
            "resource_mode": "retention",
            "failure_mode": "depletion, instability, waste, unreliable support",
            "distortion_mode": "hoarding, overidentification with possessions, reducing worth to measurable assets",
        },
        "notes": [
        ],
    },
    3: {
        "name": "Third House",
        "archetypal_title": "The Immediate Signal Ecology",

        "core_domains": [
            "siblings",
            "cousins",
            "kindred",
            "neighbors",
            "messages",
            "conversation",
            "communication",
            "correspondence",
            "information exchange",
            "local travel",
            "errands",
            "routes",
            "crossings",
            "nearby environment",
        ],

        "derived_domains": [
            "texts",
            "emails",
            "calls",
            "notes",
            "calendar",
            "dialogue",
            "dialects",
            "code-switching",
            "semiotic maneuvering",
            "symbolic fluency", #fluency with cultural symbols
            "iconographic literacy", #understanding of cultural iconograph
            "language of the local milieu",
            "gossip",
            "news",
            "data",
            "databases",
            "intelligence",
            "relay systems",
            "commuting",
            "domestic travel",
            "research",
            "study",
            "analysis",
            "investigation",
            "pattern recognition",
        ],

        "traditional_domains": [
            "brethren",
            "kindred",
            "letters",
            "missives",
            "messengers",
            "rumors",
            "short journeys",
            "visitations",
            "local roads",
            "epistles",
        ],

        "esoteric_domains": [
            "casual omens",
            "passing sign",
            "street-level intelligence",
            "crossroads knowledge",
            "local symbolic currency",
            "signal traffic",
            "nearby web of exchange",
            "small repetitions with meaning",
            "ambient murmurs",
        ],

        "axes": {
            "visibility": 0.52,
            "relationality": 0.74,
            "materiality": 0.42,
            "institutionality": 0.24,
            "immediacy":0.90,
            "agency": 0.66,
            "publicness": 0.46,
            "symbolic_density": 0.64,
        },

        "logic": {
            "entry_mode": "contact",
            "resource_mode": "exchange",
            "failure_mode": "noise, miscommunication, trivial distraction, scattered attention, local friction",
            "distortion_mode": "overstimulation, gossip addiction, compulsive signaling, mistaking information flow for depth",
        },
        "notes": [
        ],
    },
    4: {
        "name": "Fourth House",
        "archetypal_title": "The Origin Chamber",

        "core_domains": [
            "home",
            "family",
            "dwelling",
            "private life",
            "roots",
            "ancestry",
            "land",
            "property",
            "real estate",
            "childhood",
            "origin",
            "foundation",
            "belonging",
        ],

        "derived_domains": [
            "home base",
            "domestic security",
            "abode",
            "household",
            "gardens",
            "cultivated land",
            "ancestral legacy",
            "parental roots",
            "domestic situation",
            "lineage",
            "kitchen",
            "bedroom",
            "buried history",
            "cellar",
            "nesting instinct",
            "family estate",
            "domestic sovereignty",
            "family name",
            "protective enclosure",
            "past",
        ],

        "traditional_domains": [
            "ancestral land",
            "end of matters",
            "hidden foundations",
            "hearth",
            "demesne",
            #"father (within patrilineal systems)",
            #"mother (within natural systems)",
        ],

        "esoteric_domains": [
            "foundation stones",
            "gestation",
            "underground chamber",
            "buried base",
            "maternal continuity",
            "hearth memory",
            "pre-public formation of self",
            "enclosed kingdom",
            "inherited ground",
            "root system of identity",
            "shelters of the self from public view",
        ],

        "axes": {
            "visibility": 0.10,
            "relationality": 0.62,
            "materiality": 0.78,
            "institutionality": 0.32,
            "immediacy": 0.52,
            "agency": 0.34,
            "publicness": 0.06,
            "symbolic_density": 0.80,
        },

        "logic": {
            "entry_mode": "inheritance",
            "resource_mode": "containment",
            "failure_mode": "dislocation, instability of home, severed continuity, private insecurity",
            "distortion_mode": "overattachment to origins, enclosure, familial stagnation, living inside the past",
        },
        "notes": [
            "Some traditional systems assign the 4th house to the father and patrimony; this likely reflects historical property and lineage structures rather than a universally valid symbolic rule."
        ],
    },
    5: {
        "name": "Fifth House",
        "archetypal_title": "The Theatre of Pleasure",

        "core_domains": [
            "children",
            "romance",
            "courtship",
            "flirtation",
            "pleasure",
            "play",
            "creativity",
            "art",
            "performance",
            "games",
            "delight",
            "self-display",
        ],

        "derived_domains": [
            "dating",
            "seduction",
            "theatre",
            "showmanship",
            "applause",
            "hobbies",
            "party",
            "amusement",
            "festive excess",
            "festivity",
            "risk for pleasure",
            "creative output",
            "favored offspring",
            "charisma",
            "adornment",
            "being admired",
        ],

        "traditional_domains": [
            "children",
            "pleasure",
            "lovers",
            "festivals",
            "banquets",
            "games of chance",
            "merriment",
            "conception",
            "issue", #them kids issued from thine loins. lol
            "banqueting",
            "paramours",
            "merriments",
            "sports",
        ],

        "esoteric_domains": [
            "staged self",
            "radiant performance impulse",
            "creation under witness",
            "desire to delight",
            "theater of attraction",
            "gamble of visibility",
            "favored creation",
            "spark that wants applause",
        ],

        "axes": {
            "visibility": 0.86,
            "relationality": 0.58,
            "materiality": 0.42,
            "institutionality": 0.18,
            "agency": 0.84,
            "publicness": 0.64,
            "immediacy": 0.78,
            "symbolic_density": 0.72,
        },

        "logic": {
            "entry_mode": "attraction",
            "resource_mode": "expression",
            "failure_mode": "vanity, sterile performance, hollow pleasure, neglected creations, attention-seeking without substance",
            "distortion_mode": "living for applause, confusing admiration with love, turning play into self-importance",
        },
        "notes": []
    },
    6: {
        "name": "Sixth House",
        "archetypal_title": "The Discipline of Daily Function",

        "core_domains": [
            "labor",
            "service",
            "duty",
            "routine",
            "habits",
            "maintenance",
            "upkeep",
            "correction",
            "health",
            "diet",
            "repetition",
            "useful competence",
        ],

        "derived_domains": [
            "daily obligations",
            "daily tasks",
            "daily grind",
            "maintenance tasks",
            "mundane tasks",
            "schedule",
            "practical work",
            "coworkers",
            "repetitive duties",
            "quiet competence",
            "discipline",
            "regimen",
            "hygiene",
            "repair",
            "troubleshooting",
        ],

        "traditional_domains": [
            "servants",
            "toil",
            "illness",
            "infirmity",
            "labor",
            "service",
            "drudgery",
            "subordinate work",
            "indenturement",
            "small cattle",
            "servitors",
        ],

        "esoteric_domains": [
            "maintenance corridor",
            "burden of continuation",
            "discipline of upkeep",
            "what must be corrected",
            "work that keeps things running",
            "invisible labor of continuity",
            "competence without spectacle",
            "rituals of functioning",
            "price of operational life",
        ],

        "axes": {
            "visibility": 0.22,
            "relationality": 0.48,
            "materiality": 0.72,
            "institutionality": 0.52,
            "agency": 0.58,
            "publicness": 0.24,
            "immediacy": 0.88,
            "symbolic_density": 0.46,
        },

        "logic": {
            "entry_mode": "obligation",
            "resource_mode": "maintenance",
            "failure_mode": "disorder, neglect, inefficiency, burnout, declining function",
            "distortion_mode": "living as a servant to routine, overidentifying with usefulness, reducing life to upkeep",
        },

        "notes": [
        "H6 vs H10: The 6th house is doing the work that needs done. The 10th house is getting RECOGNIZED for & publicly defined by the work.",
        "H6 vs H1: Both can relate to health; 1st house is vitality, embodiment & visible constitution. H6 is maintenance of function, regimen, symptoms, health management.",
        "H6 vs H12: 6th house manages disorder. 12th house is being overtaken by what escaped management."
        ]
    },
    7: {
        "name": "Seventh House",
        "archetypal_title": "The Formal Other", #The Other Party

        "core_domains": [
            "marriage",
            "partnership",
            "spouse",
            "counterpart",
            "union",
            "agreement",
            "contracts",
            "reciprocity",
            "witness",
            "rival",
            "open enemies",
            "one-to-one commitments",
        ],

        "derived_domains": [
            "partner",
            "relationships",
            "binding contracts",
            "alliances",
            "clients",
            "collaboration",
            "negotiation",
            "interpersonal commitments",
            "legal contracts",
            "diplomacy",
            "litigation",
            "devotion",
        ],

        "traditional_domains": [
            "marriage",
            "spouse",
            "contracts",
            "open enemies",
            "lawsuits",
            "partnerships",
            "declared opposition",
            "consort",
            "adversaries",
            "covenants",
        ],

        "esoteric_domains": [
            "recognized other",
            "face across the threshold",
            "binding encounter",
            "lawful counterpart",
            "witness who answers back",
            "union under recognition",
            "adversary in full view",
            "other party",
        ],

        "axes": {
            "visibility": 0.68,
            "relationality": 0.98,
            "materiality": 0.26,
            "institutionality": 0.74,
            "agency": 0.52,
            "publicness": 0.72,
            "immediacy": 0.70,
            "symbolic_density": 0.62,
        },

        "logic": {
            "entry_mode": "encounter",
            "resource_mode": "reciprocity",
            "failure_mode": "conflict, imbalance, bad bargains, adversarial fixation, unstable commitments",
            "distortion_mode": "defining the self through the other, compulsive pair-bonding, surrendering judgment for relational recognition",
        },

        "notes": [
        "7th vs 5th house: 5th = romance, flirtation, attraction, seduction, courtship. (The courtship phase.) 7th = union, contract, marriage, mutual obligation, formal pair-bond. (The act of formalizing the union.)",
        "7th vs 8th house: 7th = the agreement (formalizing a union - like getting married). 8th = the consequence after the agreement (consequences of the formalization - the outcome of the marriage itself).",
        "7th vs 11th house: 7th = one-to-one alliance or opposition; partnerships & individual nemeses. 11th = group belonging, networks, collective affiliation, team rivalries.",
        "7th (DS) vs 1st house (AS): 1st = self as emergence. 7th = other as recognized counterpart.",
        "House 7 is not 'love', nor 'romance'. It is the juridical and reciprocal structure of human encounter."
        ]
    },
    8: {
        "name": "Eighth House",
        "archetypal_title": "Consequences of Entanglement",

        "core_domains": [
            "death",
            "mortality",
            "debt",
            "taxes",
            "inheritance",
            "other people's money",
            "shared resources",
            "loans",
            "intimacy",
            "insurance",
            "high-stakes bonds",
            "dependency",
            "irreversible exchange",
        ],

        "derived_domains": [
            "mergers",
            "transactional consequences",
            "fear",
            "taboos",
            "sexuality",
            "crises",
            "asymmetrical access",
            "desire indistinguishable from need",
            "power through entanglement",
            "tested boundaries",
            "leverage through dependency",
            "forfeiture",
            "shared liabilities",
            "consequence-bearing control",
            "control through shared stakes",
            "extraction",
            "ancestral debt",
        ],

        "traditional_domains": [
            "death",
            "fear",
            "inheritance",
            "dowry",
            "other people's assets",
            "loss",
            "estate matters",
            "tribute",
            "mortuary dues",
            "other men's substance",
        ],

        "esoteric_domains": [
            "forbidden archives",
            "occult initiation",
            "bondage of consequence",
            "energetic residue",
            "threshold events",
            "blood price",
            "cost hidden inside the bond",
            "stakes that override consent",
            "custody over what others need",
            "chamber of irreversible exchange",
        ],

        "axes": {
            "visibility": 0.24,
            "relationality": 0.88,
            "materiality": 0.72,
            "institutionality": 0.62,
            "agency": 0.38,
            "publicness": 0.26,
            "immediacy": 0.40,
            "symbolic_density": 0.92,
        },

        "logic": {
            "entry_mode": "entanglement",
            "resource_mode": "merger",
            "failure_mode": "depletion, coercion, panic, exposure, irreversible loss, inherited burden",
            "distortion_mode": "confusing intensity with truth, eroticizing damage, seeking control through dependency",
        },

        "notes": [
            "Some distinctions: 10th house power = rank, status, office, visible authority. 7th house power = contractual parity or adversarial opposition. 12th house power = hidden undermining, obscured systems, silent attrition. 8th house power = leverage arising from merger, debt, taboo, exposure, inheritance, sexuality, fear, or irreversible consequence.",
            "The 8th house says, “I can affect your survival, your losses, your exposure, your dependency, your access, or the cost of your choices.” Then if you have it in Gemini, it probably adds 'teehee' and throws confetti in your face."
        ],
        "fear": "fear of loss, exposure, dependence, debt, death, violation, irreversible consequence",
    },
    9: {
        "name": "Ninth House",
        "archetypal_title": "Meaning Found at Distance",

        "core_domains": [
            "long-distance travel",
            "foreign lands",
            "pilgrimage",
            "higher education",
            "philosophy",
            "religion",
            "law",
            "doctrine",
            "worldview",
            "systems of meaning",
            "cosmology",
            "cultural distance",
        ],

        "derived_domains": [
            "travel abroad",
            "international journeys",
            "foreign cultures",
            "advanced study",
            "scholarship",
            "canonical texts",
            "sanctioned truth",
            "dogma",
            "gurus",
            "teachers",
            "theology",
            "jurisprudence",
            "ideology",
            "paradigms",
            "worldview architecture",
            "publishing",
            "translation across cultures",
        ],

        "traditional_domains": [
            "long journeys",
            "religion",
            "philosophy",
            "law",
            "priests",
            "sacred learning",
            "prophecy",
            "foreign lands",
            "augery",
            "oracles",
            "divination",
            "clerks",
        ],

        "esoteric_domains": [
            "meaning beyond the horizon",
            "initiation by distance",
            "doctrine of elsewhere",
            "truth carried across borders",
            "pilgrimage mind",
            "architecture of sanctioned meaning",
            "distant order that reshapes belief",
        ],

        "axes": {
            "visibility": 0.46,
            "relationality": 0.40,
            "materiality": 0.22,
            "institutionality": 0.72,
            "agency": 0.68,
            "publicness": 0.52,
            "immediacy": 0.22,
            "symbolic_density": 0.88,
        },

        "logic": {
            "entry_mode": "departure",
            "resource_mode": "orientation",
            "failure_mode": "dogmatism, abstraction without grounding, borrowed certainty, empty cosmopolitanism",
            "distortion_mode": "indiscriminate xenophilia, mistaking distance for wisdom, confusing ideology with truth, using belief as escape from reality",
        },

        "notes": [
            "H3 vs H9: 3rd house is local exchange, nearby signals, practical information, speech shaped by proximity. 9th = distance, doctrine, canon, worldview, travel beyond the local field. 3rd is information. 9th is meaning. 3rd is adjunct. 9th is tenured.",
            "H9 vs H10: 9th = truth systems, law, philosophy, doctrine. 10th = rank, office, legitimacy, public authority. The judge's reasoning is 9th. The judicial office itself is 10th.",
            "H9 vs H12: both get conflated with 'spirituality', but that's sloppy. 9th = truth systems, law, philosophy, doctrine. 12th = withdrawal, dissolution, confinement, obscured suffering. Either one can be ascetic at a monestary.",
            "The 9th house's affiliation with 'long journeys' means travel beyond one’s operative local sphere. Its scale changes with the transportation and cultural horizon of the era."
        ]
    },
    10: {
        "name": "Tenth House",
        "archetypal_title": "The Public Summit",

        "core_domains": [
            "honor",
            "career",
            "reputation",
            "public role",
            "rank",
            "authority",
            "public office",
            "public status",
            "legacy",
            "achievement",
            "ambition",
            "visible competence",
        ],

        "derived_domains": [
            "bosses",
            "celebrities",
            "titles",
            "honors",
            "fame",
            "public image",
            "public goals",
            "life achievements",
            "lifelong undertakings",
            "renown",
            "civic burden",
            "public duty",
            "leadership",
            "institutional standing",
            "social legitimacy",
        ],

        "traditional_domains": [
            "kings",
            "rulers",
            "magistrates",
            "office",
            "honor",
            "dignity",
            "preferment",
            "public estimation",
            "worldly advancement",
            "command",
            "dignities",
        ],

        "esoteric_domains": [
            "visible summit",
            "lonely top",
            "burden of prominence",
            "high place under scrutiny",
            "name carried upward",
            "architecture of public consequence",
        ],

        "axes": {
            "visibility": 0.98,
            "relationality": 0.56,
            "materiality": 0.34,
            "institutionality": 0.94,
            "agency": 0.86,
            "publicness": 1.00,
            "immediacy": 0.54,
            "symbolic_density": 0.70,
        },

        "logic": {
            "entry_mode": "aspiration",
            "resource_mode": "elevation",
            "failure_mode": "disgrace, stagnation, illegitimacy, hollow status, public diminishment",
            "distortion_mode": "confusing visibility with worth, sacrificing private life to rank, mistaking office for virtue",
        },

        "notes": []
    },
    11: {
        "name": "Eleventh House",
        "archetypal_title": "Networked Belonging",

        "core_domains": [
            "friends",
            "groups",
            "community",
            "networks",
            "affiliations",
            "cohorts",
            "alliances",
            "group aspiration",
            "social belonging",
            "shared causes",
            "future orientation",
            "audience",
        ],

        "derived_domains": [
            "teams",
            "teamwork",
            "followers",
            "patrons",
            "supporters",
            "collaborators",
            "causes",
            "crowds",
            "systems with many nodes",
            "social networks",
            "audience blocs",
            "gatherings",
            "cohort affiliations",
            "group memberships",
            "clubs",
            "circles",
            "coalitions",
            "constituencies",
            "future plans",
        ],

        "traditional_domains": [
            "friends",
            "allies",
            "benefactors",
            "patrons",
            "hopes",
            "wishes",
            "associations",
            "good fortune through others",
            # "hopes",
            # "wishes",
            # "favorites",
        ],

        "esoteric_domains": [
            "collective identity",
            "field of affinity",
            "allies & audience",
            "shared horizon",
            "social constellations",
            "web of belonging",
            "collective futures",
        ],

        "axes": {
            "visibility": 0.62,
            "relationality": 0.90,
            "materiality": 0.22,
            "institutionality": 0.58,
            "agency": 0.64,
            "publicness": 0.82,
            "immediacy": 0.56,
            "symbolic_density": 0.66,
        },

        "logic": {
            "entry_mode": "affiliation",
            "resource_mode": "belonging",
            "failure_mode": "alienation, factionalism, shallow networking, social drift, dependence on group approval",
            "distortion_mode": "dissolving into the collective, mistaking visibility for belonging, substituting audience for friendship",
        },
        "notes": [
        "H5 is the performer; it's opposite, H11, is the audience.",
        "Subcultures arguably belong to H3 & H11. H3 for fluency with local symbolism, H11 for in-group belonging."
        ]
    },
    12: {
        "name": "Twelfth House",
        "archetypal_title": "That Which Withdraws from Ordinary Visibility",

        "core_domains": [
            "isolation",
            "seclusion",
            "confinement",
            "withdrawal",
            "sleep",
            "dreams",
            "retreat",
            "exile",
            "captivity",
            "hidden suffering",
            "hidden enemies",
            "erasure",
        ],

        "derived_domains": [
            "prisons",
            "hospitals",
            "backstage life",
            "going off the grid",
            "burnout",
            "unseen costs",
            "lost things",
            "forgotten things",
            "hidden things",
            "closet skeletons",
            "rest",
            "escape",
            "banishment",
            "ostracization",
            "lingering illness",
            "subconscious psyche",
            "psychic destabilization",
            "dissolution of identity",
            "ego-death",
        ],

        "traditional_domains": [
            "captivity",
            "banishment",
            "hidden enemies",
            "sorrow",
            "confinement",
            "self-undoing",
            "institutions of seclusion",
            "loss through obscurity",
            # "great cattle", #hilarious, though. And canonical.
        ],

        "esoteric_domains": [
            "far room",
            "things misplaced by time",
            "events unwitnessed by the world",
            "cost paid offstage",
            "dissolution of identity boundaries",
            "submerged life",
            "silent attrition",
            "withdrawal from the visible field",
        ],

        "axes": {
            "visibility": 0.02,
            "relationality": 0.22,
            "materiality": 0.38,
            "institutionality": 0.56,
            "agency": 0.18,
            "publicness": 0.04,
            "immediacy": 0.30,
            "symbolic_density": 0.96,
        },

        "logic": {
            "entry_mode": "withdrawal",
            "resource_mode": "seclusion",
            "failure_mode": "erasure, confinement, hidden depletion, psychic disorganization, loss of foothold in ordinary life",
            "distortion_mode": "romanticizing disappearance, confusing retreat with transcendence, surrendering agency through passivity or avoidance",
        },
        "notes": [
        "H4 vs H12: 4th is private foundation and enclosed belonging; 12th is enclosure without secure belonging.",
        "H9 vs H12: 9th is doctrine, pilgrimage, sanctioned meaning; 12th is seclusion, dissolution, hidden attrition. People blur these when they want to make retreat sound holy.",
        "H6 vs H12: 6th manages disorder; 12th is what escapes management, overwhelms functioning, or removes one from ordinary routine.",
        "H8 vs H12: 8th is entanglement and consequence; 12th is obscurity, confinement, erosion, disappearance. Did this happen because two forces became bound together? It was probably 8th house. Did it happen because something was hidden/trapped/slipping out of ordinary visibility? Then it was probably 12th. 8th says: “You are tied into this now.” 12th says: “You are being removed from view now.”"
        ],
        "fear": "vague dread, hidden depletion, loneliness, psychic drift, invisible pressure, loss of footing",
    },
}