"""Prose descriptions for specific natal body/sign placements.

Use :func:`get_position_description` rather than reading the mappings directly.
That gives callers one stable lookup as descriptions for bodies other than the
Moon are added over time.
"""

MOON_SIGN_DESCRIPTIONS: dict[str, str] = {
    "aries": (
        "An Aries Moon can become furious before anybody has technically done anything. "
        "That's the impressive part. You'll merely pause a fraction too long before "
        "answering, and suddenly they're walking around the room saying, \"Forget it,\" as "
        "though you've betrayed them during wartime. They don't actually want to forget "
        "it. They want you to catch up.\n\n"
        "Their feelings arrive without secretaries or appointments. Anger, delight, "
        "desire, indignation—every one of them comes straight through the front door. "
        "This makes them seem unreasonable, which they often are, but rarely dishonest. "
        "They may forgive you before you have finished understanding why they were mad. "
        "The trouble is that they assume emotional sincerity must be immediate. If you "
        "need three days to know how you feel, they suspect you're either dead or running "
        "some kind of racket.\n\n"
        "Underneath all the noise is a surprisingly young heart. It wants proof that life "
        "is happening now, that love means choosing, and that somebody will run after "
        "them when they storm out without their coat."
    ),
    "taurus": (
        "A Taurus Moon has a particular chair, though they may not formally announce it. "
        "You discover this by sitting in it.\n\n"
        "They are emotionally attached to the physical evidence of continuity: the same "
        "mug, the familiar grocery store, the blanket that should have been thrown away "
        "in 2014. People call this materialism because people are always misnaming "
        "things. What the Taurus Moon really wants is reassurance that existence will not "
        "rearrange the furniture overnight.\n\n"
        "They can tolerate quite a lot before objecting. This is frequently mistaken for "
        "docility. Then one day they say no in a tone that makes it clear the matter was "
        "decided during the Bronze Age. Persuasion becomes beside the point.\n\n"
        "They love through maintenance. They remember what you eat, repair the loose "
        "hinge, and put something warm in front of you without turning it into a ceremony. "
        "Their affections are slow because they consider permanence a serious claim. If "
        "they finally allow you into the private territory of their habits, they expect "
        "you not to start moving things around just to prove that you can."
    ),
    "gemini": (
        "A Gemini Moon will tell you exactly how they feel, provided they are permitted "
        "to offer six mutually incompatible answers.\n\n"
        "They process emotion by translating it into language, jokes, anecdotes, "
        "theories, impressions, and occasionally a devastating imitation of the person "
        "who upset them. Silence makes the feeling grow larger and less manageable. Once "
        "they can describe it, preferably to somebody alert enough to interrupt "
        "intelligently, it becomes portable.\n\n"
        "This gives them a reputation for shallowness. It isn't quite fair. Their feelings "
        "are not necessarily weak; they are mobile. A Gemini Moon can be heartsick and "
        "fascinated by a billboard in the same minute. They refuse the strange social "
        "rule that says sorrow becomes more authentic when one stops noticing everything "
        "else.\n\n"
        "What they need most is mental company. Not constant agreement—that would bore "
        "them half to death—but responsiveness. Ask another question. Notice the odd "
        "detail. Let the conversation wander somewhere neither of you intended. They fall "
        "in love partly with the person and partly with the private language that begins "
        "forming between them."
    ),
    "cancer": (
        "A Cancer Moon remembers the afternoon you were unkind to them in 2009, including "
        "the weather and what everybody ordered.\n\n"
        "Their emotional life is organized by association. A smell is never merely a "
        "smell; it is their grandmother's hallway, an old apartment, the summer before "
        "somebody left. The past remains active inside the present, constantly casting "
        "votes. This can make them profoundly perceptive and occasionally impossible. You "
        "may believe you are arguing about tonight's dinner. They are arguing with every "
        "person who ever made them feel unnecessary.\n\n"
        "They care for people almost involuntarily. They feed, protect, anticipate, and "
        "fuss, then become offended when nobody recognizes that each small service was "
        "also a declaration. Directly requesting affection seems vulgar to them. Surely "
        "you should have noticed.\n\n"
        "Their shell is not coldness. It is quality control. Beneath it sits an enormous, "
        "rather defenseless need to belong somewhere without having to audition "
        "continually. Once they decide you are family, the designation is difficult to "
        "revoke—even when, by every reasonable standard, it probably ought to be."
    ),
    "leo": (
        "A Leo Moon does not merely have feelings. The feelings require lighting.\n\n"
        "This sounds vain, but vanity is only the cheap version of what they want. They "
        "want the inner self to be recognized accurately and generously. Praise that is "
        "automatic or nonspecific irritates them. Tell them they're wonderful and they'll "
        "smile; tell them precisely what they did that nobody else could have done, and "
        "they may remember it for twenty years.\n\n"
        "They possess a dramatic emotional metabolism. Delight should be shared, loyalty "
        "demonstrated, affection made visible. Cool little arrangements in which everybody "
        "cares but nobody admits it strike them as spiritually stingy. They would rather "
        "risk embarrassment.\n\n"
        "When hurt, they become stately in a manner that convinces absolutely no one. "
        "Their dignity develops a limp. Yet they are often remarkably warm once the "
        "injured pride has been acknowledged. They don't need endless submission. They "
        "need to know they mattered enough to wound.\n\n"
        "Love them openly. Laugh at the performance without laughing at the heart producing "
        "it. There is a difference, and a Leo Moon can detect it from across a crowded "
        "room."
    ),
    "virgo": (
        "A Virgo Moon notices that you are tired before you do, but may express this by "
        "criticizing the way you loaded the dishwasher.\n\n"
        "Their feelings immediately volunteer for administrative duty. Sadness becomes a "
        "list. Anxiety becomes research. Love becomes remembering your medication, editing "
        "your résumé, and sending a link accompanied by \"This made me think of your "
        "situation.\" They are often accused of withholding tenderness when, from their "
        "perspective, they have spent the entire afternoon reorganizing your life in its "
        "honor.\n\n"
        "They fear being a burden, so they try to become useful enough to justify needing "
        "anything. This produces a peculiar sorrow: the person who helps everybody may "
        "feel secretly ashamed when they cannot repair themselves with equal efficiency.\n\n"
        "Their discernment is real, but it can become merciless when frightened. They find "
        "the loose thread because loose threads imply that larger failures are approaching. "
        "What settles them is not grand reassurance but trustworthy competence: follow "
        "through, arrive when you said you would, and notice the details they usually "
        "carry alone.\n\n"
        "Then they may relax for nearly eleven minutes."
    ),
    "libra": (
        "A Libra Moon can identify every side of an argument except, sometimes, their own.\n\n"
        "They are emotionally calibrated to relationship. A room feels wrong when two "
        "people are annoyed with each other, even if neither person is annoyed with them. "
        "They begin smoothing, translating, charming, and distributing blame into tasteful "
        "little portions. This looks peaceful. Internally, they may be accumulating "
        "grievances with the precision of an accountant.\n\n"
        "They need fairness, but fairness is not always the same as niceness. This is the "
        "lesson that keeps following them around. Their reluctance to disturb the "
        "atmosphere can permit exactly the ugliness they hoped to prevent. Eventually the "
        "repressed judgment emerges, elegantly dressed and several months late.\n\n"
        "A Libra Moon wants a companion with whom reality can be considered jointly. They "
        "feel more certain when a thought has crossed the space between two minds and "
        "returned intact. They are not necessarily dependent; they are dialogical. Solitude "
        "deprives them of their preferred instrument.\n\n"
        "Love, for them, is partly the ongoing construction of a shared world in which both "
        "people remain visible."
    ),
    "scorpio": (
        "A Scorpio Moon hears the second meaning before you finish delivering the first.\n\n"
        "They are not content with the stated feeling. They want its motive, ancestry, "
        "strategic function, and hidden cost. This makes them formidable judges of "
        "character and terrible company for anyone attempting casual deceit. Unfortunately, "
        "they may continue searching for concealment after they have already reached the "
        "truth.\n\n"
        "Trust is not granted because somebody seems pleasant. Pleasant people have done "
        "all sorts of things. Trust is built through evidence, tested under pressure, then "
        "guarded with unnerving intensity. Once attached, the Scorpio Moon does not feel "
        "affection as a decorative preference. It becomes binding.\n\n"
        "They can appear controlled precisely because the inner stakes are so high. Exposure "
        "feels consequential. They may reveal one small secret and watch very carefully "
        "what you do with it. Mishandle it, and a door closes somewhere.\n\n"
        "What they need is emotional courage without intrusion: someone who will tell the "
        "truth, withstand intensity, and refrain from treating their private depths as an "
        "entertaining excavation site."
    ),
    "sagittarius": (
        "A Sagittarius Moon can survive almost anything except the conclusion that it meant "
        "nothing.\n\n"
        "They require distance around a feeling. Immediately after disaster, some part of "
        "them is already trying to see the whole ridiculous story from a mountaintop. This "
        "can look insensitive, especially when everybody else would prefer ten uninterrupted "
        "minutes of despair. But meaning is how they breathe. Without it, emotion becomes "
        "confinement.\n\n"
        "They are restored by motion, possibility, jokes made at inappropriate but "
        "mathematically perfect moments, and the suspicion that a larger life exists just "
        "beyond the current arrangement. Attempts to manage their feelings usually make "
        "them flee faster than the feelings themselves.\n\n"
        "They are often more vulnerable than their optimism suggests. Cheerfulness can "
        "become a trap: if they are the buoyant one, who permits them to collapse? Still, "
        "they possess a genuine talent for reopening a future after others have declared "
        "it closed.\n\n"
        "Love them without shrinking the horizon. Tell them the truth, give them room, and "
        "be interesting enough that freedom occasionally chooses to come home."
    ),
    "capricorn": (
        "A Capricorn Moon may experience a complete emotional disaster and decide the first "
        "priority is answering their email.\n\n"
        "They distrust feelings that cannot present credentials. Neediness seems especially "
        "suspicious, including their own. Consequently, affection is routed through duty, "
        "provision, endurance, and the solemn completion of tasks nobody else remembered. "
        "They may not say \"I need you.\" They will simply include you in plans extending "
        "thirty years into the future.\n\n"
        "Their composure is frequently interpreted as strength, and it is strength, but "
        "strength can become compulsory. Many Capricorn Moons learned early that somebody "
        "had to remain functional. They became that somebody, then forgot functionality was "
        "originally an emergency role rather than a personality requirement.\n\n"
        "They need respect almost as much as love. Pity is intolerable. Sentiment without "
        "reliability is worse than useless. Show up when conditions are inconvenient; that "
        "is the language they believe.\n\n"
        "Under the reserve is a dry, mischievous tenderness that appears only when nobody "
        "is making a spectacle of it. If they let you see them being silly, you have been "
        "admitted to a very restricted department."
    ),
    "aquarius": (
        "An Aquarius Moon can explain their feelings with extraordinary intelligence while "
        "remaining several postal districts away from actually feeling them.\n\n"
        "They instinctively step outside emotion to examine its structure. This grants them "
        "unusual objectivity and sometimes makes intimate partners want to throw a cushion "
        "at them. While you are crying, they may become fascinated by the social assumptions "
        "underlying the argument. The analysis is not always avoidance. Often it is the only "
        "route by which the feeling becomes safe enough to approach.\n\n"
        "They need freedom from prescribed reactions. Tell them what they are supposed to "
        "feel, and whatever genuine emotion existed may instantly be replaced by resistance. "
        "Their private loyalties are deeper than their detached manner suggests, but they "
        "prefer affection founded on recognition rather than possession.\n\n"
        "They are drawn to people who are distinctly themselves. Conventional charm "
        "interests them less than an odd, internally consistent mind. Love should resemble "
        "friendship with additional electricity, not membership in a tiny authoritarian "
        "state.\n\n"
        "Give them room without disappearing. They want independence, certainly, but they "
        "also want somebody to notice when detachment has become loneliness."
    ),
    "pisces": (
        "A Pisces Moon can enter a room in a perfectly good mood and leave carrying somebody "
        "else's divorce.\n\n"
        "Their emotional boundaries are unusually permeable. Atmosphere reaches them before "
        "facts do. They register the tired waitress, the neglected plant, the song playing "
        "in another apartment. This sensitivity can produce compassion, imagination, and "
        "bewilderment about which feelings actually belong to them.\n\n"
        "They require retreat because ordinary reality arrives at excessive volume. Music, "
        "sleep, fantasy, water, private rituals—these are not always evasions. They are ways "
        "of returning the psyche to its original shape. The danger comes when retreat becomes "
        "indefinite and practical life is left outside ringing the bell.\n\n"
        "Pisces Moons can love people beyond reason, evidence, and occasionally basic "
        "self-preservation. They perceive unrealized possibilities so vividly that the "
        "actual person begins to seem like an unfortunate early draft. Their mercy is "
        "enormous; their judgment sometimes takes the afternoon off.\n\n"
        "What they need is gentleness with structure: someone who respects the dream but "
        "remembers the train schedule. They do not need to become less sensitive. They need "
        "somewhere reliable to put everything they sense."
    ),
}

MERCURY_SIGN_DESCRIPTIONS: dict[str, str] = {
    "aries": (
        "Mercury in Aries begins the sentence before the thought has finished putting on "
        "its shoes. This is not necessarily carelessness. Sometimes the thought simply "
        "knows it will lose its nerve if it has to wait in the hallway.\n\n"
        "Their minds work by ignition: a question appears, an answer leaps at it, and the "
        "rest of the evidence is invited to catch up. They are excellent at decisions, "
        "improvisation, first drafts, and saying what everybody else has been politely "
        "circling for forty minutes. They are less gifted at pretending a discussion is "
        "still open after they have become bored with it.\n\n"
        "Argument stimulates them. They may sound angry when they are merely interested, "
        "then become genuinely angry when asked why they are angry. Still, there is a "
        "cleanliness to their speech. You seldom have to excavate six layers of courtesy "
        "to find the point. Their best thinking is brave, quick, and original. Their worst "
        "thinking mistakes speed for certainty and volume for the arrival of proof."
    ),
    "taurus": (
        "Mercury in Taurus does not answer quickly merely because another person has "
        "developed an urgent need to hear themselves answered. The thought will be ready "
        "when it is ready. You may have time to order dessert.\n\n"
        "Their minds prefer the concrete: examples, evidence, demonstrated use, the thing "
        "itself sitting on the table. Abstract claims become more convincing once they can "
        "be attached to a cost, a texture, a consequence, or an ordinary Tuesday. They "
        "learn through repetition and retain what they have truly learned with formidable "
        "stability.\n\n"
        "Changing their mind is possible, but it requires more than rhetorical weather. "
        "They distrust people who revise their principles every time somebody invents a "
        "new adjective. Once convinced, they speak with a calm finality that can be either "
        "reassuring or maddening. Their best thinking is patient, grounded, and durable. "
        "Their worst thinking keeps defending an idea chiefly because it has already paid "
        "rent and settled in."
    ),
    "gemini": (
        "Mercury in Gemini has three thoughts while you are clearing your throat, and one "
        "of them has already become a joke. Conversation is not merely a way to report "
        "what they think. It is the machinery by which thinking happens.\n\n"
        "Their attention moves rapidly because the world keeps presenting footnotes. A "
        "single remark reminds them of a headline, a childhood story, an etymological "
        "peculiarity, and something scandalous they promised not to repeat by name. They "
        "make connections other minds miss, partly because other minds possess the good "
        "sense to stop after the third connection.\n\n"
        "They are verbally agile, socially observant, and capable of trying on an idea "
        "without marrying it. This is mistaken for insincerity by people who regard every "
        "sentence as a sworn affidavit. Their best thinking is curious, flexible, and "
        "brilliantly connective. Their worst thinking collects information as a substitute "
        "for deciding what any of it means."
    ),
    "cancer": (
        "Mercury in Cancer remembers not only what you said but how the room felt when you "
        "said it. You may produce an exact transcript in your defense. It will not help. "
        "The transcript has omitted the weather inside the sentence.\n\n"
        "Their thoughts develop through memory, intuition, and personal association. Facts "
        "rarely arrive alone; each one brings relatives. A place becomes all the people who "
        "occupied it, an object becomes its history, and an argument becomes the previous "
        "four arguments it resembles. This gives them a rich contextual intelligence, "
        "though it can make the present answer for crimes committed by the past.\n\n"
        "They communicate protectively. Sometimes this means tenderness and exquisite tact. "
        "Sometimes it means approaching the point sideways and then resenting you for not "
        "meeting them there. Their best thinking understands motive, atmosphere, and human "
        "consequence. Their worst thinking treats a strong feeling as evidence that the "
        "case has already been proved."
    ),
    "leo": (
        "Mercury in Leo does not see why a perfectly good idea should enter the room like "
        "an apologetic cousin. If the idea is worth saying, it deserves posture, timing, "
        "and possibly an audience that knows when to laugh.\n\n"
        "Their minds organize information around meaning and character. They remember the "
        "heroic detail, the insulting detail, and the detail that makes the whole episode "
        "work as a story. Mere data can bore them unless it participates in a larger claim. "
        "Once engaged, however, they speak with warmth and conviction powerful enough to "
        "make a provisional opinion sound engraved on a municipal building.\n\n"
        "They need intellectual respect. Being corrected is tolerable; being casually "
        "dismissed is an event with sequels. Their best thinking is creative, persuasive, "
        "generous, and capable of giving an idea memorable form. Their worst thinking turns "
        "disagreement into lèse-majesté and keeps performing certainty after certainty has "
        "quietly left the premises."
    ),
    "virgo": (
        "Mercury in Virgo notices that your argument contains a misplaced comma and, more "
        "seriously, a premise you smuggled in without declaring it. They will return both "
        "items to you in a small, labeled envelope.\n\n"
        "Their minds separate, classify, test, compare, and refine. They are less impressed "
        "by a grand idea than by whether the grand idea survives contact with instructions. "
        "Language matters because imprecision allows nonsense to enter dressed as depth. "
        "They often possess a quiet comic sense founded on noticing the exact discrepancy "
        "between what people claim to be doing and what they are plainly doing.\n\n"
        "The difficulty is that discernment has no natural stopping point. Every solution "
        "contains another possible correction, and every finished sentence could be made "
        "one percent less embarrassing. Their best thinking is lucid, useful, exact, and "
        "merciless toward faulty construction. Their worst thinking edits life so "
        "thoroughly that nothing is ever permitted to be finished."
    ),
    "libra": (
        "Mercury in Libra can hear one opinion and immediately perceive the intelligent "
        "objection to it. This is admirable until you ask what they themselves believe and "
        "watch an entire appellate court assemble behind their eyes.\n\n"
        "Their minds work through comparison. They place ideas beside one another, examine "
        "proportion, account for opposing interests, and search for wording that preserves "
        "both truth and civilization. They are gifted negotiators because they can restate "
        "another person's position without making it sound idiotic—a courtesy rarer than "
        "most universities would care to admit.\n\n"
        "The cost of this breadth is delayed commitment. A conclusion excludes alternatives, "
        "and alternatives often remain charming long after they have become impractical. "
        "Their best thinking is fair, elegant, relational, and alert to contradiction. "
        "Their worst thinking polishes the framing of a question until everybody has "
        "forgotten that an answer was required."
    ),
    "scorpio": (
        "Mercury in Scorpio listens to what you say, what you avoid saying, and the curious "
        "little piece of furniture your eyes keep visiting while you say it. The official "
        "statement is merely the first witness.\n\n"
        "Their minds pursue hidden structure: motive, leverage, contradiction, taboo, the "
        "fact somebody buried beneath three harmless facts and a laugh. They concentrate "
        "deeply and dislike explanations designed chiefly to make the explainer appear "
        "innocent. Superficial conversation can exhaust them, although they may use it "
        "expertly while deciding whether you are safe.\n\n"
        "They communicate selectively. Information has consequence, so why scatter it like "
        "birdseed? At their best, they are incisive researchers and fearless interpreters "
        "of difficult material. At their worst, suspicion becomes self-confirming: every "
        "denial proves concealment, every openness looks calculated, and the absence of a "
        "secret becomes the most suspicious secret of all."
    ),
    "sagittarius": (
        "Mercury in Sagittarius wants to know what the facts add up to. The facts themselves "
        "may occasionally object that several of them were not consulted, but by then the "
        "conclusion is halfway to another country.\n\n"
        "Their minds seek scale, pattern, principle, and implication. They are natural "
        "synthesizers, teachers, arguers, travelers between disciplines, and collectors of "
        "theories large enough to furnish a life. Details matter when they illuminate the "
        "whole. Details that merely sit there being accurate can seem almost provocatively "
        "unambitious.\n\n"
        "They speak candidly, sometimes out of honesty and sometimes because tact feels like "
        "an unreasonable administrative fee. Their best thinking is expansive, humorous, "
        "generous, and able to rescue significance from a pile of particulars. Their worst "
        "thinking exaggerates for momentum, mistakes conviction for comprehension, and "
        "delivers universal law from a sample size of two and an unusually memorable bus "
        "driver."
    ),
    "capricorn": (
        "Mercury in Capricorn likes an idea to have employment. It may be beautiful, "
        "ingenious, and morally uplifting, but what exactly does it do on Monday morning?\n\n"
        "Their minds arrange information into structures: priorities, sequences, causes, "
        "obligations, and outcomes. They respect expertise that can demonstrate how it "
        "became expert. Empty intellectual display leaves them cold, particularly when it "
        "requires six fashionable terms to avoid one ordinary noun. They tend to speak "
        "economically, with a dry precision that becomes funnier the less they acknowledge "
        "the joke.\n\n"
        "They may sound pessimistic when they are merely including gravity in the "
        "calculation. Yet practical judgment can harden into premature limitation. Their "
        "best thinking is strategic, disciplined, credible, and built to last. Their worst "
        "thinking rejects the unproven as impossible, then acts personally offended when "
        "the future declines to respect established procedure."
    ),
    "aquarius": (
        "Mercury in Aquarius encounters an accepted idea and immediately wonders who "
        "accepted it, under what conditions, and whether everybody might benefit from the "
        "mild inconvenience of taking it apart.\n\n"
        "Their minds favor systems, abstractions, anomalies, and views from sufficient "
        "distance to make ordinary assumptions look peculiar. They connect subjects that "
        "were introduced at separate parties and devise categories nobody requested but "
        "everybody later might find useful. Social convention interests them chiefly as evidence "
        "of collective behavior. This can make them original analysts and rather alienating "
        "dinner companions.\n\n"
        "They want intellectual freedom more than intellectual comfort. Unfortunately, "
        "contradiction can become its own convention, and the approved view is not "
        "automatically false merely because tedious people repeat it. Their best thinking "
        "is inventive, independent, systemic, and future-facing. Their worst thinking "
        "confuses emotional distance with objectivity and eccentricity with proof."
    ),
    "pisces": (
        "Mercury in Pisces thinks in weather, music, images, impressions, and connections "
        "that become obvious only after somebody has explained them beautifully. Ask for "
        "the route by which they arrived and you may receive a look suggesting routes are "
        "a rather provincial demand.\n\n"
        "Their minds are associative rather than strictly sequential. They perceive tone, "
        "symbol, implication, and the faint resemblance between two things that logic had "
        "seated at opposite ends of the room. Language becomes flexible in their hands. A "
        "word need not merely identify an object; it can release an entire atmosphere.\n\n"
        "This intelligence is difficult to measure because it may become less articulate "
        "when interrogated too literally. Still, intuition is not infallibility, and a "
        "beautiful association can be beautifully wrong. Their best thinking is imaginative, "
        "compassionate, symbolic, and capable of expressing what plain statement cannot. "
        "Their worst thinking drifts past definitions, absorbs other people's conclusions, "
        "and hopes coherence will arrive if nobody turns on the overhead lights."
    ),
}

RISING_SIGN_DESCRIPTIONS: dict[str, str] = {
    "aries": (
        "Aries Rising enters a situation as though somebody has just said, \"Go.\" Nobody "
        "may actually have said it. There may not even be a situation yet. They are often "
        "halfway into one before the rest of the room has located its coat.\n\n"
        "Their first instinct is action: approach, answer, challenge, begin. This gives them "
        "a direct physical presence even when the rest of the chart is shy, cautious, or "
        "quietly composing a twelve-page objection. Other people read them as candid, "
        "energetic, competitive, impatient, or some inconvenient combination of all four. "
        "They would rather risk an awkward encounter than stand around rehearsing one.\n\n"
        "The Aries Rising defense is momentum. Hesitation feels more dangerous than error. "
        "At their best, they bring courage and immediacy into stale environments. At their "
        "worst, they treat every closed door as a personal insult and every delay as evidence "
        "that civilization has failed specifically to inconvenience them."
    ),
    "taurus": (
        "Taurus Rising appears to have arrived several minutes before everybody else and "
        "used the time to become part of the furniture. There is something settled about "
        "them, even when internally they are reconsidering every decision since breakfast.\n\n"
        "They approach unfamiliar life through the senses. Is the place comfortable? Is the "
        "person consistent? Is anybody about to demand a sudden change of plans while using "
        "the phrase \"It'll be fun\"? Their pace is deliberate because they prefer to know "
        "what they are entering before they permit it to rearrange their nervous system. "
        "Others often read them as calm, self-contained, sensual, dependable, or stubborn.\n\n"
        "The Taurus Rising defense is immovability. If they remain still enough, perhaps the "
        "unwelcome development will become embarrassed and leave. At their best, they make "
        "a room feel inhabitable and give continuity to whatever they join. At their worst, "
        "they confuse resistance with discernment and call it patience long after everyone "
        "has missed the train."
    ),
    "gemini": (
        "Gemini Rising enters through conversation, even when no conversation is technically "
        "available. They will ask a question, notice a detail, read the noticeboard, and "
        "establish the entire social temperature before some people have finished entering "
        "their surname.\n\n"
        "Their manner is alert, mobile, and responsive. The eyes seem to be taking notes. "
        "They adapt quickly because they gather information quickly, altering tone and "
        "vocabulary to meet whoever is in front of them. This can make them seem youthful, "
        "witty, nervous, bright, scattered, or suspiciously acquainted with everybody. "
        "They are often easier to meet than to pin down.\n\n"
        "The Gemini Rising defense is mobility. If one identity becomes limiting, another "
        "angle is already waiting nearby with better material. At their best, they enliven "
        "an environment and connect people who would otherwise remain mutually irrelevant. "
        "At their worst, they keep the encounter moving so briskly that nobody, including "
        "them, has time to discover what was actually at stake."
    ),
    "cancer": (
        "Cancer Rising enters a room the way a hand enters uncertain water: gradually, with "
        "attention to temperature. Before offering themselves, they want to know what sort "
        "of place this is and whether anybody in it bites for recreation.\n\n"
        "Their first response is receptive rather than declarative. They notice mood, "
        "belonging, familiarity, and who appears to need looking after. Others often perceive "
        "softness, reserve, kindness, caution, or a curious maternal authority that has "
        "nothing to do with age or gender. Their expression may change markedly with the "
        "surroundings because their manner registers atmosphere before policy.\n\n"
        "The Cancer Rising defense is protective withdrawal. If safety is uncertain, they "
        "reduce exposure and observe from behind ordinary politeness. At their best, they "
        "make space personal, humane, and emotionally legible. At their worst, they treat "
        "unfamiliarity as danger, communicate displeasure through weather systems, and wait "
        "for others to infer needs that were never formally submitted."
    ),
    "leo": (
        "Leo Rising enters as though the room has been expecting someone, and it would be "
        "petty to investigate whether that person was actually them. Their presence tends "
        "to arrive all at once: face, posture, hair, laugh, and an unmistakable sense that "
        "the occasion has now acquired a center.\n\n"
        "They approach life through self-expression. Even quiet Leo Risings possess a "
        "certain composed visibility; they seem aware that other people are looking and "
        "inclined to give the looking something coherent to do. Others read them as warm, "
        "confident, dramatic, proud, playful, or grander than the immediate circumstances "
        "strictly require. Their manner says that dignity is a practical necessity.\n\n"
        "The Leo Rising defense is presentation. If they can carry themselves splendidly, "
        "perhaps uncertainty will lose interest. At their best, they animate social space "
        "and make other people feel more vivid inside it. At their worst, they begin treating "
        "ordinary acknowledgment as a constitutional obligation and disappointment as poor "
        "audience behavior."
    ),
    "virgo": (
        "Virgo Rising enters quietly enough to notice what everybody louder has missed. The "
        "chair is unstable, the schedule contradicts itself, and the host has been smiling "
        "with the desperate concentration of a person whose dinner is burning.\n\n"
        "Their first instinct is assessment. What is happening, what is required, and how "
        "can they participate without becoming an additional problem? This lends them a "
        "contained, observant, competent manner. Others may read them as modest, intelligent, "
        "helpful, discriminating, anxious, or mildly unimpressed. They often appear more "
        "controlled than they feel because self-monitoring begins before breakfast and does "
        "not recognize national holidays.\n\n"
        "The Virgo Rising defense is usefulness. If they are competent enough, perhaps nobody "
        "will examine whether they are comfortable. At their best, they improve whatever "
        "they enter through precise attention and unshowy care. At their worst, they meet "
        "life as a sequence of preventable defects and themselves as the most urgent one."
    ),
    "libra": (
        "Libra Rising enters a social situation already aware that entering it changes the "
        "balance. They smile, adjust, make room, and somehow establish that everyone present "
        "is civilized before the available evidence has fully agreed.\n\n"
        "Their manner is relational. They instinctively consider how they are being received, "
        "what the other person needs in order to respond, and which version of the truth can "
        "survive being spoken attractively. Others tend to read them as charming, composed, "
        "gracious, aesthetically aware, flirtatious, or more agreeable than they ultimately "
        "turn out to be. The ease is real; it is simply not the whole person.\n\n"
        "The Libra Rising defense is accommodation. If the interaction remains pleasant, "
        "perhaps conflict can be persuaded to die of neglect. At their best, they create "
        "reciprocity and make strangers feel considered rather than processed. At their "
        "worst, they perform agreement until resentment becomes the only honest participant "
        "left in the conversation."
    ),
    "scorpio": (
        "Scorpio Rising enters without appearing to enter. One moment the room is minding "
        "its business; the next, somebody near the wall seems to know why three people are "
        "lying. This is unnerving, particularly if only two people are speaking.\n\n"
        "Their first instinct is to evaluate power, motive, exposure, and risk. They reveal "
        "themselves selectively, which causes other people to fill the available silence "
        "with projections, confessions, or increasingly foolish jokes. Others often read "
        "them as intense, private, magnetic, suspicious, self-possessed, or dangerous in a "
        "way that may be entirely invented. Their reserve increases the amount of personality "
        "strangers manufacture on their behalf.\n\n"
        "The Scorpio Rising defense is control of access. At their best, they meet difficult "
        "situations with courage, perception, and formidable presence. At their worst, they "
        "treat ordinary uncertainty as a covert operation and make people pass examinations "
        "whose existence, subject, and grading criteria remain classified."
    ),
    "sagittarius": (
        "Sagittarius Rising enters as though the room might contain a story, a philosophical "
        "problem, or directions to somewhere better. They bring the unmistakable impression "
        "of onwardness. Even while seated, some part of them appears to be leaning toward a "
        "larger map.\n\n"
        "Their first response is expansion: talk to the stranger, test the boundary, make "
        "the joke, ask what lies beyond the accepted arrangement. Others read them as open, "
        "buoyant, candid, restless, opinionated, or refreshingly free of those internal "
        "committees that prevent most people from saying the first thing. Their enthusiasm "
        "can make an environment seem temporarily more possible.\n\n"
        "The Sagittarius Rising defense is escape into distance, humor, or meaning. At their "
        "best, they restore proportion and invite everybody into a wider life. At their "
        "worst, they step over limits while praising the horizon, promise more than the "
        "calendar can honor, and call departure a principle immediately after someone asks "
        "them to clean up."
    ),
    "capricorn": (
        "Capricorn Rising enters as though attendance may be noted. Even in casual settings "
        "they can project the contained seriousness of a person who has read the instructions "
        "and discovered, with little surprise, that nobody else has.\n\n"
        "Their first instinct is to establish structure: who is responsible, what is expected, "
        "which behavior belongs here, and whether the enterprise has any chance of surviving "
        "its organizers. Others often read them as reserved, mature, competent, ambitious, "
        "formal, or faintly disapproving. Sometimes they are simply shy in a suit of authority "
        "that arrived several years before the authority itself.\n\n"
        "The Capricorn Rising defense is self-command. If they appear capable, need can remain "
        "off the public record. At their best, they lend gravity, reliability, and direction "
        "to uncertain circumstances. At their worst, they behave as though spontaneity must "
        "first submit a proposal, then resent everyone else for enjoying what they privately "
        "wanted permission to do."
    ),
    "aquarius": (
        "Aquarius Rising enters at a slight angle to the occasion. They may be perfectly "
        "friendly, but some unmistakable part of them remains outside the room studying what "
        "sort of room would require everybody to behave this way.\n\n"
        "Their first instinct is differentiation. They notice the system, the expectation, "
        "and the available position from which neither can entirely claim them. Others may "
        "read them as unusual, detached, clever, approachable, remote, socially progressive, "
        "or personally opposed to matching socks. They can circulate widely while preserving "
        "an odd private distance, belonging to the group chiefly as its independent witness.\n\n"
        "The Aquarius Rising defense is detachment through distinctness. If they cannot be "
        "classified, perhaps they cannot be controlled. At their best, they make room for "
        "difference and expose assumptions everyone mistook for natural law. At their worst, "
        "they turn nonconformity into a uniform and act surprised when human intimacy refuses "
        "to function as an interesting social hypothesis."
    ),
    "pisces": (
        "Pisces Rising enters softly enough that other people may mistake the available space "
        "for an invitation to invent them. Within ten minutes they have been described as "
        "innocent, mysterious, absent-minded, profound, helpless, and exactly like somebody's "
        "aunt. None of these witnesses has consulted the defendant.\n\n"
        "Their first response is permeability. They absorb tone, imagery, expectation, and "
        "the emotional posture of the environment, adapting without always deciding to adapt. "
        "Others often read them as gentle, elusive, artistic, dreamy, sympathetic, confused, "
        "or curiously difficult to remember accurately. Their presence can feel less like a "
        "fixed statement than an atmosphere in which other people's assumptions become visible.\n\n"
        "The Pisces Rising defense is diffusion. A clearly defined target can be cornered; a "
        "shifting impression is harder to seize. At their best, they meet the world with "
        "imagination, receptivity, and unusual compassion. At their worst, adaptation becomes "
        "disappearance, boundaries become rumors, and they escape unwanted roles by becoming "
        "temporarily impossible to locate."
    ),
}

MIDHEAVEN_SIGN_DESCRIPTIONS: dict[str, str] = {
    "aries": (
        "An Aries Midheaven would prefer to be known for beginning something rather than "
        "for maintaining the tasteful little system somebody else began. Public life is "
        "approached as an arena of initiative: identify the opening, move first, and let "
        "the committee discover afterward that a decision has occurred.\n\n"
        "Their reputation tends to collect words like bold, independent, impatient, "
        "competitive, pioneering, and difficult to supervise. They are most convincing "
        "when visibly exercising nerve—leading, launching, defending, competing, or taking "
        "responsibility while everyone else is still discussing jurisdiction. Excessive "
        "oversight makes them professionally adolescent in record time.\n\n"
        "At their best, they become the person willing to act when action is socially "
        "expensive. At their worst, they mistake opposition for proof of importance and "
        "keep declaring new beginnings to avoid the humiliating middle portion where work "
        "must be repeated. Their public lesson is that leadership requires more than being "
        "the first person through the door. Occasionally it requires remembering why the "
        "door mattered."
    ),
    "taurus": (
        "A Taurus Midheaven wants a public life with weight, continuity, and some evidence "
        "that the roof will remain attached. They are rarely impressed by careers described "
        "mainly through excitement. Excitement is what people advertise when the pension is "
        "fictional.\n\n"
        "Their reputation develops through steadiness, taste, production, stewardship, "
        "material judgment, or the ability to make value tangible. They may be associated "
        "with money, land, food, art, beauty, craft, resources, or simply the rare competence "
        "of building something that still works after the launch party. Progress tends to "
        "be gradual because they prefer durable gains to theatrical ascent.\n\n"
        "At their best, they create security and preserve what deserves to endure. At their "
        "worst, stability becomes an expensive shrine to decisions made fifteen years ago. "
        "They may remain in an exhausted role because leaving would interrupt the biography. "
        "Their public lesson is that permanence has value only while the thing being "
        "preserved remains alive."
    ),
    "gemini": (
        "A Gemini Midheaven is publicly known for knowing things, saying things, connecting "
        "things, or asking the question that causes three established professionals to look "
        "suddenly preoccupied with their water glasses. One career may seem an unnecessarily "
        "strict response to possessing several interests.\n\n"
        "Their reputation gathers around communication, adaptability, information, wit, "
        "teaching, writing, sales, media, languages, networks, or intellectual versatility. "
        "They often appear professionally youthful because they continue learning and "
        "changing lanes after other people have purchased commemorative plaques. Public "
        "relevance depends on circulation; isolation makes their talents stale.\n\n"
        "At their best, they translate between worlds and keep institutions mentally awake. "
        "At their worst, variety becomes fragmentation, cleverness replaces authority, and "
        "the résumé begins to resemble the contents of a particularly ambitious junk drawer. "
        "Their public lesson is not to choose only one voice, but to develop a recognizable "
        "mind behind all the voices they use."
    ),
    "cancer": (
        "A Cancer Midheaven is often expected to care, even when the official job description "
        "has neglected to mention this. The public places emotional meaning upon them: "
        "protector, keeper, advocate, parent, custodian, representative of home—or the person "
        "everyone calls when the institution has behaved like an institution.\n\n"
        "Their reputation may form through nurturing, protection, memory, family, food, "
        "housing, history, education, public feeling, or the creation of belonging. Career "
        "choices are rarely separable from emotional security and private life. They need "
        "their work to matter personally, though public response may fluctuate because the "
        "collective tends to project its needs onto whatever appears maternal.\n\n"
        "At their best, they humanize power and build structures people can actually inhabit. "
        "At their worst, public duty becomes personal grievance, loyalty blocks necessary "
        "change, and professional criticism is received at the level of ancestry. Their "
        "public lesson is to care without making care an invisible contract nobody else "
        "realized they had signed."
    ),
    "leo": (
        "A Leo Midheaven has difficulty pretending that public recognition is vulgar. Usually "
        "the people calling it vulgar are already receiving plenty. They want their "
        "contribution to bear a name, a face, and enough distinction that nobody can confuse "
        "it with office furniture.\n\n"
        "Their reputation gathers around visibility, leadership, performance, creativity, "
        "authority, entertainment, or personal magnetism. Even in technical fields, they "
        "tend to become the representative, the director, the memorable teacher, or the "
        "person photographed holding the oversized ceremonial object. They need room to "
        "exercise individual style and wither under systems that reward anonymity as virtue.\n\n"
        "At their best, they dignify their vocation and encourage others to become more "
        "fully present. At their worst, applause becomes quality control, criticism becomes "
        "insubordination, and every group endeavor somehow acquires a starring role. Their "
        "public lesson is to seek recognition for the work without making recognition the "
        "work."
    ),
    "virgo": (
        "A Virgo Midheaven becomes publicly valuable through noticing what is incorrect, "
        "inefficient, unfinished, poorly worded, mildly contaminated, or likely to become "
        "expensive by Thursday. This does not always produce glamorous introductions. It "
        "does produce organizations that continue functioning.\n\n"
        "Their reputation rests on precision, service, analysis, health, craft, editing, "
        "diagnosis, method, or practical intelligence. They are often known less for occupying "
        "authority than for being the person authority quietly asks what went wrong. Public "
        "respect grows through mastery of details and a refusal to call approximation a "
        "finished product merely because the meeting has run long.\n\n"
        "At their best, they make expertise useful and improvement concrete. At their worst, "
        "standards become a hiding place from visibility, criticism replaces direction, and "
        "they remain indispensable in positions too small for them because being needed feels "
        "safer than being seen. Their public lesson is that competence need not apologize for "
        "having ambition."
    ),
    "libra": (
        "A Libra Midheaven is publicly judged not only by what they accomplish but by the "
        "arrangement of people, values, and appearances surrounding the accomplishment. They "
        "understand that merit does not enter public life alone. It brings presentation, "
        "alliances, timing, and somebody who knows where everyone should sit.\n\n"
        "Their reputation may develop through diplomacy, law, design, art, mediation, beauty, "
        "social intelligence, partnership, or the ability to make competing interests behave "
        "as though civilization was their own idea. They often advance through relationships "
        "and public goodwill, which is not superficial unless one believes cooperation occurs "
        "spontaneously among adults.\n\n"
        "At their best, they create legitimacy, proportion, and workable agreement. At their "
        "worst, image replaces position, partnership dilutes authorship, and the wish to remain "
        "acceptable produces decisions nobody can respect. Their public lesson is that grace "
        "has greater authority once it is willing to become definite."
    ),
    "scorpio": (
        "A Scorpio Midheaven tends to acquire a public aura of consequence. People assume "
        "they know more than they are saying, possess influence nobody has documented, or "
        "could survive an organizational collapse with a folder of evidence and an excellent "
        "coat. Sometimes this is accurate enough to be inconvenient.\n\n"
        "Their reputation forms through intensity, investigation, crisis, secrecy, shared "
        "resources, psychology, transformation, or the management of matters polite society "
        "prefers to delegate and forget. They may attract both trust and suspicion because "
        "their public role involves what is hidden, consequential, or difficult to control. "
        "Neutral reactions are not their most abundant natural resource.\n\n"
        "At their best, they expose corruption, steward power responsibly, and remain useful "
        "when superficial competence has fled. At their worst, professional life becomes a "
        "contest over leverage, privacy becomes opacity, and every rival is granted mythic "
        "importance. Their public lesson is that power grows more credible when it does not "
        "need everyone to feel its presence."
    ),
    "sagittarius": (
        "A Sagittarius Midheaven wants a vocation large enough to contain a point of view. "
        "Employment without meaning feels like being paid to remain indoors. They need some "
        "relationship to distance: geographical, intellectual, moral, educational, or the "
        "ordinary distance between an institution and the truth about itself.\n\n"
        "Their reputation may gather around teaching, publishing, travel, law, religion, "
        "philosophy, advocacy, broadcasting, scholarship, or cultural exchange. They are "
        "publicly persuasive when they connect particulars to a larger possibility. People "
        "look to them for vision, candor, optimism, and occasionally an opinion that would "
        "have benefited from being delayed until after lunch.\n\n"
        "At their best, they enlarge the public imagination and give knowledge a destination. "
        "At their worst, conviction outruns qualification, grand plans develop an allergy to "
        "administration, and freedom becomes a noble explanation for unfinished obligations. "
        "Their public lesson is that a horizon becomes useful only when someone can describe "
        "the road."
    ),
    "capricorn": (
        "A Capricorn Midheaven regards public life as a structure with stairs. They may deny "
        "wanting the upper floor, especially when young, but they have already noticed who "
        "holds the keys, which beams are load-bearing, and why the present management will "
        "eventually require replacement.\n\n"
        "Their reputation rests on authority, endurance, discipline, organization, strategy, "
        "status, and measurable accomplishment. Responsibility arrives early or accumulates "
        "naturally because they look capable of carrying it without composing a group email "
        "about the emotional impact. Recognition may come slowly, but it tends to solidify "
        "because they understand that credibility is built from repeated evidence.\n\n"
        "At their best, they become serious custodians of long-term work and use power with "
        "earned judgment. At their worst, hierarchy becomes morality, achievement becomes "
        "identity, and success keeps moving one floor higher whenever they arrive. Their "
        "public lesson is that authority should serve a purpose beyond proving they were "
        "qualified to possess it."
    ),
    "aquarius": (
        "An Aquarius Midheaven is rarely content to become an exemplary specimen of an "
        "existing profession. Something about the profession will need to be reorganized, "
        "modernized, democratized, automated, publicly questioned, or at least given a less "
        "embarrassing name.\n\n"
        "Their reputation forms through innovation, technology, science, reform, networks, "
        "collective movements, unusual expertise, or independence from conventional career "
        "paths. They may become publicly known as the outsider, futurist, dissenter, inventor, "
        "or baffling person who was dismissed five years before everybody adopted the idea. "
        "Their trajectory can be irregular because relevance matters more than sequence.\n\n"
        "At their best, they make institutions answerable to the future and create public "
        "space for neglected possibilities. At their worst, novelty becomes a credential, "
        "human needs are reduced to systems diagrams, and contrariness substitutes for "
        "substance. Their public lesson is that changing the world still requires dealing "
        "with the people currently living in it."
    ),
    "pisces": (
        "A Pisces Midheaven may spend years trying to determine whether vocation is supposed "
        "to be a profession, a calling, an artistic condition, an act of rescue, or something "
        "that mysteriously happens while one is occupied with all four. Public direction is "
        "felt before it is easily named.\n\n"
        "Their reputation may arise through art, music, film, healing, spirituality, charity, "
        "imagination, compassion, institutions of retreat, or work involving what cannot be "
        "neatly measured. The public often projects fantasies onto them: saint, fraud, victim, "
        "genius, innocent, savior, disappointment. Their professional identity may remain "
        "fluid because the contribution matters more to them than the category containing it.\n\n"
        "At their best, they give public form to subtle realities and make compassion active. "
        "At their worst, purpose dissolves into longing, boundaries vanish from the job "
        "description, and being misunderstood becomes easier than becoming accountable. Their "
        "public lesson is to build a vessel sturdy enough that inspiration can arrive without "
        "flooding the office."
    ),
}

POSITION_DESCRIPTIONS: dict[str, dict[str, str]] = {
    # "sun": SUN_SIGN_DESCRIPTIONS,
    "moon": MOON_SIGN_DESCRIPTIONS,
    "mercury": MERCURY_SIGN_DESCRIPTIONS,
    # "venus": VENUS_SIGN_DESCRIPTIONS,
    # "mars": MARS_SIGN_DESCRIPTIONS,
    # "jupiter": JUPITER_SIGN_DESCRIPTIONS,
    # "saturn": SATURN_SIGN_DESCRIPTIONS,
    # "uranus": URANUS_SIGN_DESCRIPTIONS,
    # "neptune": NEPTUNE_SIGN_DESCRIPTIONS,
    # "pluto": PLUTO_SIGN_DESCRIPTIONS,
    "as": RISING_SIGN_DESCRIPTIONS,  # aka rising, ASC, ascendant
    # "mc": MIDHEAVEN_SIGN_DESCRIPTIONS,  # aka midheaven, medium coeli
    # "ic": IC_SIGN_DESCRIPTIONS,  # aka imum coeli
    # "ds": DESCENDANT_SIGN_DESCRIPTIONS,  # aka descendant
}


def get_position_description(body: object, sign: object) -> str | None:
    """Return the curated prose for a body/sign placement, when available.

    Keys are normalized at this boundary so GUI display capitalization does not
    leak into the reference data. Empty descriptions are treated as unavailable,
    allowing an entry to be drafted without suppressing the generic fallback.
    """

    body_key = str(body or "").strip().casefold()
    sign_key = str(sign or "").strip().casefold()
    description = POSITION_DESCRIPTIONS.get(body_key, {}).get(sign_key, "").strip()
    return description or None
