"""Reference descriptions for natal Moon signs."""

MOON_SIGN_DESCRIPTIONS: dict[str, str] = {
    "aries": (
        "An Aries Moon can become furious before anybody has technically done anything. "
        "That's the impressive part. You'll merely pause a fraction too long before "
        "answering, and suddenly they're walking around the room saying, \"Forget it,\" as "
        "though you've betrayed them during wartime. They don't actually want to forget "
        "it. They want you to catch up.\n\n"
        "Their feelings arrive without secretaries or appointments. Anger, delight, "
        "desire, indignation—every one of them comes straight through the front door. "
        "This makes them seem unreasonable, which they often are, but rarely dishonest. "
        "They may forgive you before you have finished understanding why they were mad. "
        "The trouble is that they assume emotional sincerity must be immediate. If you "
        "need three days to know how you feel, they suspect you're either dead or running "
        "some kind of racket.\n\n"
        "Underneath all the noise is a surprisingly young heart. It wants proof that life "
        "is happening now, that love means choosing, and that somebody will run after "
        "them when they storm out without their coat."
    ),
    "taurus": (
        "A Taurus Moon has a particular chair, though they may not formally announce it. "
        "You discover this by sitting in it.\n\n"
        "They are emotionally attached to the physical evidence of continuity: the same "
        "mug, the familiar grocery store, the blanket that should have been thrown away "
        "in 2014. People call this materialism because people are always misnaming "
        "things. What the Taurus Moon really wants is reassurance that existence will not "
        "rearrange the furniture overnight.\n\n"
        "They can tolerate quite a lot before objecting. This is frequently mistaken for "
        "docility. Then one day they say no in a tone that makes it clear the matter was "
        "decided during the Bronze Age. Persuasion becomes beside the point.\n\n"
        "They love through maintenance. They remember what you eat, repair the loose "
        "hinge, and put something warm in front of you without turning it into a ceremony. "
        "Their affections are slow because they consider permanence a serious claim. If "
        "they finally allow you into the private territory of their habits, they expect "
        "you not to start moving things around just to prove that you can."
    ),
    "gemini": (
        "A Gemini Moon will tell you exactly how they feel, provided they are permitted "
        "to offer six mutually incompatible answers.\n\n"
        "They process emotion by translating it into language, jokes, anecdotes, "
        "theories, impressions, and occasionally a devastating imitation of the person "
        "who upset them. Silence makes the feeling grow larger and less manageable. Once "
        "they can describe it, preferably to somebody alert enough to interrupt "
        "intelligently, it becomes portable.\n\n"
        "This gives them a reputation for shallowness. It isn't quite fair. Their feelings "
        "are not necessarily weak; they are mobile. A Gemini Moon can be heartsick and "
        "fascinated by a billboard in the same minute. They refuse the strange social "
        "rule that says sorrow becomes more authentic when one stops noticing everything "
        "else.\n\n"
        "What they need most is mental company. Not constant agreement—that would bore "
        "them half to death—but responsiveness. Ask another question. Notice the odd "
        "detail. Let the conversation wander somewhere neither of you intended. They fall "
        "in love partly with the person and partly with the private language that begins "
        "forming between them."
    ),
    "cancer": (
        "A Cancer Moon remembers the afternoon you were unkind to them in 2009, including "
        "the weather and what everybody ordered.\n\n"
        "Their emotional life is organized by association. A smell is never merely a "
        "smell; it is their grandmother's hallway, an old apartment, the summer before "
        "somebody left. The past remains active inside the present, constantly casting "
        "votes. This can make them profoundly perceptive and occasionally impossible. You "
        "may believe you are arguing about tonight's dinner. They are arguing with every "
        "person who ever made them feel unnecessary.\n\n"
        "They care for people almost involuntarily. They feed, protect, anticipate, and "
        "fuss, then become offended when nobody recognizes that each small service was "
        "also a declaration. Directly requesting affection seems vulgar to them. Surely "
        "you should have noticed.\n\n"
        "Their shell is not coldness. It is quality control. Beneath it sits an enormous, "
        "rather defenseless need to belong somewhere without having to audition "
        "continually. Once they decide you are family, the designation is difficult to "
        "revoke—even when, by every reasonable standard, it probably ought to be."
    ),
    "leo": (
        "A Leo Moon does not merely have feelings. The feelings require lighting.\n\n"
        "This sounds vain, but vanity is only the cheap version of what they want. They "
        "want the inner self to be recognized accurately and generously. Praise that is "
        "automatic or nonspecific irritates them. Tell them they're wonderful and they'll "
        "smile; tell them precisely what they did that nobody else could have done, and "
        "they may remember it for twenty years.\n\n"
        "They possess a dramatic emotional metabolism. Delight should be shared, loyalty "
        "demonstrated, affection made visible. Cool little arrangements in which everybody "
        "cares but nobody admits it strike them as spiritually stingy. They would rather "
        "risk embarrassment.\n\n"
        "When hurt, they become stately in a manner that convinces absolutely no one. "
        "Their dignity develops a limp. Yet they are often remarkably warm once the "
        "injured pride has been acknowledged. They don't need endless submission. They "
        "need to know they mattered enough to wound.\n\n"
        "Love them openly. Laugh at the performance without laughing at the heart producing "
        "it. There is a difference, and a Leo Moon can detect it from across a crowded "
        "room."
    ),
    "virgo": (
        "A Virgo Moon notices that you are tired before you do, but may express this by "
        "criticizing the way you loaded the dishwasher.\n\n"
        "Their feelings immediately volunteer for administrative duty. Sadness becomes a "
        "list. Anxiety becomes research. Love becomes remembering your medication, editing "
        "your résumé, and sending a link accompanied by \"This made me think of your "
        "situation.\" They are often accused of withholding tenderness when, from their "
        "perspective, they have spent the entire afternoon reorganizing your life in its "
        "honor.\n\n"
        "They fear being a burden, so they try to become useful enough to justify needing "
        "anything. This produces a peculiar sorrow: the person who helps everybody may "
        "feel secretly ashamed when they cannot repair themselves with equal efficiency.\n\n"
        "Their discernment is real, but it can become merciless when frightened. They find "
        "the loose thread because loose threads imply that larger failures are approaching. "
        "What settles them is not grand reassurance but trustworthy competence: follow "
        "through, arrive when you said you would, and notice the details they usually "
        "carry alone.\n\n"
        "Then they may relax for nearly eleven minutes."
    ),
    "libra": (
        "A Libra Moon can identify every side of an argument except, sometimes, their own.\n\n"
        "They are emotionally calibrated to relationship. A room feels wrong when two "
        "people are annoyed with each other, even if neither person is annoyed with them. "
        "They begin smoothing, translating, charming, and distributing blame into tasteful "
        "little portions. This looks peaceful. Internally, they may be accumulating "
        "grievances with the precision of an accountant.\n\n"
        "They need fairness, but fairness is not always the same as niceness. This is the "
        "lesson that keeps following them around. Their reluctance to disturb the "
        "atmosphere can permit exactly the ugliness they hoped to prevent. Eventually the "
        "repressed judgment emerges, elegantly dressed and several months late.\n\n"
        "A Libra Moon wants a companion with whom reality can be considered jointly. They "
        "feel more certain when a thought has crossed the space between two minds and "
        "returned intact. They are not necessarily dependent; they are dialogical. Solitude "
        "deprives them of their preferred instrument.\n\n"
        "Love, for them, is partly the ongoing construction of a shared world in which both "
        "people remain visible."
    ),
    "scorpio": (
        "A Scorpio Moon hears the second meaning before you finish delivering the first.\n\n"
        "They are not content with the stated feeling. They want its motive, ancestry, "
        "strategic function, and hidden cost. This makes them formidable judges of "
        "character and terrible company for anyone attempting casual deceit. Unfortunately, "
        "they may continue searching for concealment after they have already reached the "
        "truth.\n\n"
        "Trust is not granted because somebody seems pleasant. Pleasant people have done "
        "all sorts of things. Trust is built through evidence, tested under pressure, then "
        "guarded with unnerving intensity. Once attached, the Scorpio Moon does not feel "
        "affection as a decorative preference. It becomes binding.\n\n"
        "They can appear controlled precisely because the inner stakes are so high. Exposure "
        "feels consequential. They may reveal one small secret and watch very carefully "
        "what you do with it. Mishandle it, and a door closes somewhere.\n\n"
        "What they need is emotional courage without intrusion: someone who will tell the "
        "truth, withstand intensity, and refrain from treating their private depths as an "
        "entertaining excavation site."
    ),
    "sagittarius": (
        "A Sagittarius Moon can survive almost anything except the conclusion that it meant "
        "nothing.\n\n"
        "They require distance around a feeling. Immediately after disaster, some part of "
        "them is already trying to see the whole ridiculous story from a mountaintop. This "
        "can look insensitive, especially when everybody else would prefer ten uninterrupted "
        "minutes of despair. But meaning is how they breathe. Without it, emotion becomes "
        "confinement.\n\n"
        "They are restored by motion, possibility, jokes made at inappropriate but "
        "mathematically perfect moments, and the suspicion that a larger life exists just "
        "beyond the current arrangement. Attempts to manage their feelings usually make "
        "them flee faster than the feelings themselves.\n\n"
        "They are often more vulnerable than their optimism suggests. Cheerfulness can "
        "become a trap: if they are the buoyant one, who permits them to collapse? Still, "
        "they possess a genuine talent for reopening a future after others have declared "
        "it closed.\n\n"
        "Love them without shrinking the horizon. Tell them the truth, give them room, and "
        "be interesting enough that freedom occasionally chooses to come home."
    ),
    "capricorn": (
        "A Capricorn Moon may experience a complete emotional disaster and decide the first "
        "priority is answering their email.\n\n"
        "They distrust feelings that cannot present credentials. Neediness seems especially "
        "suspicious, including their own. Consequently, affection is routed through duty, "
        "provision, endurance, and the solemn completion of tasks nobody else remembered. "
        "They may not say \"I need you.\" They will simply include you in plans extending "
        "thirty years into the future.\n\n"
        "Their composure is frequently interpreted as strength, and it is strength, but "
        "strength can become compulsory. Many Capricorn Moons learned early that somebody "
        "had to remain functional. They became that somebody, then forgot functionality was "
        "originally an emergency role rather than a personality requirement.\n\n"
        "They need respect almost as much as love. Pity is intolerable. Sentiment without "
        "reliability is worse than useless. Show up when conditions are inconvenient; that "
        "is the language they believe.\n\n"
        "Under the reserve is a dry, mischievous tenderness that appears only when nobody "
        "is making a spectacle of it. If they let you see them being silly, you have been "
        "admitted to a very restricted department."
    ),
    "aquarius": (
        "An Aquarius Moon can explain their feelings with extraordinary intelligence while "
        "remaining several postal districts away from actually feeling them.\n\n"
        "They instinctively step outside emotion to examine its structure. This grants them "
        "unusual objectivity and sometimes makes intimate partners want to throw a cushion "
        "at them. While you are crying, they may become fascinated by the social assumptions "
        "underlying the argument. The analysis is not always avoidance. Often it is the only "
        "route by which the feeling becomes safe enough to approach.\n\n"
        "They need freedom from prescribed reactions. Tell them what they are supposed to "
        "feel, and whatever genuine emotion existed may instantly be replaced by resistance. "
        "Their private loyalties are deeper than their detached manner suggests, but they "
        "prefer affection founded on recognition rather than possession.\n\n"
        "They are drawn to people who are distinctly themselves. Conventional charm "
        "interests them less than an odd, internally consistent mind. Love should resemble "
        "friendship with additional electricity, not membership in a tiny authoritarian "
        "state.\n\n"
        "Give them room without disappearing. They want independence, certainly, but they "
        "also want somebody to notice when detachment has become loneliness."
    ),
    "pisces": (
        "A Pisces Moon can enter a room in a perfectly good mood and leave carrying somebody "
        "else's divorce.\n\n"
        "Their emotional boundaries are unusually permeable. Atmosphere reaches them before "
        "facts do. They register the tired waitress, the neglected plant, the song playing "
        "in another apartment. This sensitivity can produce compassion, imagination, and "
        "bewilderment about which feelings actually belong to them.\n\n"
        "They require retreat because ordinary reality arrives at excessive volume. Music, "
        "sleep, fantasy, water, private rituals—these are not always evasions. They are ways "
        "of returning the psyche to its original shape. The danger comes when retreat becomes "
        "indefinite and practical life is left outside ringing the bell.\n\n"
        "Pisces Moons can love people beyond reason, evidence, and occasionally basic "
        "self-preservation. They perceive unrealized possibilities so vividly that the "
        "actual person begins to seem like an unfortunate early draft. Their mercy is "
        "enormous; their judgment sometimes takes the afternoon off.\n\n"
        "What they need is gentleness with structure: someone who respects the dream but "
        "remembers the train schedule. They do not need to become less sensitive. They need "
        "somewhere reliable to put everything they sense."
    ),
}
