"""Semantic theme reference for cross-system chart synthesis.

This module is deliberately a routing/indexing layer, not an interpretation
engine. Themes answer "what human subject is this chart factor about?" while
the existing astrology, Human Design, and BaZi engines remain responsible for
calculating and interpreting their own symbols.

Design rules
------------
* THEMES is flat. ``family`` is organizational only and may be changed without
  changing a theme's stable key.
* Labels are presentation text. Stable keys are intended for internal
  references, so labels can be renamed freely.
* Membership is non-exclusive: one symbol may legitimately belong to many
  themes.
* Cross-system mappings are independent. A Human Design gate should earn a
  theme from its Human Design meaning, not merely from its zodiacal position;
  the same principle applies to BaZi.
* Empty lists are meaningful. They mean that no direct correspondence has yet
  been judged defensible, not that a correspondence is forbidden forever.
* Aspects are intentionally absent. They are relational operators/modifiers
  (pressure, flow, polarization, adjustment, etc.), not ordinary thematic
  membership.
* All seed memberships in this file are provisional and expected to evolve.

Weights
-------
Every listed item has an implicit weight of 1.0 unless a future
``weight_overrides`` entry says otherwise. An item not listed for a theme has
weight 0.0 for that theme.
"""

from __future__ import annotations

from numbers import Real
from typing import Any


DEFAULT_THEME_ITEM_WEIGHT = 1.0

WEIGHTED_THEME_PROPERTIES = (
    "signs",
    "houses",
    "bodies",
    "elements",
    "modes",
    "nakshatras",
    "gates",
    "channels",
    "crosses",
    "centers",
    "profiles",
    "authorities",
    "bazisigns",
)

THEME_METADATA_LIST_PROPERTIES = (
    "color",
    "description",
    "quotes",
    "aliases",
)

THEME_FAMILIES = {
    'self_agency_power': {
        "label": 'Self, Agency & Power',
        "description": 'Identity, agency, direction, visibility, influence, authority, and the use of personal force.',
    },
    'mind_language_truth': {
        "label": 'Mind, Language & Truth',
        "description": 'Thinking, learning, communication, interpretation, evidence, doctrine, and systems of meaning.',
    },
    'relationship_attachment_society': {
        "label": 'Relationship, Attachment & Society',
        "description": 'Attraction, bonds, contracts, kinship, reciprocity, community, and social opposition.',
    },
    'material_life_work_survival': {
        "label": 'Material Life, Work & Survival',
        "description": 'Resources, security, labor, health, endurance, institutions, and material continuity.',
    },
    'shadow_crisis_transformation': {
        "label": 'Shadow, Crisis & Transformation',
        "description": 'Hidden material, taboo, fear, conflict, loss, crisis, coercion, healing, and regeneration.',
    },
    'change_boundaries_disappearance': {
        "label": 'Change, Boundaries & Disappearance',
        "description": 'Mutation, transition, timing, movement, confinement, retreat, separation, and permeability.',
    },
    'imagination_expanded_perspective': {
        "label": 'Imagination & Expanded Perspective',
        "description": 'Imagination, fantasy, altered perspective, experience, possibility, abundance, and heightened awareness.',
    },
}


def _theme(
    label: str,
    family: str,
    *,
    signs: list[str] | None = None,
    houses: list[int] | None = None,
    bodies: list[str] | None = None,
    elements: list[str] | None = None,
    modes: list[str] | None = None,
    nakshatras: list[str] | None = None,
    gates: list[int] | None = None,
    channels: list[str] | None = None,
    crosses: list[str] | None = None,
    centers: list[str] | None = None,
    profiles: list[str] | None = None,
    authorities: list[str] | None = None,
    bazisigns: list[str] | None = None,
    color: list[str] | None = None,
    description: list[str] | None = None,
    quotes: list[str] | None = None,
    aliases: list[str] | None = None,
    notes: str = "",
    default_weight: float = DEFAULT_THEME_ITEM_WEIGHT,
    weight_overrides: dict[str, dict[Any, float]] | None = None,
) -> dict[str, Any]:
    """Create one theme entry with the complete, stable schema."""

    return {
        "label": label,
        "family": family,
        "signs": list(signs or []),
        "houses": list(houses or []),
        "bodies": list(bodies or []),
        "elements": list(elements or []),
        "modes": list(modes or []),
        "nakshatras": list(nakshatras or []),
        "gates": list(gates or []),
        "channels": list(channels or []),
        "crosses": list(crosses or []),
        "centers": list(centers or []),
        "profiles": list(profiles or []),
        "authorities": list(authorities or []),
        "bazisigns": list(bazisigns or []),
        "color": list(color or []),
        "description": list(description or []),
        "quotes": list(quotes or []),
        "aliases": list(aliases or []),
        "notes": notes,
        "default_weight": float(default_weight),
        "weight_overrides": {
            property_name: dict(overrides)
            for property_name, overrides in (weight_overrides or {}).items()
        },
    }


THEMES = {
    'identity_selfhood': _theme(
        'Identity & Selfhood',
        'self_agency_power',
        signs=['Leo', 'Aries'],
        houses=[1],
        bodies=['Sun', 'AS'],
        elements=['Fire'],
        nakshatras=['Magha', 'Uttara Phalguni', 'Uttara Ashadha'],
        gates=[1, 2, 10, 25, 46],
        crosses=['Self-Expression', 'Identification', 'the Sphinx', 'the Vessel of Love'],
        centers=['G'],
        bazisigns=['tiger', 'dragon'],
    ),
    'direction_purpose': _theme(
        'Direction & Purpose',
        'self_agency_power',
        signs=['Leo', 'Sagittarius', 'Capricorn'],
        houses=[1, 9, 10],
        bodies=['Sun', 'Jupiter', 'Rahu'],
        nakshatras=['Ashwini', 'Vishakha', 'Uttara Ashadha', 'Revati'],
        gates=[2, 7, 14, 28, 38],
        channels=['2-14', '28-38'],
        crosses=['the Sphinx', 'the Driver', 'Alignment', 'Incarnation', 'Fates'],
        centers=['G'],
        bazisigns=['tiger', 'horse', 'dragon'],
    ),
    'visibility_recognition': _theme(
        'Visibility & Recognition',
        'self_agency_power',
        signs=['Leo', 'Capricorn'],
        houses=[1, 5, 10],
        bodies=['Sun', 'Venus', 'MC'],
        elements=['Fire'],
        nakshatras=['Magha', 'Purva Phalguni', 'Chitra', 'Dhanishta'],
        gates=[1, 8, 20, 31],
        channels=['8-1', '7-31'],
        crosses=['Self-Expression', 'Influence', 'the Alpha', 'Rulership'],
        centers=['Throat', 'G'],
        bazisigns=['dragon', 'rooster'],
    ),
    'leadership_authority': _theme(
        'Leadership & Authority',
        'self_agency_power',
        signs=['Leo', 'Capricorn', 'Aries'],
        houses=[10, 11],
        bodies=['Sun', 'Saturn', 'Jupiter', 'MC'],
        elements=['Fire', 'Earth'],
        modes=['cardinal'],
        nakshatras=['Magha', 'Jyeshtha', 'Uttara Ashadha'],
        gates=[7, 21, 31, 45],
        channels=['7-31', '21-45'],
        crosses=['Rulership', 'Influence', 'the Alpha', 'Dominion', 'the Driver'],
        centers=['Throat', 'Ego', 'G'],
        bazisigns=['dragon', 'tiger', 'dog'],
    ),
    'autonomy_defiance': _theme(
        'Autonomy & Defiance',
        'self_agency_power',
        signs=['Aquarius', 'Aries', 'Scorpio'],
        houses=[1, 11],
        bodies=['Uranus', 'Mean Lilith', 'Osculating Lilith', 'Natural Lilith', 'Mars'],
        modes=['fixed', 'cardinal'],
        nakshatras=['Ashwini', 'Swati', 'Mula', 'Purva Bhadrapada'],
        gates=[10, 25, 38, 39, 51],
        channels=['10-34', '25-51', '28-38'],
        crosses=['Defiance', 'Individualism', 'Revolution', 'Opposition'],
        bazisigns=['tiger', 'horse'],
    ),
    'action_assertion': _theme(
        'Action & Assertion',
        'self_agency_power',
        signs=['Aries', 'Leo', 'Sagittarius'],
        houses=[1, 5, 10],
        bodies=['Mars', 'Sun'],
        elements=['Fire'],
        modes=['cardinal'],
        nakshatras=['Ashwini', 'Krittika', 'Vishakha'],
        gates=[20, 34, 51, 53],
        channels=['34-20', '10-34', '25-51'],
        crosses=['Penetration', 'the Driver', 'Power', 'Endeavour'],
        bazisigns=['tiger', 'horse'],
    ),
    'risk_courage': _theme(
        'Risk & Courage',
        'self_agency_power',
        signs=['Aries', 'Sagittarius', 'Scorpio'],
        houses=[5, 8, 9],
        bodies=['Mars', 'Jupiter', 'Rahu'],
        elements=['Fire'],
        nakshatras=['Ashwini', 'Bharani', 'Vishakha', 'Purva Bhadrapada'],
        gates=[28, 29, 30, 38, 51],
        channels=['28-38', '25-51'],
        crosses=['Risks', 'Shock', 'Penetration', 'the Unexpected'],
        bazisigns=['tiger', 'dragon'],
    ),
    'ambition_advancement': _theme(
        'Ambition & Advancement',
        'self_agency_power',
        signs=['Capricorn', 'Aries', 'Sagittarius'],
        houses=[2, 10],
        bodies=['Saturn', 'Mars', 'Jupiter', 'Rahu'],
        elements=['Earth', 'Fire'],
        modes=['cardinal'],
        nakshatras=['Vishakha', 'Jyeshtha', 'Uttara Ashadha', 'Dhanishta'],
        gates=[14, 21, 32, 45, 54],
        channels=['32-54', '21-45'],
        crosses=['Ambition', 'Endeavour', 'Industry', 'Empowering'],
        bazisigns=['tiger', 'dragon', 'ox'],
    ),
    'power_control': _theme(
        'Power & Control',
        'self_agency_power',
        signs=['Scorpio', 'Capricorn', 'Aries'],
        houses=[8, 10],
        bodies=['Pluto', 'Saturn', 'Mars', 'Pallas'],
        nakshatras=['Bharani', 'Ashlesha', 'Magha', 'Jyeshtha'],
        gates=[14, 21, 34, 45, 50],
        channels=['21-45', '34-20', '34-57'],
        crosses=['Power', 'Control', 'Rulership', 'Dominion'],
        centers=['Ego', 'Sacral'],
        bazisigns=['snake', 'tiger', 'dragon'],
    ),
    'influence_persuasion': _theme(
        'Influence & Persuasion',
        'self_agency_power',
        signs=['Gemini', 'Libra', 'Leo'],
        houses=[3, 7, 10, 11],
        bodies=['Mercury', 'Venus', 'Jupiter', 'Pallas'],
        elements=['Air'],
        nakshatras=['Ashlesha', 'Purva Phalguni', 'Swati', 'Jyeshtha'],
        gates=[8, 26, 31, 44, 45],
        channels=['44-26', '7-31', '21-45'],
        crosses=['Influence', 'the Trickster', 'Informing', 'Articulation'],
        bazisigns=['snake', 'monkey'],
    ),
    'possession_dominion': _theme(
        'Possession & Dominion',
        'self_agency_power',
        signs=['Scorpio', 'Taurus', 'Capricorn'],
        houses=[2, 8, 10],
        bodies=['Pluto', 'Saturn', 'Venus'],
        elements=['Earth'],
        nakshatras=['Bharani', 'Magha', 'Jyeshtha'],
        gates=[14, 21, 45, 50],
        channels=['21-45'],
        crosses=['Possession', 'Dominion', 'Rulership', 'Control'],
        bazisigns=['tiger', 'snake'],
    ),
    'contribution_usefulness': _theme(
        'Contribution & Usefulness',
        'self_agency_power',
        signs=['Leo', 'Virgo', 'Aquarius'],
        houses=[6, 10, 11],
        bodies=['Sun', 'Mercury', 'Ceres', 'Pallas'],
        nakshatras=['Pushya', 'Hasta', 'Uttara Phalguni', 'Uttara Ashadha'],
        gates=[8, 16, 27, 45, 58],
        channels=['8-1', '16-48', '27-50', '21-45'],
        crosses=['Contribution', 'Service', 'Industry', 'Caring'],
        bazisigns=['ox', 'dog'],
    ),
    'communication_exchange': _theme(
        'Communication & Exchange',
        'mind_language_truth',
        signs=['Gemini', 'Libra', 'Aquarius'],
        houses=[3, 7, 11],
        bodies=['Mercury'],
        elements=['Air'],
        nakshatras=['Mrigashira', 'Swati', 'Shravana', 'Revati'],
        gates=[12, 20, 23, 31, 45, 56, 62],
        channels=['43-23', '17-62', '11-56', '7-31'],
        crosses=['Interaction', 'Informing', 'Articulation', 'Listening'],
        centers=['Throat'],
        bazisigns=['monkey', 'rat'],
    ),
    'ideas_explanation': _theme(
        'Ideas & Explanation',
        'mind_language_truth',
        signs=['Gemini', 'Sagittarius', 'Aquarius'],
        houses=[3, 9],
        bodies=['Mercury', 'Jupiter', 'Pallas', 'Uranus'],
        elements=['Air'],
        nakshatras=['Mrigashira', 'Hasta', 'Shravana'],
        gates=[4, 11, 17, 23, 24, 43, 47, 62],
        channels=['63-4', '43-23', '17-62', '64-47'],
        crosses=['Ideas', 'Explanation', 'Formulization', 'Thinking'],
        bazisigns=['monkey', 'rooster'],
    ),
    'learning_education': _theme(
        'Learning & Education',
        'mind_language_truth',
        signs=['Gemini', 'Sagittarius', 'Virgo'],
        houses=[3, 9],
        bodies=['Mercury', 'Jupiter', 'Pallas'],
        nakshatras=['Mrigashira', 'Punarvasu', 'Shravana', 'Uttara Bhadrapada'],
        gates=[4, 9, 11, 16, 17, 48, 56, 62],
        channels=['63-4', '17-62', '16-48', '11-56'],
        crosses=['Education', 'Experimentation', 'Explanation'],
        bazisigns=['monkey', 'rooster'],
    ),
    'strategy_pattern_recognition': _theme(
        'Strategy & Pattern Recognition',
        'mind_language_truth',
        signs=['Virgo', 'Scorpio', 'Aquarius', 'Gemini'],
        houses=[3, 6, 8],
        bodies=['Pallas', 'Mercury', 'Pluto'],
        elements=['Air', 'Earth'],
        nakshatras=['Ashlesha', 'Hasta', 'Jyeshtha', 'Mula'],
        gates=[9, 17, 18, 44, 48, 57, 62, 63],
        channels=['17-62', '16-48', '18-58', '44-26', '57-20'],
        crosses=['Strategy', 'Planning', 'Alertness', 'Focus'],
        bazisigns=['snake', 'monkey', 'rat'],
    ),
    'judgment_correction': _theme(
        'Judgment & Correction',
        'mind_language_truth',
        signs=['Virgo', 'Libra', 'Capricorn'],
        houses=[6, 9],
        bodies=['Pallas', 'Saturn', 'Mercury'],
        elements=['Earth', 'Air'],
        nakshatras=['Krittika', 'Hasta', 'Jyeshtha'],
        gates=[17, 18, 48, 50, 58, 62, 63],
        channels=['17-62', '18-58', '16-48'],
        crosses=['Correction', 'Opinions', 'Demands', 'Prevention'],
        bazisigns=['rooster', 'snake'],
    ),
    'skill_refinement': _theme(
        'Skill & Refinement',
        'mind_language_truth',
        signs=['Virgo', 'Capricorn', 'Taurus'],
        houses=[2, 6, 10],
        bodies=['Pallas', 'Vesta', 'Saturn', 'Mercury'],
        elements=['Earth'],
        nakshatras=['Krittika', 'Hasta', 'Chitra', 'Shravana'],
        gates=[9, 16, 18, 48, 52, 58, 62],
        channels=['16-48', '18-58', '9-52'],
        crosses=['Refinement', 'Experimentation', 'Focus', 'Service'],
        bazisigns=['rooster', 'goat'],
    ),
    'doubt_verification': _theme(
        'Doubt & Verification',
        'mind_language_truth',
        signs=['Gemini', 'Virgo', 'Aquarius'],
        houses=[3, 6, 9],
        bodies=['Mercury', 'Saturn', 'Pallas'],
        nakshatras=['Mrigashira', 'Mula', 'Shatabhisha'],
        gates=[4, 17, 24, 47, 62, 63, 64],
        channels=['63-4', '17-62', '64-47'],
        crosses=['Doubts', 'Uncertainty', 'Obscuration', 'Denial'],
        bazisigns=['snake', 'rooster', 'monkey'],
    ),
    'memory_history': _theme(
        'Memory & History',
        'mind_language_truth',
        signs=['Cancer', 'Scorpio', 'Capricorn'],
        houses=[3, 4, 8],
        bodies=['Moon', 'Mercury', 'Pluto'],
        nakshatras=['Magha', 'Anuradha', 'Shravana'],
        gates=[13, 24, 33, 44, 47, 56, 64],
        channels=['13-33', '64-47', '11-56'],
        crosses=['Listening', 'Incarnation', 'the Four Ways'],
        bazisigns=['dog', 'ox'],
    ),
    'story_narrative': _theme(
        'Story & Narrative',
        'mind_language_truth',
        signs=['Gemini', 'Cancer', 'Sagittarius', 'Pisces'],
        houses=[3, 9, 12],
        bodies=['Mercury', 'Moon', 'Neptune', 'Jupiter'],
        nakshatras=['Mrigashira', 'Shravana', 'Revati'],
        gates=[11, 13, 33, 41, 47, 56, 64],
        channels=['11-56', '13-33', '64-47'],
        crosses=['Informing', 'Explanation', 'Listening', 'Stimulation'],
        bazisigns=['monkey', 'rat'],
    ),
    'mystery_inner_truth': _theme(
        'Mystery & Inner Truth',
        'mind_language_truth',
        signs=['Scorpio', 'Pisces'],
        houses=[8, 12],
        bodies=['Neptune', 'Pluto', 'Ketu'],
        nakshatras=['Ashlesha', 'Mula', 'Shatabhisha', 'Uttara Bhadrapada'],
        gates=[24, 43, 47, 48, 57, 61, 64],
        channels=['61-24', '43-23', '64-47', '57-20'],
        crosses=['Insight', 'Consciousness', 'Obscuration', 'Maya'],
        bazisigns=['snake'],
    ),
    'dogma_faith': _theme(
        'Dogma & Faith',
        'mind_language_truth',
        signs=['Sagittarius', 'Pisces'],
        houses=[9],
        bodies=['Jupiter', 'Saturn', 'Neptune'],
        elements=['Fire', 'Water'],
        nakshatras=['Pushya', 'Purva Ashadha', 'Uttara Ashadha', 'Purva Bhadrapada'],
        gates=[17, 25, 49, 50, 55, 61, 63],
        crosses=['Principles', 'Spirit', 'Laws', 'Consciousness'],
        bazisigns=['dog', 'ox'],
    ),
    'law_principles': _theme(
        'Law & Principles',
        'mind_language_truth',
        signs=['Sagittarius', 'Libra', 'Capricorn', 'Aquarius'],
        houses=[7, 9, 10],
        bodies=['Jupiter', 'Saturn', 'Juno', 'Pallas'],
        nakshatras=['Pushya', 'Uttara Phalguni', 'Uttara Ashadha'],
        gates=[10, 17, 21, 49, 50, 63],
        crosses=['Laws', 'Principles', 'Values', 'Rulership'],
        bazisigns=['dog', 'rooster'],
    ),
    'attraction_beauty': _theme(
        'Attraction & Beauty',
        'relationship_attachment_society',
        signs=['Taurus', 'Libra', 'Leo'],
        houses=[2, 5],
        bodies=['Venus'],
        elements=['Earth', 'Air'],
        nakshatras=['Rohini', 'Purva Phalguni', 'Chitra'],
        gates=[22, 46],
        channels=['12-22', '29-46'],
        crosses=['Grace', 'the Vessel of Love', 'Serendipity'],
        bazisigns=['goat', 'pig'],
    ),
    'pleasure_sensuality': _theme(
        'Pleasure & Sensuality',
        'relationship_attachment_society',
        signs=['Taurus', 'Leo', 'Pisces'],
        houses=[2, 5],
        bodies=['Venus', 'Moon', 'Jupiter'],
        nakshatras=['Rohini', 'Purva Phalguni'],
        gates=[22, 30, 46, 55],
        crosses=['Eden', 'the Vessel of Love', 'Spirit'],
        bazisigns=['pig', 'goat'],
    ),
    'desire_appetite': _theme(
        'Desire & Appetite',
        'relationship_attachment_society',
        signs=['Aries', 'Taurus', 'Scorpio', 'Pisces'],
        houses=[2, 5, 8],
        bodies=['Mars', 'Venus', 'Rahu', 'Jupiter'],
        nakshatras=['Bharani', 'Rohini', 'Mrigashira', 'Purva Phalguni'],
        gates=[19, 30, 41, 55, 59],
        channels=['41-30', '39-55', '59-6'],
        crosses=['Wishes', 'Spirit', 'Fantasy', 'Fates'],
        bazisigns=['tiger', 'pig'],
    ),
    'romance_courtship': _theme(
        'Romance & Courtship',
        'relationship_attachment_society',
        signs=['Leo', 'Libra', 'Taurus'],
        houses=[5],
        bodies=['Venus', 'Mars'],
        nakshatras=['Rohini', 'Purva Phalguni', 'Anuradha'],
        gates=[22, 30, 41, 59],
        channels=['12-22', '41-30', '59-6'],
        crosses=['the Vessel of Love', 'Spirit', 'Eden'],
        bazisigns=['goat', 'pig'],
    ),
    'sexuality_intimacy': _theme(
        'Sexuality & Intimacy',
        'relationship_attachment_society',
        signs=['Scorpio', 'Taurus', 'Aries'],
        houses=[5, 8],
        bodies=['Mars', 'Venus', 'Pluto', 'Mean Lilith', 'Osculating Lilith', 'Natural Lilith', 'Rahu'],
        nakshatras=['Bharani', 'Rohini', 'Ashlesha', 'Purva Phalguni'],
        gates=[6, 30, 37, 59],
        channels=['59-6', '37-40'],
        crosses=['Spirit', 'Duality', 'Conflict', 'the Sleeping Phoenix'],
        bazisigns=['tiger', 'pig', 'snake'],
    ),
    'partnership_contract': _theme(
        'Partnership & Contract',
        'relationship_attachment_society',
        signs=['Libra', 'Taurus', 'Capricorn'],
        houses=[7],
        bodies=['Venus', 'Juno', 'Saturn', 'Mercury'],
        elements=['Air', 'Earth'],
        nakshatras=['Uttara Phalguni', 'Anuradha'],
        gates=[6, 21, 26, 37, 40, 49, 50],
        channels=['37-40', '19-49', '21-45', '44-26'],
        crosses=['Bargains', 'Planning', 'Duality', 'Interaction'],
        bazisigns=['dog', 'ox'],
    ),
    'loyalty_reciprocity': _theme(
        'Loyalty & Reciprocity',
        'relationship_attachment_society',
        signs=['Libra', 'Cancer', 'Taurus'],
        houses=[4, 7, 11],
        bodies=['Juno', 'Moon', 'Saturn', 'Ceres'],
        nakshatras=['Pushya', 'Uttara Phalguni', 'Anuradha'],
        gates=[19, 37, 40, 49, 50],
        channels=['37-40', '19-49'],
        crosses=['Bargains', 'Planning', 'Caring', 'Alignment'],
        bazisigns=['dog', 'ox'],
    ),
    'care_nourishment': _theme(
        'Care & Nourishment',
        'relationship_attachment_society',
        signs=['Cancer', 'Taurus', 'Virgo'],
        houses=[2, 4, 6],
        bodies=['Moon', 'Ceres', 'Venus'],
        elements=['Water', 'Earth'],
        nakshatras=['Rohini', 'Punarvasu', 'Pushya', 'Revati'],
        gates=[19, 27, 37, 40, 50],
        channels=['27-50', '37-40', '19-49'],
        crosses=['Caring', 'Healing', 'Service', 'Conservation'],
        bazisigns=['rabbit', 'pig', 'ox'],
    ),
    'family_kinship': _theme(
        'Family & Kinship',
        'relationship_attachment_society',
        signs=['Cancer', 'Taurus', 'Pisces'],
        houses=[4, 5, 7],
        bodies=['Moon', 'Ceres', 'Juno'],
        nakshatras=['Rohini', 'Punarvasu', 'Pushya', 'Magha'],
        gates=[19, 27, 37, 40, 50, 59],
        channels=['27-50', '37-40', '59-6'],
        crosses=['Planning', 'Caring', 'the Four Ways', 'Migration'],
        bazisigns=['rabbit', 'dog', 'ox'],
    ),
    'belonging_community': _theme(
        'Belonging & Community',
        'relationship_attachment_society',
        signs=['Cancer', 'Aquarius', 'Pisces'],
        houses=[4, 11],
        bodies=['Moon', 'Jupiter', 'Juno'],
        nakshatras=['Pushya', 'Anuradha', 'Dhanishta'],
        gates=[15, 19, 37, 40, 45, 49, 50],
        channels=['37-40', '19-49', '21-45'],
        crosses=['Planning', 'Interaction', 'Contribution', 'Duality'],
        bazisigns=['dog', 'rabbit'],
    ),
    'friendship_networks': _theme(
        'Friendship & Networks',
        'relationship_attachment_society',
        signs=['Aquarius', 'Gemini', 'Libra'],
        houses=[3, 11],
        bodies=['Mercury', 'Venus', 'Uranus', 'Jupiter'],
        elements=['Air'],
        nakshatras=['Swati', 'Anuradha', 'Dhanishta'],
        gates=[8, 13, 19, 31, 37, 45],
        channels=['8-1', '13-33', '7-31', '37-40'],
        crosses=['Interaction', 'Planning', 'Influence', 'Informing'],
        bazisigns=['dog', 'monkey'],
    ),
    'rivalry_opposition': _theme(
        'Rivalry & Opposition',
        'relationship_attachment_society',
        signs=['Aries', 'Libra', 'Scorpio'],
        houses=[7, 10],
        bodies=['Mars', 'Pluto'],
        nakshatras=['Bharani', 'Krittika', 'Vishakha', 'Jyeshtha'],
        gates=[6, 17, 18, 28, 38, 39, 51],
        channels=['28-38', '25-51'],
        crosses=['Opposition', 'Conflict', 'Confrontation', 'Tension'],
        bazisigns=['tiger', 'rooster'],
    ),
    'rejection_separation': _theme(
        'Rejection & Separation',
        'relationship_attachment_society',
        signs=['Aquarius', 'Scorpio', 'Pisces'],
        houses=[7, 11, 12],
        bodies=['Mean Lilith', 'Osculating Lilith', 'Natural Lilith', 'Ketu', 'Saturn', 'Uranus'],
        nakshatras=['Bharani', 'Ardra', 'Mula', 'Shatabhisha'],
        gates=[12, 33, 38, 40, 49],
        channels=['13-33', '28-38', '19-49'],
        crosses=['Separation', 'Defiance', 'Denial', 'Migration'],
        bazisigns=['horse', 'tiger'],
    ),
    'money_resources': _theme(
        'Money & Resources',
        'material_life_work_survival',
        signs=['Taurus', 'Capricorn', 'Scorpio'],
        houses=[2, 8, 10],
        bodies=['Venus', 'Jupiter', 'Saturn', 'Earth'],
        elements=['Earth'],
        nakshatras=['Rohini', 'Pushya', 'Uttara Phalguni', 'Dhanishta'],
        gates=[14, 19, 21, 32, 45, 50, 54],
        channels=['21-45', '32-54', '19-49'],
        crosses=['Possession', 'Rulership', 'Bargains', 'Planning', 'Empowering'],
        bazisigns=['rat', 'ox', 'pig'],
    ),
    'security_continuity': _theme(
        'Security & Continuity',
        'material_life_work_survival',
        signs=['Taurus', 'Cancer', 'Capricorn'],
        houses=[2, 4],
        bodies=['Moon', 'Saturn', 'Earth', 'Ceres'],
        elements=['Earth', 'Water'],
        modes=['fixed'],
        nakshatras=['Rohini', 'Punarvasu', 'Pushya', 'Uttara Bhadrapada'],
        gates=[5, 19, 27, 32, 37, 42, 50, 60],
        channels=['15-5', '27-50', '37-40', '42-53', '3-60'],
        crosses=['Conservation', 'Planning', 'Limitation', 'the Four Ways'],
        bazisigns=['ox', 'rabbit', 'dog'],
    ),
    'home_roots': _theme(
        'Home & Roots',
        'material_life_work_survival',
        signs=['Cancer', 'Taurus', 'Capricorn'],
        houses=[4],
        bodies=['Moon', 'Ceres', 'Saturn'],
        nakshatras=['Rohini', 'Punarvasu', 'Pushya', 'Magha'],
        gates=[13, 27, 32, 33, 37, 50],
        channels=['13-33', '27-50', '37-40'],
        crosses=['the Four Ways', 'Conservation', 'Planning', 'Retreat'],
        bazisigns=['rabbit', 'ox'],
    ),
    'work_service': _theme(
        'Work & Service',
        'material_life_work_survival',
        signs=['Virgo', 'Capricorn'],
        houses=[6, 10],
        bodies=['Saturn', 'Mars', 'Ceres', 'Vesta'],
        elements=['Earth'],
        nakshatras=['Pushya', 'Hasta', 'Uttara Phalguni', 'Uttara Ashadha'],
        gates=[9, 16, 18, 27, 40, 42, 52, 58],
        channels=['16-48', '18-58', '9-52', '27-50'],
        crosses=['Service', 'Industry', 'Contribution', 'Endeavour'],
        bazisigns=['ox', 'dog', 'rooster'],
    ),
    'duty_burden': _theme(
        'Duty & Burden',
        'material_life_work_survival',
        signs=['Capricorn', 'Virgo', 'Cancer'],
        houses=[6, 10],
        bodies=['Saturn', 'Earth', 'Vesta'],
        nakshatras=['Bharani', 'Pushya', 'Jyeshtha', 'Uttara Ashadha'],
        gates=[21, 27, 32, 40, 50, 52, 60],
        crosses=['Service', 'Demands', 'Planning', 'Conservation'],
        bazisigns=['ox', 'dog'],
    ),
    'health_maintenance': _theme(
        'Health & Maintenance',
        'material_life_work_survival',
        signs=['Virgo', 'Cancer', 'Taurus'],
        houses=[1, 6],
        bodies=['Moon', 'Chiron', 'Ceres', 'Saturn'],
        nakshatras=['Ashwini', 'Krittika', 'Pushya', 'Shatabhisha'],
        gates=[18, 27, 46, 48, 50, 57, 58],
        channels=['18-58', '27-50', '29-46', '16-48', '57-20'],
        crosses=['Healing', 'Service', 'Prevention', 'Correction'],
        bazisigns=['rabbit', 'rooster'],
    ),
    'body_vitality': _theme(
        'Body & Vitality',
        'material_life_work_survival',
        signs=['Aries', 'Leo', 'Taurus'],
        houses=[1, 6],
        bodies=['Sun', 'Moon', 'Mars', 'Earth'],
        elements=['Fire', 'Earth'],
        nakshatras=['Ashwini', 'Rohini', 'Purva Phalguni', 'Dhanishta'],
        gates=[20, 34, 46, 57, 58],
        channels=['34-20', '34-57', '29-46', '57-20'],
        crosses=['Vitality', 'Healing', 'the Vessel of Love', 'the Sleeping Phoenix'],
        centers=['Sacral', 'Spleen', 'G'],
        bazisigns=['dragon', 'tiger'],
    ),
    'rest_recovery': _theme(
        'Rest & Recovery',
        'material_life_work_survival',
        signs=['Cancer', 'Taurus', 'Pisces'],
        houses=[4, 6, 12],
        bodies=['Moon', 'Ceres', 'Chiron', 'Vesta', 'Ketu'],
        nakshatras=['Punarvasu', 'Pushya', 'Uttara Bhadrapada', 'Revati'],
        gates=[27, 33, 40, 46, 52, 58],
        channels=['27-50', '13-33', '29-46', '9-52'],
        crosses=['Healing', 'Retreat', 'Stillness', 'Conservation'],
        bazisigns=['rabbit', 'pig'],
    ),
    'time_endurance': _theme(
        'Time & Endurance',
        'material_life_work_survival',
        signs=['Capricorn', 'Taurus'],
        houses=[2, 6, 10],
        bodies=['Saturn', 'Moon'],
        elements=['Earth'],
        modes=['fixed'],
        nakshatras=['Pushya', 'Anuradha', 'Uttara Ashadha', 'Uttara Bhadrapada'],
        gates=[5, 29, 32, 42, 52, 53, 60],
        channels=['15-5', '42-53', '3-60'],
        crosses=['Cycles', 'Completion', 'Limitation', 'Conservation'],
        bazisigns=['ox', 'dog'],
    ),
    'institutions_orthodoxy': _theme(
        'Institutions & Orthodoxy',
        'material_life_work_survival',
        signs=['Capricorn', 'Sagittarius'],
        houses=[6, 9, 10],
        bodies=['Saturn', 'Jupiter'],
        nakshatras=['Pushya', 'Magha', 'Uttara Ashadha', 'Shravana'],
        gates=[17, 21, 31, 45, 49, 50, 60],
        crosses=['Laws', 'Rulership', 'Dominion', 'Planning'],
        bazisigns=['ox', 'dog'],
    ),
    'status_reputation': _theme(
        'Status & Reputation',
        'material_life_work_survival',
        signs=['Leo', 'Capricorn'],
        houses=[1, 5, 10],
        bodies=['Sun', 'Saturn', 'Jupiter', 'MC'],
        nakshatras=['Magha', 'Uttara Phalguni', 'Dhanishta'],
        gates=[7, 21, 26, 31, 45, 54],
        channels=['7-31', '21-45', '32-54', '44-26'],
        crosses=['Rulership', 'Influence', 'the Alpha', 'Masks'],
        bazisigns=['dragon', 'rooster'],
    ),
    'conservation_preservation': _theme(
        'Conservation & Preservation',
        'material_life_work_survival',
        signs=['Taurus', 'Cancer', 'Capricorn'],
        houses=[2, 4, 6],
        bodies=['Ceres', 'Saturn', 'Earth', 'Moon'],
        elements=['Earth', 'Water'],
        modes=['fixed'],
        nakshatras=['Pushya', 'Uttara Phalguni', 'Uttara Ashadha', 'Uttara Bhadrapada'],
        gates=[27, 32, 42, 50, 58, 60],
        channels=['27-50', '42-53', '3-60'],
        crosses=['Conservation', 'Planning', 'Caring', 'Limitation'],
        bazisigns=['ox', 'rabbit', 'dog'],
    ),
    'secrets_concealment': _theme(
        'Secrets & Concealment',
        'shadow_crisis_transformation',
        signs=['Scorpio', 'Cancer', 'Pisces'],
        houses=[4, 8, 12],
        bodies=['Pluto', 'Moon', 'Mean Lilith', 'Osculating Lilith', 'Natural Lilith', 'Neptune'],
        nakshatras=['Ashlesha', 'Jyeshtha', 'Mula', 'Shatabhisha'],
        gates=[12, 13, 33, 44, 47],
        channels=['13-33'],
        crosses=['Masks', 'Retreat', 'Obscuration', 'Oppression'],
        bazisigns=['snake', 'rat'],
    ),
    'taboo_transgression': _theme(
        'Taboo & Transgression',
        'shadow_crisis_transformation',
        signs=['Scorpio', 'Aquarius', 'Aries'],
        houses=[8, 12],
        bodies=['Mean Lilith', 'Osculating Lilith', 'Natural Lilith', 'Pluto', 'Rahu', 'Uranus'],
        nakshatras=['Bharani', 'Ashlesha', 'Mula', 'Purva Bhadrapada'],
        gates=[28, 38, 39, 49, 51],
        channels=['28-38', '19-49', '25-51'],
        crosses=['Defiance', 'Revolution', 'Provocation', 'Individualism'],
        bazisigns=['tiger', 'snake'],
    ),
    'obsession_compulsion': _theme(
        'Obsession & Compulsion',
        'shadow_crisis_transformation',
        signs=['Scorpio', 'Pisces', 'Capricorn'],
        houses=[8, 12],
        bodies=['Pluto', 'Rahu', 'Mars'],
        nakshatras=['Bharani', 'Vishakha', 'Mula', 'Purva Bhadrapada'],
        gates=[28, 29, 30, 38, 39, 41, 55],
        channels=['28-38', '39-55', '41-30'],
        crosses=['Fates', 'Commitment', 'Tension', 'Spirit'],
        bazisigns=['tiger', 'snake'],
    ),
    'fear_survival': _theme(
        'Fear & Survival',
        'shadow_crisis_transformation',
        signs=['Scorpio', 'Cancer', 'Capricorn'],
        houses=[1, 2, 8, 12],
        bodies=['Saturn', 'Moon', 'Pluto', 'Mars'],
        nakshatras=['Bharani', 'Ardra', 'Jyeshtha', 'Mula'],
        gates=[19, 28, 32, 44, 50, 57, 60],
        channels=['28-38', '44-26', '27-50', '3-60'],
        crosses=['Prevention', 'Alertness', 'Limitation', 'Need'],
        bazisigns=['rabbit', 'rat', 'snake'],
    ),
    'conflict_friction': _theme(
        'Conflict & Friction',
        'shadow_crisis_transformation',
        signs=['Aries', 'Scorpio', 'Libra'],
        houses=[7, 8],
        bodies=['Mars', 'Pluto'],
        nakshatras=['Ardra', 'Vishakha', 'Jyeshtha'],
        gates=[6, 18, 28, 38, 39, 51],
        channels=['28-38', '25-51'],
        crosses=['Conflict', 'Tension', 'Opposition', 'Confrontation'],
        bazisigns=['tiger', 'rooster'],
    ),
    'crisis_upheaval': _theme(
        'Crisis & Upheaval',
        'shadow_crisis_transformation',
        signs=['Scorpio', 'Aries', 'Aquarius', 'Pisces'],
        houses=[8, 12],
        bodies=['Pluto', 'Mars', 'Uranus', 'Chiron'],
        nakshatras=['Ardra', 'Mula', 'Purva Bhadrapada'],
        gates=[3, 36, 38, 39, 49, 51, 60],
        channels=['3-60', '28-38', '19-49', '25-51', '35-36'],
        crosses=['Crisis', 'Upheaval', 'Shock', 'Tension'],
        bazisigns=['dragon', 'tiger'],
    ),
    'oppression_resistance': _theme(
        'Oppression & Resistance',
        'shadow_crisis_transformation',
        signs=['Capricorn', 'Scorpio', 'Aquarius'],
        houses=[8, 10, 12],
        bodies=['Saturn', 'Pluto', 'Uranus', 'Mean Lilith', 'Osculating Lilith', 'Natural Lilith'],
        nakshatras=['Bharani', 'Ardra', 'Mula', 'Purva Bhadrapada'],
        gates=[21, 38, 39, 47, 49, 51, 60],
        channels=['28-38', '19-49', '25-51', '3-60'],
        crosses=['Oppression', 'Defiance', 'Opposition', 'Revolution'],
        bazisigns=['tiger', 'horse'],
    ),
    'death_loss': _theme(
        'Death & Loss',
        'shadow_crisis_transformation',
        signs=['Scorpio', 'Capricorn', 'Pisces'],
        houses=[8, 12],
        bodies=['Pluto', 'Saturn', 'Ketu', 'Ceres'],
        nakshatras=['Bharani', 'Ardra', 'Mula', 'Purva Bhadrapada'],
        gates=[28, 32, 40, 42, 50, 60],
        crosses=['Separation', 'Limitation', 'Completion', 'Maya'],
        bazisigns=['snake', 'ox'],
    ),
    'transformation_regeneration': _theme(
        'Transformation & Regeneration',
        'shadow_crisis_transformation',
        signs=['Scorpio', 'Aquarius', 'Pisces'],
        houses=[8, 12],
        bodies=['Pluto', 'Uranus', 'Chiron', 'Ketu'],
        nakshatras=['Bharani', 'Ardra', 'Punarvasu', 'Mula', 'Shatabhisha'],
        gates=[3, 28, 32, 35, 42, 53, 54, 58, 60],
        channels=['3-60', '28-38', '35-36', '42-53', '32-54'],
        crosses=['Mutation', 'Healing', 'Cycles', 'the Sleeping Phoenix'],
        bazisigns=['dragon', 'snake'],
    ),
    'purification_eradication': _theme(
        'Purification & Eradication',
        'shadow_crisis_transformation',
        signs=['Scorpio', 'Virgo', 'Capricorn'],
        houses=[6, 8, 12],
        bodies=['Pluto', 'Vesta', 'Ketu', 'Saturn'],
        nakshatras=['Krittika', 'Mula', 'Shatabhisha'],
        gates=[18, 27, 50, 52, 58, 60],
        channels=['18-58', '27-50', '9-52', '3-60'],
        crosses=['Correction', 'Refinement', 'Prevention', 'Revolution'],
        bazisigns=['rooster', 'snake'],
    ),
    'healing_adaptation': _theme(
        'Healing & Adaptation',
        'shadow_crisis_transformation',
        signs=['Virgo', 'Cancer', 'Pisces'],
        houses=[6, 8, 12],
        bodies=['Chiron', 'Ceres', 'Moon'],
        modes=['mutable'],
        nakshatras=['Ashwini', 'Punarvasu', 'Shatabhisha', 'Revati'],
        gates=[18, 25, 27, 46, 48, 57, 58],
        channels=['18-58', '27-50', '29-46', '16-48', '57-20'],
        crosses=['Healing', 'Refinement', 'Service', 'Alignment'],
        bazisigns=['rabbit', 'dragon'],
    ),
    'change_mutation': _theme(
        'Change & Mutation',
        'change_boundaries_disappearance',
        signs=['Aquarius', 'Scorpio', 'Aries'],
        houses=[8, 11],
        bodies=['Uranus', 'Pluto', 'Rahu'],
        modes=['mutable'],
        nakshatras=['Ashwini', 'Ardra', 'Mula', 'Shatabhisha'],
        gates=[3, 35, 42, 49, 53, 60],
        channels=['3-60', '35-36', '42-53', '19-49'],
        crosses=['Mutation', 'Revolution', 'Cycles', 'the Unexpected'],
        bazisigns=['dragon', 'monkey'],
    ),
    'innovation_disruption': _theme(
        'Innovation & Disruption',
        'change_boundaries_disappearance',
        signs=['Aquarius', 'Aries', 'Gemini'],
        houses=[3, 11],
        bodies=['Uranus', 'Mercury', 'Pallas'],
        nakshatras=['Ashwini', 'Ardra', 'Swati', 'Shatabhisha'],
        gates=[3, 43, 49, 51, 60],
        channels=['3-60', '43-23', '19-49', '25-51'],
        crosses=['Mutation', 'Shock', 'Revolution', 'Experimentation'],
        bazisigns=['monkey', 'horse'],
    ),
    'chaos_ordering': _theme(
        'Chaos & Ordering',
        'change_boundaries_disappearance',
        signs=['Aquarius', 'Virgo', 'Capricorn'],
        houses=[3, 6, 10],
        bodies=['Uranus', 'Saturn', 'Mercury', 'Pallas'],
        nakshatras=['Ardra', 'Krittika', 'Hasta', 'Mula'],
        gates=[3, 4, 9, 18, 47, 60, 64],
        channels=['3-60', '63-4', '9-52', '18-58', '64-47'],
        crosses=['Mutation', 'Planning', 'Correction', 'Formulization'],
        bazisigns=['rooster', 'monkey'],
    ),
    'cycles_completion': _theme(
        'Cycles & Completion',
        'change_boundaries_disappearance',
        signs=['Capricorn', 'Cancer', 'Pisces'],
        houses=[4, 6, 8, 10],
        bodies=['Saturn', 'Moon', 'Jupiter', 'Ketu'],
        nakshatras=['Punarvasu', 'Uttara Ashadha', 'Uttara Bhadrapada', 'Revati'],
        gates=[5, 32, 41, 42, 53, 60],
        channels=['15-5', '42-53', '3-60'],
        crosses=['Cycles', 'Completion', 'Beginnings', 'Incarnation'],
        bazisigns=['ox', 'pig'],
    ),
    'timing_rhythm': _theme(
        'Timing & Rhythm',
        'change_boundaries_disappearance',
        signs=['Cancer', 'Taurus', 'Capricorn'],
        houses=[4, 6],
        bodies=['Moon', 'Saturn', 'Part of Fortune'],
        modes=['fixed'],
        nakshatras=['Pushya', 'Hasta', 'Dhanishta', 'Revati'],
        gates=[5, 15, 32, 46, 52, 53],
        channels=['15-5', '9-52', '29-46'],
        crosses=['Habits', 'Cycles', 'Stillness', 'the Now'],
        bazisigns=['rooster', 'ox'],
    ),
    'thresholds_transition': _theme(
        'Thresholds & Transition',
        'change_boundaries_disappearance',
        signs=['Aries', 'Scorpio', 'Pisces'],
        houses=[1, 8, 12],
        bodies=['Pluto', 'Uranus', 'Ketu', 'Rahu'],
        modes=['mutable'],
        nakshatras=['Ashwini', 'Bharani', 'Mula', 'Revati'],
        gates=[3, 35, 36, 42, 46, 51, 53, 60],
        channels=['3-60', '35-36', '42-53', '29-46', '25-51'],
        crosses=['Beginnings', 'Completion', 'Migration', 'the Unexpected'],
        bazisigns=['horse', 'rat'],
    ),
    'travel_migration': _theme(
        'Travel & Migration',
        'change_boundaries_disappearance',
        signs=['Sagittarius', 'Gemini', 'Aquarius'],
        houses=[3, 9, 12],
        bodies=['Jupiter', 'Uranus', 'Mars', 'Ketu'],
        modes=['mutable'],
        nakshatras=['Mrigashira', 'Swati', 'Shravana', 'Revati'],
        gates=[2, 35, 41, 46, 53, 56],
        channels=['35-36', '41-30', '29-46', '11-56'],
        crosses=['Migration', 'Experience', 'the Plane'],
        bazisigns=['horse', 'rat'],
    ),
    'chance_serendipity': _theme(
        'Chance & Serendipity',
        'change_boundaries_disappearance',
        signs=['Sagittarius', 'Aquarius'],
        houses=[5, 9, 11],
        bodies=['Part of Fortune', 'Jupiter', 'Uranus'],
        nakshatras=['Ashwini', 'Punarvasu', 'Revati'],
        gates=[14, 35, 41, 46, 53],
        channels=['2-14', '35-36', '41-30', '29-46'],
        crosses=['Serendipity', 'the Unexpected', 'Wishes'],
        bazisigns=['rat', 'monkey', 'dragon'],
    ),
    'confinement_escape': _theme(
        'Confinement & Escape',
        'change_boundaries_disappearance',
        signs=['Pisces', 'Capricorn'],
        houses=[12],
        bodies=['Neptune', 'Saturn', 'Ketu', 'Mean Lilith', 'Osculating Lilith', 'Natural Lilith'],
        nakshatras=['Bharani', 'Shatabhisha', 'Uttara Bhadrapada', 'Revati'],
        gates=[33, 40, 52, 60],
        channels=['13-33', '9-52', '3-60'],
        crosses=['Retreat', 'Limitation', 'Separation', 'Migration'],
        bazisigns=['horse', 'rat'],
    ),
    'retreat_seclusion': _theme(
        'Retreat & Seclusion',
        'change_boundaries_disappearance',
        signs=['Pisces', 'Cancer', 'Virgo'],
        houses=[4, 12],
        bodies=['Vesta', 'Ketu', 'Neptune', 'Moon'],
        nakshatras=['Ashlesha', 'Shatabhisha', 'Uttara Bhadrapada'],
        gates=[12, 33, 40, 52],
        channels=['13-33', '9-52'],
        crosses=['Retreat', 'Stillness', 'Separation'],
        bazisigns=['snake', 'rabbit'],
    ),
    'dissolution_surrender': _theme(
        'Dissolution & Surrender',
        'change_boundaries_disappearance',
        signs=['Pisces', 'Scorpio'],
        houses=[8, 12],
        bodies=['Neptune', 'Ketu', 'Pluto'],
        nakshatras=['Bharani', 'Mula', 'Purva Bhadrapada', 'Uttara Bhadrapada'],
        gates=[25, 40, 55, 59, 60],
        channels=['39-55', '59-6', '3-60'],
        crosses=['Spirit', 'Separation', 'Limitation'],
        bazisigns=['pig', 'snake'],
    ),
    'exile_alienation': _theme(
        'Exile & Alienation',
        'change_boundaries_disappearance',
        signs=['Aquarius', 'Scorpio', 'Pisces'],
        houses=[11, 12],
        bodies=['Mean Lilith', 'Osculating Lilith', 'Natural Lilith', 'Ketu', 'Uranus', 'Neptune'],
        nakshatras=['Ardra', 'Swati', 'Mula', 'Shatabhisha'],
        gates=[12, 33, 38, 40, 49],
        channels=['13-33', '28-38', '19-49'],
        crosses=['Separation', 'Migration', 'Retreat', 'Individualism'],
        bazisigns=['horse'],
    ),
    'boundaries_permeability': _theme(
        'Boundaries & Permeability',
        'change_boundaries_disappearance',
        signs=['Cancer', 'Scorpio', 'Pisces', 'Capricorn'],
        houses=[4, 7, 8, 12],
        bodies=['Saturn', 'Neptune', 'Pluto', 'Juno'],
        nakshatras=['Bharani', 'Ashlesha', 'Jyeshtha', 'Shatabhisha'],
        gates=[6, 19, 21, 37, 40, 49, 50, 59, 60],
        channels=['37-40', '19-49', '59-6', '21-45', '3-60'],
        crosses=['Limitation', 'Conflict', 'Separation', 'Bargains'],
        bazisigns=['dog', 'rabbit', 'snake'],
    ),
    'dreams_illusion': _theme(
        'Dreams & Illusion',
        'imagination_expanded_perspective',
        signs=['Pisces', 'Cancer'],
        houses=[5, 12],
        bodies=['Neptune', 'Moon', 'Rahu'],
        elements=['Water'],
        nakshatras=['Rohini', 'Ardra', 'Purva Bhadrapada', 'Uttara Bhadrapada'],
        gates=[11, 41, 47, 55, 64],
        channels=['11-56', '64-47', '39-55', '41-30'],
        crosses=['Fantasy', 'Maya', 'Obscuration', 'Spirit'],
        bazisigns=['pig', 'dragon'],
    ),
    'imagination_fantasy': _theme(
        'Imagination & Fantasy',
        'imagination_expanded_perspective',
        signs=['Pisces', 'Sagittarius', 'Cancer'],
        houses=[5, 9, 12],
        bodies=['Neptune', 'Moon', 'Jupiter'],
        nakshatras=['Rohini', 'Mrigashira', 'Purva Phalguni', 'Purva Bhadrapada'],
        gates=[11, 30, 41, 47, 56, 64],
        channels=['11-56', '64-47', '41-30'],
        crosses=['Fantasy', 'Ideas', 'Wishes', 'Stimulation'],
        bazisigns=['goat', 'monkey'],
    ),
    'stimulation_experience': _theme(
        'Stimulation & Experience',
        'imagination_expanded_perspective',
        signs=['Sagittarius', 'Gemini', 'Pisces'],
        houses=[5, 9],
        bodies=['Jupiter', 'Mars', 'Uranus', 'Neptune'],
        modes=['mutable'],
        nakshatras=['Ashwini', 'Mrigashira', 'Ardra', 'Swati'],
        gates=[30, 35, 36, 41, 56],
        channels=['35-36', '41-30', '11-56'],
        crosses=['Stimulation', 'Experience', 'Contagion', 'the Unexpected'],
        bazisigns=['monkey', 'horse', 'dragon'],
    ),
    'extremes_intensity': _theme(
        'Extremes & Intensity',
        'imagination_expanded_perspective',
        signs=['Scorpio', 'Aries', 'Sagittarius'],
        houses=[5, 8],
        bodies=['Pluto', 'Mars', 'Rahu', 'Jupiter'],
        nakshatras=['Bharani', 'Ardra', 'Vishakha', 'Purva Bhadrapada'],
        gates=[15, 28, 30, 34, 36, 38],
        channels=['28-38', '34-20', '35-36'],
        crosses=['Extremes', 'Tension', 'Risks', 'Crisis'],
        bazisigns=['tiger', 'dragon'],
    ),
    'joy_abundance': _theme(
        'Joy & Abundance',
        'imagination_expanded_perspective',
        signs=['Sagittarius', 'Taurus', 'Leo', 'Pisces'],
        houses=[2, 5, 9, 11],
        bodies=['Jupiter', 'Venus', 'Part of Fortune'],
        nakshatras=['Rohini', 'Purva Phalguni', 'Dhanishta', 'Revati'],
        gates=[14, 22, 42, 55, 58],
        channels=['2-14', '12-22', '42-53', '39-55', '18-58'],
        crosses=['Vitality', 'the Vessel of Love', 'Serendipity', 'Wishes'],
        bazisigns=['pig', 'dragon'],
    ),
    'longing_lack': _theme(
        'Longing & Lack',
        'imagination_expanded_perspective',
        signs=['Pisces', 'Cancer', 'Scorpio'],
        houses=[2, 4, 8, 12],
        bodies=['Neptune', 'Moon', 'Rahu', 'Ketu', 'Ceres'],
        nakshatras=['Mrigashira', 'Ardra', 'Vishakha', 'Purva Bhadrapada'],
        gates=[19, 30, 41, 55],
        channels=['19-49', '41-30', '39-55'],
        crosses=['Wishes', 'Need', 'Uncertainty', 'Spirit'],
        bazisigns=['rat', 'pig'],
    ),
    'hope_possibility': _theme(
        'Hope & Possibility',
        'imagination_expanded_perspective',
        signs=['Sagittarius', 'Pisces', 'Aquarius'],
        houses=[9, 11],
        bodies=['Jupiter', 'Neptune', 'Part of Fortune'],
        nakshatras=['Punarvasu', 'Purva Ashadha', 'Revati'],
        gates=[11, 30, 41, 42, 55],
        channels=['11-56', '41-30', '42-53', '39-55'],
        crosses=['Wishes', 'Fantasy', 'Serendipity', 'Beginnings'],
        bazisigns=['dragon', 'rat'],
    ),
    'grace_receptivity': _theme(
        'Grace & Receptivity',
        'imagination_expanded_perspective',
        signs=['Libra', 'Pisces', 'Taurus'],
        houses=[5, 7],
        bodies=['Venus', 'Moon', 'Neptune'],
        nakshatras=['Rohini', 'Purva Phalguni', 'Revati'],
        gates=[2, 15, 22, 25, 46],
        channels=['12-22', '29-46'],
        crosses=['Grace', 'Innocence', 'the Vessel of Love'],
        bazisigns=['goat', 'rabbit', 'pig'],
    ),
    'present_moment_awareness': _theme(
        'Present-Moment Awareness',
        'imagination_expanded_perspective',
        signs=['Aries', 'Gemini', 'Libra'],
        houses=[1, 3],
        bodies=['Mars', 'Moon', 'Uranus'],
        nakshatras=['Ashwini', 'Hasta', 'Swati'],
        gates=[20, 34, 46, 57],
        channels=['34-20', '57-20', '34-57', '29-46'],
        crosses=['the Now', 'Intuition', 'Penetration'],
        bazisigns=['tiger', 'monkey'],
    ),
    'devotion_dedication': _theme(
        'Devotion & Dedication',
        'imagination_expanded_perspective',
        signs=['Virgo', 'Capricorn', 'Sagittarius'],
        houses=[6, 7, 9],
        bodies=['Vesta', 'Saturn', 'Jupiter', 'Juno'],
        nakshatras=['Pushya', 'Anuradha', 'Uttara Ashadha'],
        gates=[5, 16, 29, 40, 52],
        channels=['15-5', '16-48', '9-52'],
        crosses=['Dedication', 'Commitment', 'Service'],
        bazisigns=['dog', 'ox'],
    ),
    'provocation_shock': _theme(
        'Provocation & Shock',
        'imagination_expanded_perspective',
        signs=['Aries', 'Aquarius', 'Scorpio'],
        houses=[1, 7, 8, 11],
        bodies=['Uranus', 'Mars', 'Mean Lilith', 'Osculating Lilith', 'Natural Lilith', 'Pluto'],
        nakshatras=['Krittika', 'Ardra', 'Mula'],
        gates=[38, 39, 49, 51, 57],
        channels=['28-38', '19-49', '25-51', '57-20'],
        crosses=['Provocation', 'Shock', 'the Clarion', 'Tension'],
        bazisigns=['tiger', 'monkey'],
    ),
    'masks_presentation': _theme(
        'Masks & Presentation',
        'imagination_expanded_perspective',
        signs=['Leo', 'Libra', 'Gemini'],
        houses=[1, 5, 10],
        bodies=['Sun', 'Venus', 'Mercury', 'AS'],
        nakshatras=['Magha', 'Purva Phalguni', 'Chitra', 'Swati'],
        gates=[7, 10, 12, 13, 22, 23],
        channels=['10-20', '12-22', '43-23', '13-33'],
        crosses=['Masks', 'Self-Expression', 'Grace', 'Rulership'],
        bazisigns=['rooster', 'goat', 'monkey'],
    ),
}


THEME_ENTRY_KEYS = frozenset(
    {
        "label",
        "family",
        *WEIGHTED_THEME_PROPERTIES,
        *THEME_METADATA_LIST_PROPERTIES,
        "notes",
        "default_weight",
        "weight_overrides",
    }
)


def theme_item_weight(theme_key: str, property_name: str, item: Any) -> float:
    """Return the item's thematic membership weight.

    Listed items default to 1.0 (or the theme's future custom default).
    Unlisted items return 0.0. ``weight_overrides`` is intentionally sparse.
    """

    if property_name not in WEIGHTED_THEME_PROPERTIES:
        raise KeyError(f"{property_name!r} is not a weighted theme property")

    theme = THEMES[theme_key]
    if item not in theme[property_name]:
        return 0.0

    return float(
        theme["weight_overrides"]
        .get(property_name, {})
        .get(item, theme["default_weight"])
    )


def themes_in_family(family_key: str) -> dict[str, dict[str, Any]]:
    """Return theme entries assigned to one organizational family."""

    if family_key not in THEME_FAMILIES:
        raise KeyError(f"Unknown theme family: {family_key!r}")
    return {
        theme_key: theme
        for theme_key, theme in THEMES.items()
        if theme["family"] == family_key
    }


def validate_theme_reference() -> None:
    """Raise ValueError if the reference schema or weight scaffold is invalid."""

    for theme_key, theme in THEMES.items():
        keys = frozenset(theme)
        if keys != THEME_ENTRY_KEYS:
            missing = sorted(THEME_ENTRY_KEYS - keys)
            extra = sorted(keys - THEME_ENTRY_KEYS)
            raise ValueError(
                f"{theme_key}: schema mismatch; missing={missing}, extra={extra}"
            )

        if theme["family"] not in THEME_FAMILIES:
            raise ValueError(
                f"{theme_key}: unknown family {theme['family']!r}"
            )

        if not isinstance(theme["label"], str) or not theme["label"].strip():
            raise ValueError(f"{theme_key}: label must be non-empty text")

        if not isinstance(theme["notes"], str):
            raise ValueError(f"{theme_key}: notes must be text")

        if not isinstance(theme["default_weight"], Real):
            raise ValueError(f"{theme_key}: default_weight must be numeric")

        for property_name in (
            *WEIGHTED_THEME_PROPERTIES,
            *THEME_METADATA_LIST_PROPERTIES,
        ):
            values = theme[property_name]
            if not isinstance(values, list):
                raise ValueError(
                    f"{theme_key}.{property_name}: expected list"
                )
            if len(values) != len(set(values)):
                raise ValueError(
                    f"{theme_key}.{property_name}: duplicate values are not allowed"
                )

        overrides = theme["weight_overrides"]
        if not isinstance(overrides, dict):
            raise ValueError(f"{theme_key}: weight_overrides must be a dict")

        for property_name, property_overrides in overrides.items():
            if property_name not in WEIGHTED_THEME_PROPERTIES:
                raise ValueError(
                    f"{theme_key}: cannot weight non-membership property "
                    f"{property_name!r}"
                )
            if not isinstance(property_overrides, dict):
                raise ValueError(
                    f"{theme_key}.{property_name}: overrides must be a dict"
                )
            for item, weight in property_overrides.items():
                if item not in theme[property_name]:
                    raise ValueError(
                        f"{theme_key}.{property_name}: override for unlisted "
                        f"item {item!r}"
                    )
                if not isinstance(weight, Real):
                    raise ValueError(
                        f"{theme_key}.{property_name}[{item!r}]: weight must "
                        "be numeric"
                    )


validate_theme_reference()
