
#this file isn't currently in use

#enneagram (approximated). One problem with this system is something get double counted by 'dominant' and also fulfilling the positions of certain criteria.
ENNEAGRAMS = { #each criteria evidently really needs a multiplier weight attached to it for relevance, because not all predictors are equally important...
#if sign, house, body, or nakshatra exists in this constant, add its weight within the chart to the sum of the enneagram type number.
# Optional per-type criterion multipliers can be supplied via: "criterion_multipliers": {"houses":1.25,"signs":1.0,...}.
# Omitted multipliers default to 1.0.
# Individual criterion entries can also be weighted by switching set -> dict, e.g. "positions": {"Moon in Scorpio": 1.4, "Moon in Cancer": 0.8}.
# This works for signs/bodies/houses/nakshatras/gates/positions/aspects (+ anti* variants).
#Positions and aspects must be parsed differently. First, parse the position string so it's algorithmically recognizeable with actual chart positions in the given chart. Then - if take that chart's sign weight, body weight and house weight
    1:{ #sample size was 77, so that's ok, but could be better.
        "name":"Idealist",
        "signs":{"Scorpio":6,"Virgo":4}, #Cancer=9 or 4. Virgo is 3 o4 4. Taurus is 6 or 5.yeah, Cancer surprised me but that's what the data shows. My original guess was Virgo, Scorpio, Aquarius, Capricorn.
        "antisigns":{"Sagittarius":4,}, #subtract these
        "houses":{1:8}, #it is a h10 thing, that's legit. 6%-10%
        "antihouses":{9:5}, #>5% negative correlations in the dataset of 77
        "bodies":{}, #you'd think there'd be strong saturn, but no; maybe just because maybe it's more the character of Saturn (body dynamics) than generic Saturn dominance (body weight).
        "antibodies":{},
        "nakshatras":{"Purva Phalguni":7,"Mrigashira":5,"Chitra":5,"Krittika":4,"Swati":3,"Bharani":1,}, #I thought Purva Ashadha would be positively represented, but it was the strongest negative correlation! Maybe this is a flaw in my qualitative data ranking...
        "antinakshatras":{}, #not including Purva Ashadha yet because I feel like maybe I made a mistake...
        "positions":{"Sun in Scorpio":6,"Sun in Virgo":3,"Sun in Capricorn":4,"Sun in Taurus":4,"Juno in Scorpio":5,"Moon in H8":1,"Chiron in Taurus":6,"Vesta in Taurus":8,"Ceres in Pisces":5,"Mars in Virgo":5,"Juno in Pisces":6,"Mars in Taurus":5,"Vesta in Aquarius":6,"Cancer in H4":7,"Moon in H1":1,"Mercury in H3":11,"Mars in H11":12,"Fortune in H2":10,"Pluto in H3":10,"Venus in H3":10,"Chiron in H3":10,"Moon in H8":9,"Sun in H1":7,"Mars in H3":7,"Neptune in H10":6,"Pallas in H12":7,"Pisces in H3":8,"Capricorn in H1":6,}, #Neptune square Uranus was included, too, but since that's generational, I didn't want to  include it. Was it a fluke or not? Don't know...might imply some generations are more idealistic?
        "antipositions":{},
        "aspects":{"Moon square Pallas":7,"Mars trine Pallas":7,"DS trine Mars":14,"Juno opposition Vesta":7,"Pluto opposition Vesta":6,"AS square Sun":8,"IC trine Moon":10,"Jupiter sextile Pluto":6,"Ketu square Mercury":6,"Moon trine Vesta":6,"Pallas conjunction Uranus":7,"Mercury square Rahu":6,"Fortune square Pluto":5,"AS sextile Pluto":8,"DS trine Pluto":6,"Chiron sextile IC":8}, #"Jupiter sextile MC":1,"DS square Juno":1,"DS conjunction Moon":1,"Mercury trine Saturn":1,"Juno sextile Mercury":1,
        "antiaspects":{"Neptune sextile Pluto":13},
        "gates":{7:13,62:12,4:9,42:8,61:6,37:8,3:6,2:7,51:6}, #12:1,
        "antigates":{57:7,20:6,27:7,46:6,19:8,60:14,5:8,56:14,38:5,19:8,34:8,17:8},
        "channels": {
            (24, 61): 1,
        },
        "antichannels": {
            (20, 34): 1,
            (34, 57): 1,
            (20, 57): 1,
        },
        "hdtypes":{},
        "antihdtypes":{},
        "centers":{},
        "anticenters":{},
        "profiles":{},
        "antiprofiles":{},
        "authorities":{},
        "antiauthorities":{},
        "bazisigns":{},
        "antibazisigns":{},
        "color":"#f5f5f5",
        "motivation":"Perfection, correctness",
        "why":"because what needs done could - and SHOULD - be done better",
        "description":"1s dream of a better world, which begins with themselves. Their scope for seeking the betterness of things may occupy any scale - personal (rigorous regimen to become virtuosic and/or to obliterate one's personal flaws), intimate (seeking to correct the flaws of others), or global/collective (trying to correct perceived flaws in the world and/or its systems at large).",
        "quotes":{"'I don't care if it hurts. / I want to have control. / I want a perfect body. / I want a perfect soul.' - Thom Yorke, Creep"},
        "overrepresented in data": [
        "public critics",
        "writers",
        "commentators",
        "intellectual moralists",
        "aesthetic standard-setters",
        "people with quotable principles",
        "people whose criticism is easy to observe",
        ],
        "underrepresented in data": [
            "quiet duty-based Type 1s",
            "craftsperson Type 1s",
            "domestic/orderly Type 1s",
            "religious or procedural Type 1s who do not verbalize much",
            "service-oriented Type 1s who correct through routine instead of argument",
        ],
        "summary of findings":"A naive model says: Type 1 = Saturn. The data says: Type 1 = distributed correction",
        "results interpretated": {"Virgo: correction","Scorpio/Pluto: detection of hidden rot","Cancer/IC/Moon: protective moral duty","Taurus/Vesta: preservation of value","Pallas: pattern-ordering intelligence","Mars: corrective action","Juno: obligation and relational contract","Mercury/H3: naming, sorting, judging, arguing",},
        },
    2:{ #needs weights
        "name":"Caretaker",
        "signs":{"Libra":7,"Capricorn":7,"Cancer":3,"Scorpio":4}, #Pisces dominance were average in my meager sample of 22. Need a bigger sample, but gotta listen to the data for now.
        "antisigns":{"Gemini":5,},
        "houses":{10:9,4:5,7:5,11:4,5:6},
        "antihouses":{1:5},
        "bodies":{"Venus":13,"Sun":5}, #Venus was the biggest indicator! But is that because they were known for being service-oriented??
        "antibodies":{"Jupiter":9,"Mars":5,"Uranus":6,}, #moon dominange is just below avg in selection; busy looking out for #1, evidently
        "nakshatras":{
            "Krittika":3,"Hasta":3,"Swati":4,"Chitra":3,"Purva Bhadrapada":3,"Dhanishta":11,"Ashwini":3,"Magha":4,"Punarvasu":5,
        },
        "antinakshatras":{"Krittika":3,"Arda":4,"Ashlesha":4,"Mula":6,"Shravana":6}, #the 'bad' gems, and 'bad' pisces...hahaha
        "positions":{
            "Sun in Taurus":1,"Sun in Cancer":7,"Sun in Capricorn":1,
            "Moon in Cancer":1,"Moon in Pisces":1,"Moon in Virgo":1,"Moon in Scorpio":7,"Moon in Leo":7,"Moon in H11":7,
            "Mercury in Capricorn":5,
            "Venus in Gemini":10,"Venus in Pisces":1,"Venus in H6":7,
            "Mars in Cancer":1,"Mars in H11":7,"Mars in H4":7,
            "Jupiter in Cancer":1,"Jupiter in Libra":7,
            "Neptune in Libra":8,"Neptune in H9":7,
            "Uranus in Gemini":8, #idk, maybe it was a more caring age. lol
            "Pluto in H3":7,"Pluto in H8":6,
            "Juno in Libra":7,"Juno in Scorpio":8,"Juno in Cancer":1,"Juno in H1":1,"Juno in H5":1,
            "Rahu in Pisces":6,"Ketu in Aquarius":7,"Ketu in H5":13,"Rahu in H7":10,"Rahu in H8":7,
            "Ceres in Pisces":7,#"Ceres in H1":1,"Ceres in H4":1,
            #"Chiron in Leo":1,"Chiron in H3":1,"Chiron in H12":1,
            "Pallas in Aquarius":11,"Pallas in Scorpio":1,"Pallas in H6":8,
            "Lilith in Scorpio":8,
            "Vesta in Cancer":8,"Vesta in Taurus":1,"Vesta in Sagittarius":8,"Vesta in H4":7,
            "Fortune in Capricorn":5,"Scorpio in H11":11,"Pisces in H3":14,"Gemini in H7":5,
        },
        #these were true for people working in healthcare, but not my list of 'e2s': {"Rahu in Pisces","Moon in Cancer","Chiron in Pisces","Ceres in Pisces","Mars in Pisces","Vesta in H4", "Taurus in H10","Neptune in H4","Ceres in H11"},
        "antipositions":{
            "Sun in Gemini":7,
            "Moon in Aquarius":6,"Moon in Taurus":6,
            "Mercury in Aquarius":5,
            "Venus in Libra":1,
            "Jupiter in Capricorn":6,
            "Neptune in Scorpio":7,
            "Uranus in Aries":1,
            "Pluto in Virgo":1,
            "Juno in Sagittarius":6,
            "Chiron in Aquarius":6,"Chiron in Aries":1,
            "Vesta in Gemini":6,"Vesta in Virgo":5,
        },
        #have another look at aspects for e2, cos I added a bunch and now it might have changed the data:
        "aspects":{
            "Ceres trine Jupiter","Ceres sextile Juno","Saturn square True Lilith","Ceres trine Moon","AS trine Juno","Ceres opposition Neptune","Ceres sextile Mercury","Ceres sextile Fortune","Juno sextile Ketu","Ketu conjunction Sun","Ketu square Neptune","Mars trine Fortune","Mars trine Rahu","Neptune square Rahu","Pallas sextile Pluto","True Lilith sextile Venus","Venus sextile Vesta","Ceres conjunction Moon",}, #wow, Neptune is super at odds with e2?? And the Moon can work cooperatively, but only if Ceres inspires it, or if Juno is involved.
        #these were aspects for healthcare workers, not e2s:{"Ceres sextile Mercury","Chiron trine Vesta","Chiron trine True Lilith","Juno trine Neptune","Mercury trine Neptune","Ketu trine Venus","Ketu square Venus"},
        "antiaspects":{},
        "gates":{58,62,50,13,45,47,52,61,17,},
        "antigates":{34,43,14,26,9,57,22,64,51,29,31,4,},
        "hdtypes":{},
        "antihdtypes":{},
        "channels": {},
        "antichannels": {},
        "centers":{},
        "anticenters":{},
        "profiles":{},
        "antiprofiles":{},
        "authorities":{},
        "antiauthorities":{},
        "bazisigns":{"Dragon":3,"Goat":4},
        "antibazisigns":{"Tiger":3},
        "color":"#cc9900",
        "motivation":"To be useful & necessary to others",
        "why":"to be essential to others; to be useful, needed and loved",
        "description":"2s want to be indispensible to others. They need to be needed. They can only feel that they matter if others depend on them.",
        "quotes":{"'When you're weary / Feeling small / When tears are in your eyes / I will dry them all / I'm on your side. / Oh, when times get rough, / And friends just can't be found...' - Simon & Garfunkel, Bridge Over Troubled Water"},
        "summary of findings":"",
        "results interpretated":{}
        },
    3:{ #no actual data formally assessed & documented; purely theoretical rn based on loose past observations
        "name":"Status-seeker",
        "signs":{"Libra":6,"Scorpio":7,"Aries":12,"Sagittarius":6,"Leo":5,"Taurus":5,"Aquarius":6}, #my initial guesses: "Leo","Capricorn","Taurus","Sagittarius","Libra". I checked "Leo dominant" and saw a lot of subtler probable 3s I'd missed because they were tasteful & well adjusted about it.
        "antisigns":{"Virgo":12,"Pisces":9,"Gemini":9}, #cancer was -1% & cap was -2% but I think they're just subtler about it.
        "houses":{8:3}, #it's about power in society, I guess? Domination through community?
        "antihouses":{1}, #1 doesn't seem to need external validation.
        "bodies":{"Sun":4,"Mars":5,"Jupiter":3,},
        "antibodies":{"Mercury":3,"Venus":4,"Neptune":3},
        "nakshatras":{"Ashwini":8,"Jyestha":8,"Revati":6,"Ashlesha":2,"Vishakha":9,"Hasta":7,"Purva Ashadha":4}, #original guesses: "Vishakha","Jyestha","Ashlesha","Magha",
        "antinakshatras":{"Purva Phalguni":9,"Krittika":9,"Shatabhisha":6,"Shravana":6,"Mula":3,"Uttara Phalguni":5,"Ardra":7,},
        "positions":{
            "Vesta in Cancer":10,"Mars in Aries":12,"Mercury in Aries":8,"Lilith in Pisces":7,"Venus in Pisces":7,"Ceres in Aries":9,"Sun in Taurus":6,"Sun in Aries":6,"Scorpio in H4":9,"Taurus in H10":9,"Cancer in H1":14,"Leo in H2":9,"Aries in H10":9,"Pluto in Scorpio":11,
        }, #sun in Leo is not supported by the data so far, but I believe it's what I've seen in the wild, so I put it on there.
        "antipositions":{
            "Chiron in Pisces":1,"Rahu in H1":1,"Pluto in H12":1,"Saturn in H3":1,"Sun in H12":1,"Uranus in H10":1,"Venus in H11":1,"Vesta in H11":1,"Ceres in H5":1,"Chiron in H9":1,"Jupiter in H2":1,"Mars in H6":1,"Vesta in H10":1,"Vesta in H1":1,"Lilith in H4":1,
            #"Uranus in Virgo", #ignoring outer planets
        },
        "aspects":{"Jupiter sextile Sun","Mercury trine Moon","Saturn trine Sun","Ketu trine Moon","Mars sextile Mercury","Moon trine Rahu","Mars sextile Sun","Moon trine Sun","Ceres square Juno","Ceres square Moon","Chiron square Lilith","Ketu square Vesta","Ketu trine Sun","Mercury semisextile Venus","Mercury square Pluto","Pallas sextile Sun","AS trine Lilith","Rahu square Vesta","Juno conjunction Fortune","Ketu trine Pallas","Lilith sextile Venus","Mars opposition Fortune","Pallas conjunction Pluto","Fortune conjunction Pluto","IC sextile Vesta","IC square Mars","IC trine Venus","MC square Mars","MC trine Vesta","AS sextile Vesta","AS square Saturn",
            #"Saturn trine Uranus",
        },
        "antiaspects":{},
        "gates":{50,34,9,32,5,58,42,54,},
        "antigates":{59,26,12,55,15,6,36,13,23,},
        "hdtypes":{},
        "antihdtypes":{},
        "channels": {},
        "antichannels": {
            (23, 43): 1,
        },
        "centers":{},
        "anticenters":{},
        "profiles":{},
        "antiprofiles":{},
        "authorities":{},
        "antiauthorities":{},
        "bazisigns":{},
        "antibazisigns":{},
        "color":"#ffff00",
        "motivation":"Visible recognition, status and achievement",
        "why":"to be recognized as the best",
        "description":"3s are sort of narcissist-coded, but that doesn't have to be malignant. It can result in materialism, or it could result in extreme competence. Sometimes 3s are mistaken for 1s because they appear driven by perfectionism. But rather than pursuit of perfection/ideals (e1) or competence (e5) for their own sake, 3s are driven by the pursuit of recognition for that competence. Arguably, the easier the trophies and accolades come, the less hard 3s will need to try. The point here is not the conditions of victory, but the recognition of their superiority over others; the status and attention of being president more than the power of owning the red button. They will live and die for that gold star on their paper, and the knowledge that other people know they got it.",
        "quotes":{"'There's been a lot of compromisin' / on the road to my horizon... / but I'm gonna be / where the lights are shinin' on me...' - Glen Campbell, Rhinestone Cowboy"},
        "summary of findings":"",
        "results interpretated":{}
        },
    4:{ #assessed with Similarities Analysis AND DB Analytics.
        "name":"Artist",
        "signs":{"Aquarius":19,"Pisces":18,"Sagittarius":2,"Taurus":1}, #Taurus was -3% in "normcore". Maybe cos they don't conform, but they also don't flagrantly pursue authenticity or truth as an MO. haha. Sag was -4% in "normcore" but didn't register in e4. #theoretically: "Pisces","Aquarius","Scorpio","Sagittarius". I found out that Aquarius dominant charts *are* the weirdest in agregate. But not all Aquarius dominant charts show it.
        "antisigns":{"Libra":9,"Aries":10,"Cancer":6,"Capricorn":5}, #Aries was +10% in "normcore" & -8% in e4. Libra was -9% in e4, +4% in "normcore". Capricorn was -5% in e4, +4% in "normcore". Now! Aquarius was +5% in "normcore" but +19% in e4! But I think that's because radical conservatives look very "normcore" as a form of aggressive authenticity/self expression. So I'm going to leave Aquarius untouched.
        "houses":{3:1}, #H3 has fluctuated from 2-3% in e4, but -3% in "normcore", so I included it.
        "antihouses":{4:5},
        "bodies":{"Neptune":4,"Mercury":1}, #Mercury was -3% in "normcore". Neptune was -2%. #theoretically: "Uranus","Lilith"
        "antibodies":{},
        "nakshatras":{"Shravana":10,"Purva Bhadrapada":5,"Shatabhisha":7,"Purva Phalguni":3}, #Purva Phalguni was -3% in "normcore"
        "antinakshatras":{"Krittika":4,"Hasta":6,"Mula":4}, #Hasta was +6% in "normcore", Mula was +4% in "normcore"; Krittika was -4% in "e4"
        "positions":{
            "Sun in Pisces":8,"Sun in Aquarius":7,"Sun in H2":6, #Sun in Pisces was -1% normcore, Sun in Aquarius was 1% normcore.
            #no lunar correlations for e4, but Moon in Scorpio & Moon in Gemini were -4% normcore.
            "Mercury in Pisces":4,"Mercury in Aquarius":8, #Mercury in Taurus & Virgo are -5% normcore.
            "Venus in Aquarius":3,"Venus in Pisces":4,"Venus in Gemini":6,"Venus in H12":5, #Venus in Aquarius was 6% in normcore, and 6% in e4, too, so I split the diff & made it 3. Venus in Gem was 4% in e4 & -4% in normcore, so I boosted it to 6.
            "Mars in Pisces":4,"Jupiter in Pisces":4,"Jupiter in H10":5, #Mars in Gemini & Cancer were -3% normcore but nothing in e4.
            "Saturn in Aquarius":5,"Saturn in H2":6,"Saturn in Leo":4, #Saturn in Leo was -4% normcore, nothing in e4.
            "Neptune in Scorpio":7,
            "Uranus in H11":5,
            "Pluto in Virgo":5,
            "Lilith in Pisces":5,"Fortune in Sagittarius":4,"Vesta in Aquarius":4,"Pallas in Aquarius":6,
            "Chiron in Leo":4,"Chiron in Pisces":5,"Chiron in H5":7,
            "Scorpio in H1":3,"Aries in H1":4,"Gemini in H3":5,
            }, #theoretically: "Mercury in Pisces","Mars in Pisces","Pluto in Scorpio","Ketu in H8"
        "antipositions":{
            "Sun in Aries":3,"Sun in Virgo":1,"Sun in Capricorn":1,"Sun in Libra":3,"Sun in H4":5, #Sun in Aries is +3% 'normcore' & -3% e4. But Virgo was -3% e4 & -2% 'normcore'. Sun in Libra was -3% e4 & +2% 'normcore'. Sun in Cap was +3% normcore.
            "Moon in Leo":6, #no correlations in e4, but +6% in 'normcore'
            "Mercury in Scorpio":3,"Mercury in Libra":4,"Mercury in Capricorn":7, #Mercury in Scorpio was +2% norcore; removed Merc in Vir cos it was -5% normcore and only -3% in e4.
            "Venus in Leo":2,"Venus in Virgo":2,"Venus in H2":6, #Neither Leo nor Virgo Venus showed up much in 'normcore'; they were only absent in e4, so I reduced them both by 2. Venus in Aquarius was 6% in normcore, and 6% in e4, too.
            "Mars in Libra":3,
            "Jupiter in Libra":5,
            "Saturn in Scorpio":3,
            "Uranus in Taurus":5,"Neptune in Virgo":5,
            "Pluto in Cancer":5,
            "Chiron in Gemini":4,"Vesta in Capricorn":4,"Vesta in H5":5,"Lillith in H7":5,
            "Cancer in H1":4,"Sagittarius in H1":3,"Aries in H10":3,"Cancer in H10":3,
        },
        "aspects":{
            "Chiron opposition Uranus":6,"Neptune sextile Pluto":12,"Ketu trine Mercury":5,"Neptune trine Vesta":5,"Ceres trine Pluto":5,"Mercury trine Rahu":6,"Mars square Venus":5,"Rahu trine Vesta":5,"Juno trine Uranus":5,"Jupiter square Pallas":5,"Ketu sextile Vesta":5,
        },
        "antiaspects":{},
        "gates":{55:11,59:6,19:7,29:5,},
        "antigates":{60:7,27:6,21:6,52:6,48:6,33:6,64:5,17:5,58:5,62:5},
        "hdtypes":{"MF Generator":4},
        "antihdtypes":{"Generator":6},
        "channels": {},
        "antichannels": {},
        "centers":{},
        "anticenters":{},
        "profiles":{},
        "antiprofiles":{"4/6":4},
        "authorities":{"Emotional":5},
        "antiauthorities":{"Sacral":4},
        "bazisigns":{"Tiger":4}, #Tiger was also -2% in "normcore"
        "antibazisigns":{"Ox":3}, #+3% in "normcore"
        "color":"#cc66ff",
        "motivation":"Individuality, depth of experience & authenticity",
        "why":"to feel something real",
        "description":"4s don't mind if you think they're a freak. They want a genuine experience, be it the depths of pain or pleasure. They want beauty, but see beauty and truth as inseparable, so we aren't talking Kpop symmetry and Kardashians; we're talking scar-faced midwives, Edward James Olmos' face, Bukowski poems, Philip-Lorca diCorcia photos, Disco Elysium, David Lynch and Adrienne Shelly indie flicks. They can be goth-coded, but they aren't all goths. Many seek originality and ways of distinguishing themselves from the mainstream, but that may be just a reaction to the inauthenticity of the mainstream. There's a lot of BS backstory lore on e4s by major voices in Enneagram theory who say stuff like 'e4s feel there's an essential part of themselves missing' or are driven by self-pity and similar nonsense. It's all rubbish written by people who clearly don't understand them. Like their moms. *slams door*",
        "quotes":{"'Drink up one more time / and I'll make you mine, / keep you apart, / deep in my heart / separate from the rest, / where I like you the best-- / and keep the things you forgot...' - Elliott Smith, Between the Bars","'Baby, do you understand me now? / Sometimes I feel a little mad... / Don't you know no one alive can always be an angel.../ When things go wrong, I seem to be bad.  - The Animals, Don't Let Me Be Misunderstood","Marge: Why all the black? / Homer: Why all the pearls? Why all the hair? Why anything? - The Simpsons"},
        "summary of findings":"",
        "results interpretated":{}
        },
    5:{
        "name":"Investigator", #Scholar, Permastudent, Datahoarder, Researcher, Hermit
        "signs":{"Gemini":14,"Cancer":5,"Libra":1,"Aries":1}, #I checked, and Gemini dominant people are usually e7, not e5. e5 geminis are a minority, even though I know several 'super geminis' who are e5; they're all Saturnian Geminis; it's a different thing than standard gemini.
        "antisigns":{"Aquarius":6,"Sagittarius":6,"Scorpio":8,"Virgo":6},
        "houses":{3:12,6:11}, #"I came here to chew work and collect data. And I'm all outta work..."
        "antihouses":{4:8,10:6}, #Who knew. Nerdiness & public status are evidently antithetical...
        "bodies":{"Moon":4,"Venus":4,"Neptune":6}, #"Mercury","Pluto","Pallas"
        "antibodies":{"Jupiter":12,"Pluto":6},
        "nakshatras":{"Mrigashira":11,"Bharani":6,"Chitra":5,"Krittika":5,"Punarvasu":4}, #"Purva Phalguni","Krittika","Vishakha"
        "antinakshatras":{"Purva Ashadha":5,"Hasta":6,}, #"Swati","Pushya","Purva Bhadrapada"
        "positions":{
            "Sun in Cancer":6,"Sun in Gemini":3,"Sun in Taurus":4,"Sun in Virgo":3,"Sun in Scorpio":3,
            "Moon in Aries":3,"Moon in Cancer":3,"Moon in Pisces":3,
            "Mercury in Gemini":5,"Mercury in Taurus":8,
            "Venus in Aries":8,"Venus in Gemini":8,"Venus in Scorpio":6,
            "Mars in Libra":11,"Mars in Capricorn":8,
            "Jupiter in Gemini":11,
            "Saturn in Leo":5,"Scorpio in H1":7,"Gemini in H1":4,"Virgo in H10":9,"Cancer in H2":9,"Pallas in Aquarius":1,"Mercury in H3":1,"Venus in H4":1,"Vesta in H7":1,"Mercury in H12":1,"Moon in H6":1,"Venus in H3":1,"Capricorn in H8":1},
        "antipositions":{"Sun in Leo","Sun in Libra","Sun in Sagittarius","Sun in Pisces","Moon in Scorpio","Moon in Capricorn","Venus in Capricorn","Venus in Sagittarius","Mars in Scorpio","Mars in Aquarius","Jupiter in Cancer","Jupiter in Leo","Uranus in Virgo","Leo in H1","Sagittarius in H1","Libra in H10"},
        "aspects":{"Sun conjunction Venus":11,"Ceres square Jupiter":10,"Mercury conjunction Venus":5,"Moon trine Pallas":10,"Fortune square Vesta":9,"Chiron trine Mars":10,"Uranus square Venus":10,"Chiron square Pluto":9,"Neptune sextile Sun":7,"Moon square Lilith":8,"Juno trine Moon":7,"Juno square Ketu":7,"Jupiter square Rahu":7,"Ceres square Lilith":7,"Chiron square Fortune":7,"Ketu trine Vesta":6,"Neptune sextile Sun":7,"Saturn trine Lilith":6,"IC conjunction Venus":14,"IC square Jupiter":10,"IC square Vesta":9,"IC trine Neptune":10,}, #there are more. Also: 'but in what signs??'
        "antiaspects":{"Chiron opposition Uranus":16},
        "gates":{57:11,7:13,23:14,31:11,12:10,45:8,46:10,17:12,27:8,36:9,8:11,22:8,25:6,24:6},
        "antigates":{43:8,50:10,29:11,44:17,5:10,56:8,54:8,40:12,59:28,19:12,63:8},
        "hdtypes":{},
        "antihdtypes":{},
        "channels": {},
        "antichannels": {},
        "centers":{},
        "anticenters":{},
        "profiles":{"2/4"},
        "antiprofiles":{"5/1","6/2"},
        "authorities":{"Splenic"},
        "antiauthorities":{},
        "bazisigns":{"Horse"},
        "antibazisigns":{"Dog"},
        "color":"#669900",
        "motivation":"Knowledge & information, personal autonomy",
        "why":"for the love of knowledge",
        "description":"5s want to understand the world, whether through a microscope or a telescope. They generally perceive themselves as on the outside, looking in at the experiment of existence. They go to great pains to ensure that their lab is protected so that their subjects (the outside world) cannot touch them, messy their lab and disrupt their experiments.",
        "quotes":{"'I'm so glad I got burned, / think of all the things we learned / from the people who are / still alive. / And believe me I'm still alive. / I'm doing science and I'm still alive.' - Portal Soundtrack, Still Alive","'There is research to be done, / and we made a neat gun / for the people who are / still alive...' - Portal soundtrack, Still Alive","'Well they gave me medication so I feel how I imagine people of average intelligence feel all the time.' - Dr. Temperance Bones, Bones"},
        "summary of findings":"",
        "results interpretated":{}
        },
    6:{
        "name":"Loyalist", #Acolyte, authority
        "signs":{"Aries":11,"Virgo":2,"Capricorn":2,},
        "antisigns":{},
        "houses":{}, #6 was only weakly represented
        "antihouses":{},
        "bodies":{"Sun":14,"Saturn":-13}, #Mars is also 5%, but maybe just due to Aries dominance? Don't want to double count it.
        "antibodies":{}, #Apparently Saturn isn't a joiner??? I suspect the aspects to Saturn matter tremendously, as much as how it's weighed.
        "nakshatras":{"Ashwini":10,"Purva Phalguni":3,},
        "antinakshatras":{},
        "positions":{
            "Sun in Aries": 12,
            "Moon in Cancer": 8,
            "Mercury in Aries": 10,
            "Mercury in Virgo": 7,
            "Mercury in H2": 12,
            "Venus in Gemini": 14,
            "Mars in Taurus": 7,
            "Jupiter in H3": 13,
            "Saturn in Pisces": 12,
            "Saturn in H6": 10,
            "Uranus in Virgo": 10,
            "Neptune in H9": 12,
            "Chiron in H3": 13,
            "Ceres in Capricorn": 10,
            "Pallas in Sagittarius": 9,
            "Pallas in H3": 10,
            "Pallas in H10": 11,
            "Juno in Cancer": 6,
            "Juno in Leo": 8,
            "Juno in Capricorn": 7,
            "Rahu in Gemini": 6,
            "Rahu in Cancer": 7,
            "MC in Libra": 9,
            "Aries in H4": 9,
            "Libra in H10": 9,
            #old version:
        #     "Sun in Leo":8,"Sun in Capricorn":6,"Sun in Pisces":6,"Sun in Aries":12,"Sun in H6":12,
        #     "Saturn in Sagittarius":7,"Saturn in Scorpio":5,"Saturn in Pisces":3,
        #     "Moon in Taurus":4,"Moon in Cancer":6,
        #     "Mercury in Virgo":10,"Mercury in Pisces":10,"Mercury in Capricorn":4,
        #     "Venus in Virgo":5,"Venus in Pisces":7,"Venus in H4":6,"Venus in H7":5, #Venus in Gemini was overrepresented but I think that's because these are all very communicative, information-driven, chatty people - which is how it's clear they're e6. That's arguably what makes their e6ness identifiable.
        #     "Mars in Taurus":8,"Mars in Gemini":8,"Mars in Scorpio":4,"Mars in Aries":4,
        #     "Jupiter in Gemini":7,"Jupiter in Aries":5,
        #     "Saturn in Pisces":10,"Saturn in H1":8,
        #     "Chiron in Pisces":12,
        #     "Ceres in Capricorn":2,
        #     "Fortune in Libra":3,
        #     "Lilith in H10":8, #unsure if this is more about them being a public traditionalist or about them needing to transgress to defend institutions. The lore supports either interpretation. May be a false signal based on selection bias (whoever is publicly controversial - in general - or specifically about traditionalism, Mrs. Waterford style), or not.
        #     "Aries in H1":4,"Cancer in H1":1,"Cancer in H6":9,"Pisces in H1":7},
        #     #i might ignore venus in gem & thought about ignoring venus in pisces - don't buy it!
        # "antipositions":{
        #     "Sun in Sagittarius":7,"Sun in Aquarius":5,"Sun in Gemini":4,"Sun in Scorpio":3,
        #     "Moon in Leo":6,"Moon in Scorpio":1,"Moon in Gemini":1, #not in e6, but Scorpio & Gem moon were both -4% in 'normcore', possibly implying that they refuse to join.
        #     "Mercury in Gemini":5,"Mercury in Libra":5,"Mercury in Scorpio":5,"Mercury in Sagittarius":4,"Mercury in Aquarius":5,
        #     "Venus in Aries":1,"Venus in Scorpio":1,"Venus in Sagittarius":3,
        #     "Mars in Aquarius":6,"Mars in Capricorn":6,"Mars in Leo":5,
        #     "Jupiter in Cancer":6,
        #     "Saturn in Capricorn":9,"Saturn in Libra":6,
        #     "Virgo in H1":11,"Gemini in H1":4,}, #"Capricorn in H11":1,"Aquarius in H12":1,"Leo in H6":1,"Pisces in H3":1,"Virgo in H9":1,"Chiron in Aries":1,"Sun in H10":1,"Neptune in Sagittarius":1,"Pluto in Libra":1,"Juno in Scorpio":1,"Jupiter in Cancer":1,
        },
        "aspects":{
            "Mercury conjunction Sun": 12,
            "Chiron opposition Pluto": 10,
            "Pluto conjunction Uranus": 10,
            "Ceres trine Jupiter": 9,
            "Rahu trine Saturn": 10,
            "Saturn opposition Uranus": 15,
            "Mars trine Pallas": 9,
            "True Lilith square Vesta": 10,
            "Ceres trine Mercury": 9,
            "Chiron square Jupiter": 10,
            "Juno conjunction Pallas": 8,
            "Mercury trine Pluto": 8,
            "Venus sextile Vesta": 8,
            "Ceres opposition Rahu": 9,
            "Juno square Saturn": 7,
            "Pallas trine Sun": 8,
            "Pluto square True Lilith": 7,
            "Chiron square True Lilith": 6,
            "Juno sextile Moon": 7,
            "Juno square Uranus": 6,
            "Mars sextile Venus": 6,
            "Mars trine Vesta": 6,
            "Moon sextile Venus": 7,
            "Moon square Neptune": 7,
            "Pallas square Pluto": 7,
            "Ceres sextile Rahu": 6,
            "Part of Fortune conjunction Sun": 8,
            "Ceres quincunx Jupiter": 7,
            "Juno quincunx Rahu": 7,
            "Mercury conjunction Part of Fortune": 6,
            "Mercury opposition Neptune": 6,
            "Pallas conjunction Part of Fortune": 7,
            "AS conjunction True Lilith": 16,
            "AS trine Mars": 13,
            "AS trine Pluto": 11,
            "Ceres quintile Chiron": 7,
            "Ceres semisextile Juno": 7,
            "MC square Saturn": 11,
            "Mercury opposition Moon": 5,
            "Moon quincunx Pluto": 6,
            "Neptune quintile Uranus": 7,
            "Pluto conjunction Vesta": 6,
            "Sun conjunction Vesta": 5,
            "AS sextile Jupiter": 10,
            "Ceres biquintile Jupiter": 7,
            "Chiron quincunx Part of Fortune": 5,
            "Jupiter biquintile Rahu": 6,
            "Mars semisextile Saturn": 5,
            "Moon semisquare Uranus": 6,
            "Pallas quincunx Rahu": 5,
            "Ceres quincunx Pluto": 4,
            "Ceres semisextile Venus": 5,
            "Ceres sesquiquadrate Neptune": 5,
            "Chiron semisquare Mars": 5,
            "Mars biquintile Neptune": 5,
            "Mars semisextile Part of Fortune": 5,
            "MC conjunction Rahu": 8,
            "MC conjunction True Lilith": 10,
            "Mercury biquintile Rahu": 5,
            "Moon quintile Sun": 4,
            "Neptune biquintile Saturn": 5,
            "Pallas opposition Sun": 4,
            "Pallas opposition Venus": 4,
            "Pallas quincunx Part of Fortune": 4,
            "Pallas semisextile Saturn": 5,
            "Pluto semisquare Saturn": 5,
            "Rahu sesquiquadrate Vesta": 5,
            "Sun quincunx Uranus": 4,
            "Uranus biquintile Vesta": 5,
            "AS quincunx Venus": 9,
            "Ceres semisquare Neptune": 4,
            "Chiron quintile Venus": 3,
            "Chiron semisextile Part of Fortune": 4,
            "Chiron semisquare Jupiter": 4,
            "Chiron sesquiquadrate Venus": 4,
            "Juno quintile MC": 9,
            "Jupiter biquintile Vesta": 3,
            "Jupiter quintile Vesta": 4,
            "Mercury quintile Moon": 4,
            "Moon quintile Pluto": 3,
            "Moon semisextile Vesta": 4,
            "Moon semisquare Pluto": 3,
            "Pluto quintile Uranus": 4,
            "Rahu quintile Sun": 4,
            "AS biquintile Juno": 6,
            "AS quintile Pallas": 6,
            "AS semisquare Ceres": 6,
            "MC biquintile Mars": 6,
            "MC semisextile Part of Fortune": 6,
            "MC semisquare Moon": 6,
            "MC semisquare Part of Fortune": 7,
            "AS sesquiquadrate Sun": 4,
            # "Pallas sextile Saturn","Pallas square Rahu","Chiron square Saturn","Saturn trine Sun","Juno square Saturn","Saturn square Vesta","Saturn sextile Sun", #common correlation between e6 groups
            # "Juno conjunction Pallas","Chiron square Jupiter","Mercury conjunction Sun","Mars trine Vesta","Lilith square Vesta","Juno sextile Moon","Moon square Neptune","Mars trine Pallas","Rahu trine Saturn","Ceres square Uranus","Ketu square Lilith","Mars trine Neptune","Mercury trine Neptune","Neptune sextile Lilith","Fortune conjunction Sun","Rahu square Lilith","DS trine Jupiter","AS sextile Jupiter","AS trine Vesta","Ceres biquintile Jupiter","IC trine Moon","Moon quincunx Pluto","AS conjunction Lilith","AS trine Mars","AS trine Pluto","Fortune opposition Saturn", #original correlations before I found a predictive group
            },
        "antiaspects":{"Chiron trine Neptune","Saturn trine Uranus"},
        "gates": {
            40: 17,
            3: 13,
            25: 11,
            28: -12,
            41: -13,
            #round 2
            # 40: 39, #was in original set
            # 64: 40,
            # 1: 27,
            # 21: 24,
            # 52: 23,
            # 60: 23,
            # 44: -24,
            # 57: -25,
            #12,32,40,3,11,42,54, #that was the original set.
        },
        "antigates":{28,26,58,15,18,64,55,41,17},
        "channels": {
            (3, 60): 8,
            (39, 55): 7,
            (25,51):7
            # (12, 22): 4,
            # (37, 40): 4,
        },
        "antichannels": {},
        "hdtypes":{},
        "antihdtypes":{},
        "centers": {
            # "Solar Plexus": 25,
            # "Spleen": -29,
        },
        "anticenters":{},
        "profiles":{},
        "antiprofiles":{},
        "authorities":{
        },
        "antiauthorities":{},
        "bazisigns":{},
        "antibazisigns":{},
        "color":"#0099cc",
        "motivation":"Duty, performing perceived social role & fulfilling personal responsibilities.",
        "why":"because that's what someone with their responsibilities does, according to respected authorities",
        "description":"6s are generally here to maintain their view of the status quo, upholding their recognized hierarchy, and support their tribe. This can look very different depending on who they recognize as their authority figure (leader), and who/what they believe is their tribe (which can exist at varying scales from the very personal to the very global). Independent of scale, they will expect members of their perceived tribe to fulfill their responsibilities/duties/roles within the tribe as well. In the creator of this app's opinion, there is no 'counterphobic 6' as lore suggests - just one type of 6, who is always deferential to role models, even if the early Recognized Tribal Authority was Hunter S Thompson, Charlton Heston or the Unibomber. Saying e6 is about 'security' is tautological; the entire enneagram is about how individuals seek a sense of security; e6 seeks it through tribal role participation'.",
        "quotes":{"'If I'd said that to MY daddy, he'd have...[insert reflection on one's father's archetypal behavior, intended as a model of exemplary response to the situation]' - a phrase often invoked by nearly everyone in the American South & Bible Belt.","'Three weeks from now, I will be harvesting my crops. Imagine where you will be, and it will be so. Hold the line! Stay with me! If you find yourself alone, riding in the green fields with the sun on your face, do not be troubled. For you are in Elysium, and you're already dead! Brothers, what we do in life echoes in eternity...' - Maximus, Gladiator","'Five thousand of my men are out there in the freezing mud. Three thousand of them are bloodied and cleaved. Two thousand will never leave this place. I will not believe that they fought and died for nothing.' - Maximus, Gladiator","'Sometimes I do what I want to do. The rest of the time, I do what I have to.' - Cicero, Gladiator","'You have a great name. He must kill your name before he kills you.' - Juba, Gladiator",},
        "summary of findings":"",
        "results interpretated":{}
        }, #"'Elephants are not purple. This is wrong.' - Dr. Temperance Bones, Bones"
    7:{
        "name":"Explorer",
        "signs":{"Gemini","Sagittarius","Pisces"},
        "antisigns":{"Scorpio","Libra"},
        "houses":{5},
        "antihouses":{},
        "bodies":{"Jupiter","Sun"},
        "antibodies":{"Mars","Pluto"},
        "nakshatras":{"Rohini","Ashwini","Shravana","Purva Phalguni"},
        "antinakshatras":{},
        "positions":{"Pisces in H4","Neptune in Sagittarius","Venus in Aquarius","Venus in H3","Scorpio in H12"},
        "antipositions":{"Scorpio in H1"},
        "aspects":{},
        "antiaspects":{},
        "gates":{43,54},
        "antigates":{},
        "hdtypes":{},
        "antihdtypes":{},
        "channels": {},
        "antichannels": {},
        "centers":{},
        "anticenters":{},
        "profiles":{},
        "antiprofiles":{},
        "authorities":{},
        "antiauthorities":{},
        "bazisigns":{},
        "antibazisigns":{},
        "color":"#ff33cc",
        "motivation":"Escaping adversity, embracing pleasure",
        "why":"because it sounded fun",
        "description":"Essentially, 7s are about a blend of hedonism and epicurianism. They are here to enjoy life, and avoid what detracts from that enjoyment.",
        "quotes":{"'Hey, I just met you / and this is crazy / but here's my number / so call me maybe...' - Carly Rae Jepsen, Call Me Maybe","'This is the day you will always remember as the day you almost caught Captain Jack Sparrow.' - Capt. Jack Sparrow, Pirates of the Caribbean","'What’s the hassle, Schmasel?' - Bugs Bunny","'Well, like the Romans always say … E pluribus uranium.' - Bugs Bunny"},
        },
    8:{ #needs weights
        "name":"Sovereign", #Barbarian, philarch, crushinator, czar, dominatrix, social darwinist, The Ruler
        "signs":{"Aries","Libra"}, #"Sagittarius","Leo"
        "antisigns":{},
        "houses":{10,4},
        "antihouses":{},
        "bodies":{"Mars","Pluto"},
        "antibodies":{"Neptune",},
        "nakshatras":{"Jyestha","Uttara Phalguni","Swati"}, #"Purva Bhadrapada","Krittika","Chitra"
        "antinakshatras":{},
        "positions":{"Moon in Aries","Chiron in Pisces","Ceres in Leo","Pallas in Cancer","Moon in H1","Pluto in H10","Ceres in H4","Vesta in H10",},
        "antipositions":{"Sagittarius in H1","Rahu in H12","Venus in H3","Taurus in H6","Capricorn in H2","Cancer in H8"},
        "aspects":{"Chiron opposition Pluto","Jupiter square Rahu","Jupiter trine Mars","Pallas sextile Saturn"},
        "antiaspects":{},
        "gates":{44,32,62,49,12,},
        "antigates":{55,24,18,58},
        "hdtypes":{},
        "antihdtypes":{},
        "channels": {},
        "antichannels": {},
        "centers":{},
        "anticenters":{},
        "profiles":{},
        "antiprofiles":{},
        "authorities":{},
        "antiauthorities":{},
        "bazisigns":{},
        "antibazisigns":{},
        "color":"#ff0000",
        "motivation":"Personal sovereignty, dominance, asserting control",
        "why":"to avoid being controlled",
        "description":"3s may pursue dominance through material recognition and social status. 8s will pursue it by any means necessary. Power not for social validation, not as a conditioned social response that recognizes and values the established institutions and wishes to perform within them, but potentially outside them. Whatever it takes to be in control, or at very least to avoid being controlled by others.",
        "quotes":{"'You know the way to stop me / but you don't have the discipline. / How many nights have I prayed for this? / To let my work begin...! / First we take Manhattan... / then we take Berlin!' - Leonard Cohen, First We Take Manhattan","'They’re whispering his name across this disappearing land / But hidden in his coat is a red right hand... / You ain’t got no money? / He’ll get you some / You ain’t got no car? / He’ll get you one / You ain’t got no self-respect, you feel like an insect / Well don’t you worry buddy, cause here he comes...' - Nick Cave, Red Right Hand","'People should know when they're conquered.' - Quintus, Gladiator"},
        "summary of findings":"",
        "results interpretated":{}
        },
    9:{ #needs weights
        "name":"Pacifist",
        "signs":{"Capricorn","Cancer","Sagittarius"}, #Aries also came up
        "antisigns":{"Gemini","Leo","Aquarius","Virgo"},
        "houses":{4,5,6},
        "antihouses":{2,1,8,9},
        "bodies":{"Sun","Moon"},
        "antibodies":{"Mars","Mercury"},
        "nakshatras":{"Ardra","Dhanishta","Shatabhisha","Uttara Bhadrapada",}, #Jyestha came up, but I think they're faking it
        "antinakshatras":{"Uttara Phalguni","Swati"},
        "positions":{
            "Virgo in H4","Pisces in H10","Pisces in H4","Virgo in H10","Cancer in H1",
            "Sun in Capricorn","Sun in Pisces",
            "Moon in Leo","Moon in Sagittarius","Moon in H4",
            "Mercury in Cancer","Mercury in Libra","Moon in Aries",
            "Uranus in Capricorn",
            "Chiron in Taurus","Chiron in H11","Chiron in H12",
            "Fortune in Aquarius","Fortune in H6",
            "Pallas in Pisces","Lilith in Aries",
            "Jupiter in Cancer",
            "Saturn in Taurus","Saturn in Capricorn",
            "Neptune in H6",
            "Uranus in Aquarius","Uranus in Scorpio","Uranus in H5",
            "Ketu in H9",
            "Ceres in Sagittarius","Ceres in Taurus",
            "Juno in Aquarius","Juno in Libra",
            "Mars in H4","Rahu in H3","Saturn in H3","Sun in H4","Uranus in H10","Fortune in H3","Venus in H5","Venus in H7","Vesta in H6",
        },
        "antipositions":{"Neptune in Libra","Pallas in Aquarius","Pluto in Leo",},#"Sun in Taurus","Sun in Scorpio","Sun in Leo","Sun in Aquarius","Moon in Aquarius","Moon in Taurus","Moon in Gemini","Moon in Cancer","Moon in Virgo","Moon in Capricorn","Mercury in Gemini","Mercury in Scorpio","Mercury in Pisces","Mercury in Leo","Venus in Sagittarius",,"Mars in Scorpio","Mars in Capricorn","Saturn in Aquarius","Mars in Aquarius"},
        "aspects":{
            "Pallas trine Pluto","Chiron trine Jupiter","Juno trine Saturn","Chiron sextile Juno","Neptune sextile Pallas","Pallas square Vesta","Saturn trine Sun","Ceres opposition Jupiter","Ceres sextile Fortune","Ceres trine Moon","Chiron opposition Saturn","Juno trine Mars","Juno trine Uranus","Ketu trine Neptune","Mercury square Moon","Moon sextile Uranus","Mars trine Neptune","Moon square Sun","Neptune quincunx Sun","Neptune square Fortune","Saturn trine Venus","Ceres sextile Rahu","Ceres sextile Sun","Ceres trine Ketu","Chiron trine Fortune","Juno conjunction Mercury","Juno square Moon","Jupiter opposition Sun","Mars sextile Pluto","Fortune opposition Lilith","IC sextile Uranus","IC trine Jupiter"
        },
        "antiaspects":{},
        "gates":{20,5,54,18,58,26,48,63,8,9,17,30,52,55},
        "antigates":{1,44,50,6,33,43,2,60,4,42,49,7,3,24},
        "channels": {
            (20, 57): 1,
            (18, 58): 1,
            (37, 40): 1,
            (17, 62): 1,
            (4, 63): 1,
        },
        "antichannels": {},
        "hdtypes":{},
        "antihdtypes":{},
        "centers":{"Root"},
        "anticenters":{"Sacral"},
        "profiles":{},
        "antiprofiles":{"1/4","4/1","2/5"},
        "authorities":{"Sacral"},
        "antiauthorities":{},
        "bazisigns":{"Snake",},
        "antibazisigns":{"Dragon","Tiger",},
        "color":"#cc99ff",
        "motivation":"Tranquility. Maintaining harmony at any cost",
        "why":"to maintain the peace",
        "description":"9s just want peace. They want everyone to get along. Unlike 1s, they won't generally lash out at those disrupting the peace, but will quietly brood and retreat from those who cause chaos and disharmony. If they ever choose to stand for anything, it would likely be a stand for nonviolence, a stand to end conflict. They can be hard to recognize because they often adapt & shapeshift as a means of keeping peace.",
        "quotes":{"'Well, you may say that I'm a dreamer / but I'm not the only one. / I hope someday you'll join us... / and the world can live as one.' - John Lennon, Imagine"},
        "summary of findings":"",
        "results interpretated":{}
        },
} #no one knows wtf Hasta wants. lol Bharani is hunger, but not in a chill or fun way. Uttara Phalguni for e2 is experimental. P. Phal is experimental for e7 but seems to fit.
