"""Human Design incarnation cross reference.

Source used to assemble this reference:
- Love Your Human Design, "Incarnation Cross List":
  https://loveyourhumandesign.com/incarnation-crosses/

Notes:
- This file stores the 192 full chart labels parsed from the public index page.
- Each entry includes the cross type, thematic name, optional numeric variant, and
  the four gates in the order shown by the source:
  (personality_sun, personality_earth, design_sun, design_earth).
- Some secondary sources describe the system as 192 basic crosses, or 768
  profile/line variations, so naming/count conventions can differ by source.

Generated automatically from a parsed index page.
"""

HD_INCARNATION_CROSSES = [{'full_name': 'Right Angle Cross of the Sphinx 4',
  'cross_type': 'Right Angle',
  'theme': 'the Sphinx',
  'variant': 4,
  'gates': (1, 2, 7, 13)},
 {'full_name': 'Juxtaposition Cross of Self-Expression',
  'cross_type': 'Juxtaposition',
  'theme': 'Self-Expression',
  'variant': None,
  'gates': (1, 2, 4, 49)},
 {'full_name': 'Left Angle Cross of Defiance 2',
  'cross_type': 'Left Angle',
  'theme': 'Defiance',
  'variant': 2,
  'gates': (1, 2, 4, 49)},
 {'full_name': 'Right Angle Cross of the Sphinx 2',
  'cross_type': 'Right Angle',
  'theme': 'the Sphinx',
  'variant': 2,
  'gates': (2, 1, 13, 7)},
 {'full_name': 'Juxtaposition Cross of the Driver',
  'cross_type': 'Juxtaposition',
  'theme': 'the Driver',
  'variant': None,
  'gates': (2, 1, 49, 4)},
 {'full_name': 'Left Angle Cross of Defiance',
  'cross_type': 'Left Angle',
  'theme': 'Defiance',
  'variant': None,
  'gates': (2, 1, 49, 4)},
 {'full_name': 'Right Angle Cross of Laws',
  'cross_type': 'Right Angle',
  'theme': 'Laws',
  'variant': None,
  'gates': (3, 50, 60, 56)},
 {'full_name': 'Juxtaposition Cross of Mutation',
  'cross_type': 'Juxtaposition',
  'theme': 'Mutation',
  'variant': None,
  'gates': (3, 50, 41, 31)},
 {'full_name': 'Left Angle Cross of Wishes',
  'cross_type': 'Left Angle',
  'theme': 'Wishes',
  'variant': None,
  'gates': (3, 50, 41, 31)},
 {'full_name': 'Right Angle Cross of Explanation 3',
  'cross_type': 'Right Angle',
  'theme': 'Explanation',
  'variant': 3,
  'gates': (4, 49, 23, 43)},
 {'full_name': 'Juxtaposition Cross of Formulization',
  'cross_type': 'Juxtaposition',
  'theme': 'Formulization',
  'variant': None,
  'gates': (4, 49, 8, 14)},
 {'full_name': 'Left Angle Cross of Revolution 2',
  'cross_type': 'Left Angle',
  'theme': 'Revolution',
  'variant': 2,
  'gates': (4, 49, 8, 14)},
 {'full_name': 'Right Angle Cross of Consciousness 4',
  'cross_type': 'Right Angle',
  'theme': 'Consciousness',
  'variant': 4,
  'gates': (5, 35, 64, 63)},
 {'full_name': 'Juxtaposition Cross of Habits',
  'cross_type': 'Juxtaposition',
  'theme': 'Habits',
  'variant': None,
  'gates': (5, 35, 47, 22)},
 {'full_name': 'Left Angle Cross of Separation 2',
  'cross_type': 'Left Angle',
  'theme': 'Separation',
  'variant': 2,
  'gates': (5, 35, 47, 22)},
 {'full_name': 'Right Angle Cross of Eden 3',
  'cross_type': 'Right Angle',
  'theme': 'Eden',
  'variant': 3,
  'gates': (6, 36, 12, 11)},
 {'full_name': 'Juxtaposition Cross of Conflict',
  'cross_type': 'Juxtaposition',
  'theme': 'Conflict',
  'variant': None,
  'gates': (6, 36, 15, 10)},
 {'full_name': 'Left Angle Cross of the Plane 2',
  'cross_type': 'Left Angle',
  'theme': 'the Plane',
  'variant': 2,
  'gates': (6, 36, 15, 10)},
 {'full_name': 'Right Angle Cross of the Sphinx 3',
  'cross_type': 'Right Angle',
  'theme': 'the Sphinx',
  'variant': 3,
  'gates': (7, 13, 2, 1)},
 {'full_name': 'Juxtaposition Cross of Interaction',
  'cross_type': 'Juxtaposition',
  'theme': 'Interaction',
  'variant': None,
  'gates': (7, 13, 23, 43)},
 {'full_name': 'Left Angle Cross of Masks 2',
  'cross_type': 'Left Angle',
  'theme': 'Masks',
  'variant': 2,
  'gates': (7, 13, 23, 43)},
 {'full_name': 'Right Angle Cross of Contagion 2',
  'cross_type': 'Right Angle',
  'theme': 'Contagion',
  'variant': 2,
  'gates': (8, 14, 30, 29)},
 {'full_name': 'Juxtaposition Cross of Contribution',
  'cross_type': 'Juxtaposition',
  'theme': 'Contribution',
  'variant': None,
  'gates': (8, 14, 55, 59)},
 {'full_name': 'Left Angle Cross of Uncertainty',
  'cross_type': 'Left Angle',
  'theme': 'Uncertainty',
  'variant': None,
  'gates': (8, 14, 55, 59)},
 {'full_name': 'Right Angle Cross of Planning 4',
  'cross_type': 'Right Angle',
  'theme': 'Planning',
  'variant': 4,
  'gates': (9, 16, 40, 37)},
 {'full_name': 'Juxtaposition Cross of Focus',
  'cross_type': 'Juxtaposition',
  'theme': 'Focus',
  'variant': None,
  'gates': (9, 16, 64, 63)},
 {'full_name': 'Left Angle Cross of Identification 2',
  'cross_type': 'Left Angle',
  'theme': 'Identification',
  'variant': 2,
  'gates': (9, 16, 64, 63)},
 {'full_name': 'Right Angle Cross of Vessel of Love 4',
  'cross_type': 'Right Angle',
  'theme': 'Vessel of Love',
  'variant': 4,
  'gates': (10, 15, 46, 25)},
 {'full_name': 'Juxtaposition Cross of Behavior',
  'cross_type': 'Juxtaposition',
  'theme': 'Behavior',
  'variant': None,
  'gates': (10, 15, 18, 17)},
 {'full_name': 'Left Angle Cross of Prevention 2',
  'cross_type': 'Left Angle',
  'theme': 'Prevention',
  'variant': 2,
  'gates': (10, 15, 18, 17)},
 {'full_name': 'Right Angle Cross of Eden 4',
  'cross_type': 'Right Angle',
  'theme': 'Eden',
  'variant': 4,
  'gates': (11, 12, 6, 36)},
 {'full_name': 'Juxtaposition Cross of Ideas',
  'cross_type': 'Juxtaposition',
  'theme': 'Ideas',
  'variant': None,
  'gates': (11, 12, 46, 25)},
 {'full_name': 'Left Angle Cross of Education 2',
  'cross_type': 'Left Angle',
  'theme': 'Education',
  'variant': 2,
  'gates': (11, 12, 46, 25)},
 {'full_name': 'Right Angle Cross of Eden 2',
  'cross_type': 'Right Angle',
  'theme': 'Eden',
  'variant': 2,
  'gates': (12, 11, 36, 6)},
 {'full_name': 'Juxtaposition Cross of Articulation',
  'cross_type': 'Juxtaposition',
  'theme': 'Articulation',
  'variant': None,
  'gates': (12, 11, 25, 46)},
 {'full_name': 'Left Angle Cross of Education',
  'cross_type': 'Left Angle',
  'theme': 'Education',
  'variant': None,
  'gates': (12, 11, 25, 46)},
 {'full_name': 'Right Angle Cross of the Sphinx',
  'cross_type': 'Right Angle',
  'theme': 'the Sphinx',
  'variant': None,
  'gates': (13, 7, 1, 2)},
 {'full_name': 'Juxtaposition Cross of Listening',
  'cross_type': 'Juxtaposition',
  'theme': 'Listening',
  'variant': None,
  'gates': (13, 7, 43, 23)},
 {'full_name': 'Left Angle Cross of Masks',
  'cross_type': 'Left Angle',
  'theme': 'Masks',
  'variant': None,
  'gates': (13, 7, 43, 23)},
 {'full_name': 'Right Angle Cross of Contagion 4',
  'cross_type': 'Right Angle',
  'theme': 'Contagion',
  'variant': 4,
  'gates': (14, 8, 29, 30)},
 {'full_name': 'Juxtaposition Cross of Empowering',
  'cross_type': 'Juxtaposition',
  'theme': 'Empowering',
  'variant': None,
  'gates': (14, 8, 59, 55)},
 {'full_name': 'Left Angle Cross of Uncertainty 2',
  'cross_type': 'Left Angle',
  'theme': 'Uncertainty',
  'variant': 2,
  'gates': (14, 8, 59, 55)},
 {'full_name': 'Right Angle Cross of the Vessel of Love 2',
  'cross_type': 'Right Angle',
  'theme': 'the Vessel of Love',
  'variant': 2,
  'gates': (15, 10, 25, 46)},
 {'full_name': 'Juxtaposition Cross of Extremes',
  'cross_type': 'Juxtaposition',
  'theme': 'Extremes',
  'variant': None,
  'gates': (15, 10, 17, 18)},
 {'full_name': 'Left Angle Cross of Prevention',
  'cross_type': 'Left Angle',
  'theme': 'Prevention',
  'variant': None,
  'gates': (15, 10, 17, 18)},
 {'full_name': 'Right Angle Cross of Planning 2',
  'cross_type': 'Right Angle',
  'theme': 'Planning',
  'variant': 2,
  'gates': (16, 9, 37, 40)},
 {'full_name': 'Juxtaposition Cross of Experimentation',
  'cross_type': 'Juxtaposition',
  'theme': 'Experimentation',
  'variant': None,
  'gates': (16, 9, 63, 64)},
 {'full_name': 'Left Angle Cross of Identification',
  'cross_type': 'Left Angle',
  'theme': 'Identification',
  'variant': None,
  'gates': (16, 9, 63, 64)},
 {'full_name': 'Right Angle Cross of Service',
  'cross_type': 'Right Angle',
  'theme': 'Service',
  'variant': None,
  'gates': (17, 18, 58, 52)},
 {'full_name': 'Juxtaposition Cross of Opinions',
  'cross_type': 'Juxtaposition',
  'theme': 'Opinions',
  'variant': None,
  'gates': (17, 18, 38, 39)},
 {'full_name': 'Left Angle Cross of Upheaval',
  'cross_type': 'Left Angle',
  'theme': 'Upheaval',
  'variant': None,
  'gates': (17, 18, 38, 39)},
 {'full_name': 'Right Angle Cross of Service 3',
  'cross_type': 'Right Angle',
  'theme': 'Service',
  'variant': 3,
  'gates': (18, 17, 52, 58)},
 {'full_name': 'Juxtaposition Cross of Correction',
  'cross_type': 'Juxtaposition',
  'theme': 'Correction',
  'variant': None,
  'gates': (18, 17, 39, 38)},
 {'full_name': 'Left Angle Cross of Upheaval 2',
  'cross_type': 'Left Angle',
  'theme': 'Upheaval',
  'variant': 2,
  'gates': (18, 17, 39, 38)},
 {'full_name': 'Right Angle Cross of the Four Ways 4',
  'cross_type': 'Right Angle',
  'theme': 'the Four Ways',
  'variant': 4,
  'gates': (19, 33, 44, 24)},
 {'full_name': 'Juxtaposition Cross of Need',
  'cross_type': 'Juxtaposition',
  'theme': 'Need',
  'variant': None,
  'gates': (19, 33, 1, 2)},
 {'full_name': 'Left Angle Cross of Refinement 2',
  'cross_type': 'Left Angle',
  'theme': 'Refinement',
  'variant': 2,
  'gates': (19, 33, 1, 2)},
 {'full_name': 'Right Angle Cross of the Sleeping Phoenix 2',
  'cross_type': 'Right Angle',
  'theme': 'the Sleeping Phoenix',
  'variant': 2,
  'gates': (20, 34, 55, 59)},
 {'full_name': 'Juxtaposition Cross of the Now',
  'cross_type': 'Juxtaposition',
  'theme': 'the Now',
  'variant': None,
  'gates': (20, 34, 37, 40)},
 {'full_name': 'Left Angle Cross of Duality',
  'cross_type': 'Left Angle',
  'theme': 'Duality',
  'variant': None,
  'gates': (20, 34, 37, 40)},
 {'full_name': 'Right Angle Cross of Tension',
  'cross_type': 'Right Angle',
  'theme': 'Tension',
  'variant': None,
  'gates': (21, 48, 38, 39)},
 {'full_name': 'Juxtaposition Cross of Control',
  'cross_type': 'Juxtaposition',
  'theme': 'Control',
  'variant': None,
  'gates': (21, 48, 54, 53)},
 {'full_name': 'Left Angle Cross of Endeavour',
  'cross_type': 'Left Angle',
  'theme': 'Endeavour',
  'variant': None,
  'gates': (21, 48, 54, 53)},
 {'full_name': 'Right Angle Cross of Rulership',
  'cross_type': 'Right Angle',
  'theme': 'Rulership',
  'variant': None,
  'gates': (22, 47, 26, 45)},
 {'full_name': 'Juxtaposition Cross of Grace',
  'cross_type': 'Juxtaposition',
  'theme': 'Grace',
  'variant': None,
  'gates': (22, 47, 11, 12)},
 {'full_name': 'Left Angle Cross of Informing',
  'cross_type': 'Left Angle',
  'theme': 'Informing',
  'variant': None,
  'gates': (22, 47, 11, 12)},
 {'full_name': 'Right Angle Cross of Explanation 2',
  'cross_type': 'Right Angle',
  'theme': 'Explanation',
  'variant': 2,
  'gates': (23, 43, 49, 4)},
 {'full_name': 'Juxtaposition Cross of Assimilation',
  'cross_type': 'Juxtaposition',
  'theme': 'Assimilation',
  'variant': None,
  'gates': (23, 43, 30, 29)},
 {'full_name': 'Left Angle Cross of Dedication',
  'cross_type': 'Left Angle',
  'theme': 'Dedication',
  'variant': None,
  'gates': (23, 43, 30, 29)},
 {'full_name': 'Right Angle Cross of the Four Ways',
  'cross_type': 'Right Angle',
  'theme': 'the Four Ways',
  'variant': None,
  'gates': (24, 44, 19, 33)},
 {'full_name': 'Juxtaposition Cross of Rationalization',
  'cross_type': 'Juxtaposition',
  'theme': 'Rationalization',
  'variant': None,
  'gates': (24, 44, 13, 7)},
 {'full_name': 'Left Angle Cross of Incarnation',
  'cross_type': 'Left Angle',
  'theme': 'Incarnation',
  'variant': None,
  'gates': (24, 44, 13, 7)},
 {'full_name': 'Right Angle Cross of the Vessel of Love',
  'cross_type': 'Right Angle',
  'theme': 'the Vessel of Love',
  'variant': None,
  'gates': (25, 46, 10, 15)},
 {'full_name': 'Juxtaposition Cross of Innocence',
  'cross_type': 'Juxtaposition',
  'theme': 'Innocence',
  'variant': None,
  'gates': (25, 46, 58, 52)},
 {'full_name': 'Left Angle Cross of Healing',
  'cross_type': 'Left Angle',
  'theme': 'Healing',
  'variant': None,
  'gates': (25, 46, 58, 52)},
 {'full_name': 'Right Angle Cross of Rulership 4',
  'cross_type': 'Right Angle',
  'theme': 'Rulership',
  'variant': 4,
  'gates': (26, 45, 47, 22)},
 {'full_name': 'Juxtaposition Cross of the Trickster',
  'cross_type': 'Juxtaposition',
  'theme': 'the Trickster',
  'variant': None,
  'gates': (26, 45, 6, 36)},
 {'full_name': 'Left Angle Cross of Confrontation 2',
  'cross_type': 'Left Angle',
  'theme': 'Confrontation',
  'variant': 2,
  'gates': (26, 45, 6, 36)},
 {'full_name': 'Right Angle Cross of the Unexpected',
  'cross_type': 'Right Angle',
  'theme': 'the Unexpected',
  'variant': None,
  'gates': (27, 28, 41, 31)},
 {'full_name': 'Juxtaposition Cross of Caring',
  'cross_type': 'Juxtaposition',
  'theme': 'Caring',
  'variant': None,
  'gates': (27, 28, 19, 33)},
 {'full_name': 'Left Angle Cross of Alignment',
  'cross_type': 'Left Angle',
  'theme': 'Alignment',
  'variant': None,
  'gates': (27, 28, 19, 33)},
 {'full_name': 'Right Angle Cross of the Unexpected 3',
  'cross_type': 'Right Angle',
  'theme': 'the Unexpected',
  'variant': 3,
  'gates': (28, 27, 31, 41)},
 {'full_name': 'Juxtaposition Cross of Risks',
  'cross_type': 'Juxtaposition',
  'theme': 'Risks',
  'variant': None,
  'gates': (28, 27, 33, 19)},
 {'full_name': 'Left Angle Cross of Alignment 2',
  'cross_type': 'Left Angle',
  'theme': 'Alignment',
  'variant': 2,
  'gates': (28, 27, 33, 19)},
 {'full_name': 'Right Angle Cross of Contagion 3',
  'cross_type': 'Right Angle',
  'theme': 'Contagion',
  'variant': 3,
  'gates': (29, 30, 8, 14)},
 {'full_name': 'Juxtaposition Cross of Commitment',
  'cross_type': 'Juxtaposition',
  'theme': 'Commitment',
  'variant': None,
  'gates': (29, 30, 20, 34)},
 {'full_name': 'Left Angle Cross of Industry 2',
  'cross_type': 'Left Angle',
  'theme': 'Industry',
  'variant': 2,
  'gates': (29, 30, 20, 34)},
 {'full_name': 'Right Angle Cross of Contagion',
  'cross_type': 'Right Angle',
  'theme': 'Contagion',
  'variant': None,
  'gates': (30, 29, 14, 8)},
 {'full_name': 'Juxtaposition Cross of Fates',
  'cross_type': 'Juxtaposition',
  'theme': 'Fates',
  'variant': None,
  'gates': (30, 29, 34, 20)},
 {'full_name': 'Left Angle Cross of Industry',
  'cross_type': 'Left Angle',
  'theme': 'Industry',
  'variant': None,
  'gates': (30, 29, 34, 20)},
 {'full_name': 'Right Angle Cross of the Unexpected 2',
  'cross_type': 'Right Angle',
  'theme': 'the Unexpected',
  'variant': 2,
  'gates': (31, 41, 27, 28)},
 {'full_name': 'Juxtaposition Cross of Influence',
  'cross_type': 'Juxtaposition',
  'theme': 'Influence',
  'variant': None,
  'gates': (31, 41, 24, 44)},
 {'full_name': 'Left Angle Cross of the Alpha',
  'cross_type': 'Left Angle',
  'theme': 'the Alpha',
  'variant': None,
  'gates': (31, 41, 24, 44)},
 {'full_name': 'Right Angle Cross of Maya 3',
  'cross_type': 'Right Angle',
  'theme': 'Maya',
  'variant': 3,
  'gates': (32, 42, 62, 61)},
 {'full_name': 'Juxtaposition Cross of Conservation',
  'cross_type': 'Juxtaposition',
  'theme': 'Conservation',
  'variant': None,
  'gates': (32, 42, 56, 60)},
 {'full_name': 'Left Angle Cross of Limitation 2',
  'cross_type': 'Left Angle',
  'theme': 'Limitation',
  'variant': 2,
  'gates': (32, 42, 56, 60)},
 {'full_name': 'Right Angle Cross of the Four Ways 2',
  'cross_type': 'Right Angle',
  'theme': 'the Four Ways',
  'variant': 2,
  'gates': (33, 19, 24, 44)},
 {'full_name': 'Juxtaposition Cross of Retreat',
  'cross_type': 'Juxtaposition',
  'theme': 'Retreat',
  'variant': None,
  'gates': (33, 19, 2, 1)},
 {'full_name': 'Left Angle Cross of Refinement',
  'cross_type': 'Left Angle',
  'theme': 'Refinement',
  'variant': None,
  'gates': (33, 19, 2, 1)},
 {'full_name': 'Right Angle Cross of the Sleeping Phoenix 4',
  'cross_type': 'Right Angle',
  'theme': 'the Sleeping Phoenix',
  'variant': 4,
  'gates': (34, 20, 59, 55)},
 {'full_name': 'Juxtaposition Cross of Power',
  'cross_type': 'Juxtaposition',
  'theme': 'Power',
  'variant': None,
  'gates': (34, 20, 40, 37)},
 {'full_name': 'Left Angle Cross of Duality 2',
  'cross_type': 'Left Angle',
  'theme': 'Duality',
  'variant': 2,
  'gates': (34, 20, 40, 37)},
 {'full_name': 'Right Angle Cross of Consciousness 2',
  'cross_type': 'Right Angle',
  'theme': 'Consciousness',
  'variant': 2,
  'gates': (35, 5, 63, 64)},
 {'full_name': 'Juxtaposition Cross of Experience',
  'cross_type': 'Juxtaposition',
  'theme': 'Experience',
  'variant': None,
  'gates': (35, 5, 22, 47)},
 {'full_name': 'Left Angle Cross of Separation',
  'cross_type': 'Left Angle',
  'theme': 'Separation',
  'variant': None,
  'gates': (35, 5, 22, 47)},
 {'full_name': 'Right Angle Cross of the Eden',
  'cross_type': 'Right Angle',
  'theme': 'the Eden',
  'variant': None,
  'gates': (36, 6, 11, 12)},
 {'full_name': 'Juxtaposition Cross of Crisis',
  'cross_type': 'Juxtaposition',
  'theme': 'Crisis',
  'variant': None,
  'gates': (36, 6, 10, 15)},
 {'full_name': 'Left Angle Cross of the Plane',
  'cross_type': 'Left Angle',
  'theme': 'the Plane',
  'variant': None,
  'gates': (36, 6, 10, 15)},
 {'full_name': 'Right Angle Cross of Planning',
  'cross_type': 'Right Angle',
  'theme': 'Planning',
  'variant': None,
  'gates': (37, 40, 9, 16)},
 {'full_name': 'Juxtaposition Cross of Bargains',
  'cross_type': 'Juxtaposition',
  'theme': 'Bargains',
  'variant': None,
  'gates': (37, 40, 5, 35)},
 {'full_name': 'Left Angle Cross of Migration',
  'cross_type': 'Left Angle',
  'theme': 'Migration',
  'variant': None,
  'gates': (37, 40, 5, 35)},
 {'full_name': 'Right Angle Cross of Tension 4',
  'cross_type': 'Right Angle',
  'theme': 'Tension',
  'variant': 4,
  'gates': (38, 39, 48, 21)},
 {'full_name': 'Juxtaposition Cross of Opposition',
  'cross_type': 'Juxtaposition',
  'theme': 'Opposition',
  'variant': None,
  'gates': (38, 39, 57, 51)},
 {'full_name': 'Left Angle Cross of Individualism 2',
  'cross_type': 'Left Angle',
  'theme': 'Individualism',
  'variant': 2,
  'gates': (38, 39, 57, 51)},
 {'full_name': 'Right Angle Cross of Tension 2',
  'cross_type': 'Right Angle',
  'theme': 'Tension',
  'variant': 2,
  'gates': (39, 38, 21, 48)},
 {'full_name': 'Juxtaposition Cross of Provocation',
  'cross_type': 'Juxtaposition',
  'theme': 'Provocation',
  'variant': None,
  'gates': (39, 38, 51, 57)},
 {'full_name': 'Left Angle Cross of Individualism',
  'cross_type': 'Left Angle',
  'theme': 'Individualism',
  'variant': None,
  'gates': (39, 38, 51, 57)},
 {'full_name': 'Right Angle Cross of Planning 3',
  'cross_type': 'Right Angle',
  'theme': 'Planning',
  'variant': 3,
  'gates': (40, 37, 16, 9)},
 {'full_name': 'Juxtaposition Cross of Denial',
  'cross_type': 'Juxtaposition',
  'theme': 'Denial',
  'variant': None,
  'gates': (40, 37, 35, 5)},
 {'full_name': 'Left Angle Cross of Migration 2',
  'cross_type': 'Left Angle',
  'theme': 'Migration',
  'variant': 2,
  'gates': (40, 37, 35, 5)},
 {'full_name': 'Right Angle Cross of the Unexpected 4',
  'cross_type': 'Right Angle',
  'theme': 'the Unexpected',
  'variant': 4,
  'gates': (41, 31, 28, 27)},
 {'full_name': 'Juxtaposition Cross of Fantasy',
  'cross_type': 'Juxtaposition',
  'theme': 'Fantasy',
  'variant': None,
  'gates': (41, 31, 44, 24)},
 {'full_name': 'Left Angle Cross of the Alpha 2',
  'cross_type': 'Left Angle',
  'theme': 'the Alpha',
  'variant': 2,
  'gates': (41, 31, 44, 24)},
 {'full_name': 'Right Angle Cross of Maya',
  'cross_type': 'Right Angle',
  'theme': 'Maya',
  'variant': None,
  'gates': (42, 32, 61, 62)},
 {'full_name': 'Juxtaposition Cross of Completion',
  'cross_type': 'Juxtaposition',
  'theme': 'Completion',
  'variant': None,
  'gates': (42, 32, 60, 56)},
 {'full_name': 'Left Angle Cross of Limitation',
  'cross_type': 'Left Angle',
  'theme': 'Limitation',
  'variant': None,
  'gates': (42, 32, 60, 56)},
 {'full_name': 'Right Angle Cross of Explanation 4',
  'cross_type': 'Right Angle',
  'theme': 'Explanation',
  'variant': 4,
  'gates': (43, 23, 4, 49)},
 {'full_name': 'Juxtaposition Cross of Insight',
  'cross_type': 'Juxtaposition',
  'theme': 'Insight',
  'variant': None,
  'gates': (43, 23, 29, 30)},
 {'full_name': 'Left Angle Cross of Dedication 2',
  'cross_type': 'Left Angle',
  'theme': 'Dedication',
  'variant': 2,
  'gates': (43, 23, 29, 30)},
 {'full_name': 'Right Angle Cross of the Four Ways 3',
  'cross_type': 'Right Angle',
  'theme': 'the Four Ways',
  'variant': 3,
  'gates': (44, 24, 33, 19)},
 {'full_name': 'Juxtaposition Cross of Alertness',
  'cross_type': 'Juxtaposition',
  'theme': 'Alertness',
  'variant': None,
  'gates': (44, 24, 7, 13)},
 {'full_name': 'Left Angle Cross of Incarnation 2',
  'cross_type': 'Left Angle',
  'theme': 'Incarnation',
  'variant': 2,
  'gates': (44, 24, 7, 13)},
 {'full_name': 'Right Angle Cross of Rulership 2',
  'cross_type': 'Right Angle',
  'theme': 'Rulership',
  'variant': 2,
  'gates': (45, 26, 22, 47)},
 {'full_name': 'Juxtaposition Cross of Possession',
  'cross_type': 'Juxtaposition',
  'theme': 'Possession',
  'variant': None,
  'gates': (45, 26, 36, 6)},
 {'full_name': 'Left Angle Cross of Confrontation',
  'cross_type': 'Left Angle',
  'theme': 'Confrontation',
  'variant': None,
  'gates': (45, 26, 36, 6)},
 {'full_name': 'Right Angle Cross of the Vessel of Love 3',
  'cross_type': 'Right Angle',
  'theme': 'the Vessel of Love',
  'variant': 3,
  'gates': (46, 25, 15, 10)},
 {'full_name': 'Juxtaposition Cross of Serendipity',
  'cross_type': 'Juxtaposition',
  'theme': 'Serendipity',
  'variant': None,
  'gates': (46, 25, 52, 58)},
 {'full_name': 'Left Angle Cross of Healing 2',
  'cross_type': 'Left Angle',
  'theme': 'Healing',
  'variant': 2,
  'gates': (46, 25, 52, 58)},
 {'full_name': 'Right Angle Cross of Rulership 3',
  'cross_type': 'Right Angle',
  'theme': 'Rulership',
  'variant': 3,
  'gates': (47, 22, 45, 26)},
 {'full_name': 'Juxtaposition Cross of Oppression',
  'cross_type': 'Juxtaposition',
  'theme': 'Oppression',
  'variant': None,
  'gates': (47, 22, 12, 11)},
 {'full_name': 'Left Angle Cross of Informing 2',
  'cross_type': 'Left Angle',
  'theme': 'Informing',
  'variant': 2,
  'gates': (47, 22, 12, 11)},
 {'full_name': 'Right Angle Cross of Tension 3',
  'cross_type': 'Right Angle',
  'theme': 'Tension',
  'variant': 3,
  'gates': (48, 21, 39, 38)},
 {'full_name': 'Juxtaposition Cross of Depth',
  'cross_type': 'Juxtaposition',
  'theme': 'Depth',
  'variant': None,
  'gates': (48, 21, 53, 54)},
 {'full_name': 'Left Angle Cross of Endeavour 2',
  'cross_type': 'Left Angle',
  'theme': 'Endeavour',
  'variant': 2,
  'gates': (48, 21, 53, 54)},
 {'full_name': 'Right Angle Cross of Explanation',
  'cross_type': 'Right Angle',
  'theme': 'Explanation',
  'variant': None,
  'gates': (49, 4, 43, 23)},
 {'full_name': 'Juxtaposition Cross of Principles',
  'cross_type': 'Juxtaposition',
  'theme': 'Principles',
  'variant': None,
  'gates': (49, 4, 14, 8)},
 {'full_name': 'Left Angle Cross of Revolution',
  'cross_type': 'Left Angle',
  'theme': 'Revolution',
  'variant': None,
  'gates': (49, 4, 14, 8)},
 {'full_name': 'Right Angle Cross of Laws 3',
  'cross_type': 'Right Angle',
  'theme': 'Laws',
  'variant': 3,
  'gates': (50, 3, 56, 60)},
 {'full_name': 'Juxtaposition Cross of Values',
  'cross_type': 'Juxtaposition',
  'theme': 'Values',
  'variant': None,
  'gates': (50, 3, 31, 41)},
 {'full_name': 'Left Angle Cross of Wishes 2',
  'cross_type': 'Left Angle',
  'theme': 'Wishes',
  'variant': 2,
  'gates': (50, 3, 31, 41)},
 {'full_name': 'Right Angle Cross of Penetration',
  'cross_type': 'Right Angle',
  'theme': 'Penetration',
  'variant': None,
  'gates': (51, 57, 54, 53)},
 {'full_name': 'Juxtaposition Cross of Shock',
  'cross_type': 'Juxtaposition',
  'theme': 'Shock',
  'variant': None,
  'gates': (51, 57, 61, 62)},
 {'full_name': 'Left Angle Cross of the Clarion',
  'cross_type': 'Left Angle',
  'theme': 'the Clarion',
  'variant': None,
  'gates': (51, 57, 61, 62)},
 {'full_name': 'Right Angle Cross of Service 2',
  'cross_type': 'Right Angle',
  'theme': 'Service',
  'variant': 2,
  'gates': (52, 58, 17, 18)},
 {'full_name': 'Juxtaposition Cross of Stillness',
  'cross_type': 'Juxtaposition',
  'theme': 'Stillness',
  'variant': None,
  'gates': (52, 58, 21, 48)},
 {'full_name': 'Left Angle Cross of Demands',
  'cross_type': 'Left Angle',
  'theme': 'Demands',
  'variant': None,
  'gates': (52, 58, 21, 48)},
 {'full_name': 'Right Angle Cross of Penetration 2',
  'cross_type': 'Right Angle',
  'theme': 'Penetration',
  'variant': 2,
  'gates': (53, 54, 51, 57)},
 {'full_name': 'Juxtaposition Cross of Beginnings',
  'cross_type': 'Juxtaposition',
  'theme': 'Beginnings',
  'variant': None,
  'gates': (53, 54, 42, 32)},
 {'full_name': 'Left Angle Cross of Cycles',
  'cross_type': 'Left Angle',
  'theme': 'Cycles',
  'variant': None,
  'gates': (53, 54, 42, 32)},
 {'full_name': 'Right Angle Cross of Penetration 4',
  'cross_type': 'Right Angle',
  'theme': 'Penetration',
  'variant': 4,
  'gates': (54, 53, 57, 51)},
 {'full_name': 'Juxtaposition Cross of Ambition',
  'cross_type': 'Juxtaposition',
  'theme': 'Ambition',
  'variant': None,
  'gates': (54, 53, 32, 42)},
 {'full_name': 'Left Angle Cross of Cycles 2',
  'cross_type': 'Left Angle',
  'theme': 'Cycles',
  'variant': 2,
  'gates': (54, 53, 32, 42)},
 {'full_name': 'Right Angle Cross of the Sleeping Phoenix',
  'cross_type': 'Right Angle',
  'theme': 'the Sleeping Phoenix',
  'variant': None,
  'gates': (55, 59, 34, 20)},
 {'full_name': 'Juxtaposition Cross of Moods',
  'cross_type': 'Juxtaposition',
  'theme': 'Moods',
  'variant': None,
  'gates': (55, 59, 9, 16)},
 {'full_name': 'Left Angle Cross of Spirit',
  'cross_type': 'Left Angle',
  'theme': 'Spirit',
  'variant': None,
  'gates': (55, 59, 9, 16)},
 {'full_name': 'Right Angle Cross of Laws 2',
  'cross_type': 'Right Angle',
  'theme': 'Laws',
  'variant': 2,
  'gates': (56, 60, 3, 50)},
 {'full_name': 'Juxtaposition Cross of Stimulation',
  'cross_type': 'Juxtaposition',
  'theme': 'Stimulation',
  'variant': None,
  'gates': (56, 60, 27, 28)},
 {'full_name': 'Left Angle Cross of Distraction',
  'cross_type': 'Left Angle',
  'theme': 'Distraction',
  'variant': None,
  'gates': (56, 60, 27, 28)},
 {'full_name': 'Right Angle Cross of Penetration 3',
  'cross_type': 'Right Angle',
  'theme': 'Penetration',
  'variant': 3,
  'gates': (57, 51, 53, 54)},
 {'full_name': 'Juxtaposition Cross of Intuition',
  'cross_type': 'Juxtaposition',
  'theme': 'Intuition',
  'variant': None,
  'gates': (57, 51, 62, 61)},
 {'full_name': 'Left Angle Cross of the Clarion 2',
  'cross_type': 'Left Angle',
  'theme': 'the Clarion',
  'variant': 2,
  'gates': (57, 51, 62, 61)},
 {'full_name': 'Right Angle Cross of Service 4',
  'cross_type': 'Right Angle',
  'theme': 'Service',
  'variant': 4,
  'gates': (58, 52, 18, 17)},
 {'full_name': 'Juxtaposition Cross of Vitality',
  'cross_type': 'Juxtaposition',
  'theme': 'Vitality',
  'variant': None,
  'gates': (58, 52, 48, 21)},
 {'full_name': 'Left Angle Cross of Demands 2',
  'cross_type': 'Left Angle',
  'theme': 'Demands',
  'variant': 2,
  'gates': (58, 52, 48, 21)},
 {'full_name': 'Right Angle Cross of the Sleeping Phoenix 3',
  'cross_type': 'Right Angle',
  'theme': 'the Sleeping Phoenix',
  'variant': 3,
  'gates': (59, 55, 20, 34)},
 {'full_name': 'Juxtaposition Cross of Strategy',
  'cross_type': 'Juxtaposition',
  'theme': 'Strategy',
  'variant': None,
  'gates': (59, 55, 16, 9)},
 {'full_name': 'Left Angle Cross of Spirit 2',
  'cross_type': 'Left Angle',
  'theme': 'Spirit',
  'variant': 2,
  'gates': (59, 55, 16, 9)},
 {'full_name': 'Right Angle Cross of Laws 4',
  'cross_type': 'Right Angle',
  'theme': 'Laws',
  'variant': 4,
  'gates': (60, 56, 50, 3)},
 {'full_name': 'Juxtaposition Cross of Limitation',
  'cross_type': 'Juxtaposition',
  'theme': 'Limitation',
  'variant': None,
  'gates': (60, 56, 28, 27)},
 {'full_name': 'Left Angle Cross of Distraction 2',
  'cross_type': 'Left Angle',
  'theme': 'Distraction',
  'variant': 2,
  'gates': (60, 56, 28, 27)},
 {'full_name': 'Right Angle Cross of Maya 4',
  'cross_type': 'Right Angle',
  'theme': 'Maya',
  'variant': 4,
  'gates': (61, 62, 32, 42)},
 {'full_name': 'Juxtaposition Cross of Thinking',
  'cross_type': 'Juxtaposition',
  'theme': 'Thinking',
  'variant': None,
  'gates': (61, 62, 50, 3)},
 {'full_name': 'Left Angle Cross of Obscuration 2',
  'cross_type': 'Left Angle',
  'theme': 'Obscuration',
  'variant': 2,
  'gates': (61, 62, 50, 3)},
 {'full_name': 'Right Angle Cross of Maya 2',
  'cross_type': 'Right Angle',
  'theme': 'Maya',
  'variant': 2,
  'gates': (62, 61, 42, 32)},
 {'full_name': 'Juxtaposition Cross of Detail',
  'cross_type': 'Juxtaposition',
  'theme': 'Detail',
  'variant': None,
  'gates': (62, 61, 3, 50)},
 {'full_name': 'Left Angle Cross of Obscuration',
  'cross_type': 'Left Angle',
  'theme': 'Obscuration',
  'variant': None,
  'gates': (62, 61, 3, 50)},
 {'full_name': 'Right Angle Cross of Consciousness',
  'cross_type': 'Right Angle',
  'theme': 'Consciousness',
  'variant': None,
  'gates': (63, 64, 5, 35)},
 {'full_name': 'Juxtaposition Cross of Doubts',
  'cross_type': 'Juxtaposition',
  'theme': 'Doubts',
  'variant': None,
  'gates': (63, 64, 26, 45)},
 {'full_name': 'Left Angle Cross of Dominion',
  'cross_type': 'Left Angle',
  'theme': 'Dominion',
  'variant': None,
  'gates': (63, 64, 26, 45)},
 {'full_name': 'Right Angle Cross of Consciousness 3',
  'cross_type': 'Right Angle',
  'theme': 'Consciousness',
  'variant': 3,
  'gates': (64, 63, 35, 5)},
 {'full_name': 'Juxtaposition Cross of Confusion',
  'cross_type': 'Juxtaposition',
  'theme': 'Confusion',
  'variant': None,
  'gates': (64, 63, 45, 26)},
 {'full_name': 'Left Angle Cross of Dominion 2',
  'cross_type': 'Left Angle',
  'theme': 'Dominion',
  'variant': 2,
  'gates': (64, 63, 45, 26)}]

HD_INCARNATION_CROSS_FULL_NAMES = ['Right Angle Cross of the Sphinx 4',
 'Juxtaposition Cross of Self-Expression',
 'Left Angle Cross of Defiance 2',
 'Right Angle Cross of the Sphinx 2',
 'Juxtaposition Cross of the Driver',
 'Left Angle Cross of Defiance',
 'Right Angle Cross of Laws',
 'Juxtaposition Cross of Mutation',
 'Left Angle Cross of Wishes',
 'Right Angle Cross of Explanation 3',
 'Juxtaposition Cross of Formulization',
 'Left Angle Cross of Revolution 2',
 'Right Angle Cross of Consciousness 4',
 'Juxtaposition Cross of Habits',
 'Left Angle Cross of Separation 2',
 'Right Angle Cross of Eden 3',
 'Juxtaposition Cross of Conflict',
 'Left Angle Cross of the Plane 2',
 'Right Angle Cross of the Sphinx 3',
 'Juxtaposition Cross of Interaction',
 'Left Angle Cross of Masks 2',
 'Right Angle Cross of Contagion 2',
 'Juxtaposition Cross of Contribution',
 'Left Angle Cross of Uncertainty',
 'Right Angle Cross of Planning 4',
 'Juxtaposition Cross of Focus',
 'Left Angle Cross of Identification 2',
 'Right Angle Cross of Vessel of Love 4',
 'Juxtaposition Cross of Behavior',
 'Left Angle Cross of Prevention 2',
 'Right Angle Cross of Eden 4',
 'Juxtaposition Cross of Ideas',
 'Left Angle Cross of Education 2',
 'Right Angle Cross of Eden 2',
 'Juxtaposition Cross of Articulation',
 'Left Angle Cross of Education',
 'Right Angle Cross of the Sphinx',
 'Juxtaposition Cross of Listening',
 'Left Angle Cross of Masks',
 'Right Angle Cross of Contagion 4',
 'Juxtaposition Cross of Empowering',
 'Left Angle Cross of Uncertainty 2',
 'Right Angle Cross of the Vessel of Love 2',
 'Juxtaposition Cross of Extremes',
 'Left Angle Cross of Prevention',
 'Right Angle Cross of Planning 2',
 'Juxtaposition Cross of Experimentation',
 'Left Angle Cross of Identification',
 'Right Angle Cross of Service',
 'Juxtaposition Cross of Opinions',
 'Left Angle Cross of Upheaval',
 'Right Angle Cross of Service 3',
 'Juxtaposition Cross of Correction',
 'Left Angle Cross of Upheaval 2',
 'Right Angle Cross of the Four Ways 4',
 'Juxtaposition Cross of Need',
 'Left Angle Cross of Refinement 2',
 'Right Angle Cross of the Sleeping Phoenix 2',
 'Juxtaposition Cross of the Now',
 'Left Angle Cross of Duality',
 'Right Angle Cross of Tension',
 'Juxtaposition Cross of Control',
 'Left Angle Cross of Endeavour',
 'Right Angle Cross of Rulership',
 'Juxtaposition Cross of Grace',
 'Left Angle Cross of Informing',
 'Right Angle Cross of Explanation 2',
 'Juxtaposition Cross of Assimilation',
 'Left Angle Cross of Dedication',
 'Right Angle Cross of the Four Ways',
 'Juxtaposition Cross of Rationalization',
 'Left Angle Cross of Incarnation',
 'Right Angle Cross of the Vessel of Love',
 'Juxtaposition Cross of Innocence',
 'Left Angle Cross of Healing',
 'Right Angle Cross of Rulership 4',
 'Juxtaposition Cross of the Trickster',
 'Left Angle Cross of Confrontation 2',
 'Right Angle Cross of the Unexpected',
 'Juxtaposition Cross of Caring',
 'Left Angle Cross of Alignment',
 'Right Angle Cross of the Unexpected 3',
 'Juxtaposition Cross of Risks',
 'Left Angle Cross of Alignment 2',
 'Right Angle Cross of Contagion 3',
 'Juxtaposition Cross of Commitment',
 'Left Angle Cross of Industry 2',
 'Right Angle Cross of Contagion',
 'Juxtaposition Cross of Fates',
 'Left Angle Cross of Industry',
 'Right Angle Cross of the Unexpected 2',
 'Juxtaposition Cross of Influence',
 'Left Angle Cross of the Alpha',
 'Right Angle Cross of Maya 3',
 'Juxtaposition Cross of Conservation',
 'Left Angle Cross of Limitation 2',
 'Right Angle Cross of the Four Ways 2',
 'Juxtaposition Cross of Retreat',
 'Left Angle Cross of Refinement',
 'Right Angle Cross of the Sleeping Phoenix 4',
 'Juxtaposition Cross of Power',
 'Left Angle Cross of Duality 2',
 'Right Angle Cross of Consciousness 2',
 'Juxtaposition Cross of Experience',
 'Left Angle Cross of Separation',
 'Right Angle Cross of the Eden',
 'Juxtaposition Cross of Crisis',
 'Left Angle Cross of the Plane',
 'Right Angle Cross of Planning',
 'Juxtaposition Cross of Bargains',
 'Left Angle Cross of Migration',
 'Right Angle Cross of Tension 4',
 'Juxtaposition Cross of Opposition',
 'Left Angle Cross of Individualism 2',
 'Right Angle Cross of Tension 2',
 'Juxtaposition Cross of Provocation',
 'Left Angle Cross of Individualism',
 'Right Angle Cross of Planning 3',
 'Juxtaposition Cross of Denial',
 'Left Angle Cross of Migration 2',
 'Right Angle Cross of the Unexpected 4',
 'Juxtaposition Cross of Fantasy',
 'Left Angle Cross of the Alpha 2',
 'Right Angle Cross of Maya',
 'Juxtaposition Cross of Completion',
 'Left Angle Cross of Limitation',
 'Right Angle Cross of Explanation 4',
 'Juxtaposition Cross of Insight',
 'Left Angle Cross of Dedication 2',
 'Right Angle Cross of the Four Ways 3',
 'Juxtaposition Cross of Alertness',
 'Left Angle Cross of Incarnation 2',
 'Right Angle Cross of Rulership 2',
 'Juxtaposition Cross of Possession',
 'Left Angle Cross of Confrontation',
 'Right Angle Cross of the Vessel of Love 3',
 'Juxtaposition Cross of Serendipity',
 'Left Angle Cross of Healing 2',
 'Right Angle Cross of Rulership 3',
 'Juxtaposition Cross of Oppression',
 'Left Angle Cross of Informing 2',
 'Right Angle Cross of Tension 3',
 'Juxtaposition Cross of Depth',
 'Left Angle Cross of Endeavour 2',
 'Right Angle Cross of Explanation',
 'Juxtaposition Cross of Principles',
 'Left Angle Cross of Revolution',
 'Right Angle Cross of Laws 3',
 'Juxtaposition Cross of Values',
 'Left Angle Cross of Wishes 2',
 'Right Angle Cross of Penetration',
 'Juxtaposition Cross of Shock',
 'Left Angle Cross of the Clarion',
 'Right Angle Cross of Service 2',
 'Juxtaposition Cross of Stillness',
 'Left Angle Cross of Demands',
 'Right Angle Cross of Penetration 2',
 'Juxtaposition Cross of Beginnings',
 'Left Angle Cross of Cycles',
 'Right Angle Cross of Penetration 4',
 'Juxtaposition Cross of Ambition',
 'Left Angle Cross of Cycles 2',
 'Right Angle Cross of the Sleeping Phoenix',
 'Juxtaposition Cross of Moods',
 'Left Angle Cross of Spirit',
 'Right Angle Cross of Laws 2',
 'Juxtaposition Cross of Stimulation',
 'Left Angle Cross of Distraction',
 'Right Angle Cross of Penetration 3',
 'Juxtaposition Cross of Intuition',
 'Left Angle Cross of the Clarion 2',
 'Right Angle Cross of Service 4',
 'Juxtaposition Cross of Vitality',
 'Left Angle Cross of Demands 2',
 'Right Angle Cross of the Sleeping Phoenix 3',
 'Juxtaposition Cross of Strategy',
 'Left Angle Cross of Spirit 2',
 'Right Angle Cross of Laws 4',
 'Juxtaposition Cross of Limitation',
 'Left Angle Cross of Distraction 2',
 'Right Angle Cross of Maya 4',
 'Juxtaposition Cross of Thinking',
 'Left Angle Cross of Obscuration 2',
 'Right Angle Cross of Maya 2',
 'Juxtaposition Cross of Detail',
 'Left Angle Cross of Obscuration',
 'Right Angle Cross of Consciousness',
 'Juxtaposition Cross of Doubts',
 'Left Angle Cross of Dominion',
 'Right Angle Cross of Consciousness 3',
 'Juxtaposition Cross of Confusion',
 'Left Angle Cross of Dominion 2']

HD_INCARNATION_CROSS_THEMES = ['Alertness',
 'Alignment',
 'Ambition',
 'Articulation',
 'Assimilation',
 'Bargains',
 'Beginnings',
 'Behavior',
 'Caring',
 'Commitment',
 'Completion',
 'Conflict',
 'Confrontation',
 'Confusion',
 'Consciousness',
 'Conservation',
 'Contagion',
 'Contribution',
 'Control',
 'Correction',
 'Crisis',
 'Cycles',
 'Dedication',
 'Defiance',
 'Demands',
 'Denial',
 'Depth',
 'Detail',
 'Distraction',
 'Dominion',
 'Doubts',
 'Duality',
 'Eden',
 'Education',
 'Empowering',
 'Endeavour',
 'Experience',
 'Experimentation',
 'Explanation',
 'Extremes',
 'Fantasy',
 'Fates',
 'Focus',
 'Formulization',
 'Grace',
 'Habits',
 'Healing',
 'Ideas',
 'Identification',
 'Incarnation',
 'Individualism',
 'Industry',
 'Influence',
 'Informing',
 'Innocence',
 'Insight',
 'Interaction',
 'Intuition',
 'Laws',
 'Limitation',
 'Listening',
 'Masks',
 'Maya',
 'Migration',
 'Moods',
 'Mutation',
 'Need',
 'Obscuration',
 'Opinions',
 'Opposition',
 'Oppression',
 'Penetration',
 'Planning',
 'Possession',
 'Power',
 'Prevention',
 'Principles',
 'Provocation',
 'Rationalization',
 'Refinement',
 'Retreat',
 'Revolution',
 'Risks',
 'Rulership',
 'Self-Expression',
 'Separation',
 'Serendipity',
 'Service',
 'Shock',
 'Spirit',
 'Stillness',
 'Stimulation',
 'Strategy',
 'Tension',
 'Thinking',
 'Uncertainty',
 'Upheaval',
 'Values',
 'Vessel of Love',
 'Vitality',
 'Wishes',
 'the Alpha',
 'the Clarion',
 'the Driver',
 'the Eden',
 'the Four Ways',
 'the Now',
 'the Plane',
 'the Sleeping Phoenix',
 'the Sphinx',
 'the Trickster',
 'the Unexpected',
 'the Vessel of Love']

def find_cross_by_name(name: str):
    """Case-insensitive exact match on the full chart label."""
    name_cf = name.casefold()
    for item in HD_INCARNATION_CROSSES:
        if item["full_name"].casefold() == name_cf:
            return item
    return None


def find_crosses_by_theme(theme: str):
    """Case-insensitive match on thematic name, ignoring numeric variant."""
    theme_cf = theme.casefold()
    return [item for item in HD_INCARNATION_CROSSES if item["theme"].casefold() == theme_cf]


def find_crosses_by_gates(personality_sun: int, personality_earth: int, design_sun: int, design_earth: int):
    """Return any cross labels matching the 4-gate signature."""
    gates = (personality_sun, personality_earth, design_sun, design_earth)
    return [item for item in HD_INCARNATION_CROSSES if tuple(item["gates"]) == gates]
