TRAITS = {

    "does comedy well": {
        "name": "does comedy well",
        "signs": {},
        "antisigns": {},
        "houses": {
            "11": 4,
            "7": -3,
        },
        "antihouses": {
            "12": 7,
            "9": 4, #dogmatic, serious - found in 'most solemn gem suns'
        },
        "bodies": {},
        "antibodies": {}, #Saturn is in 'most solemn' but not 'humorless'.
        "nakshatras": {
            "Magha": 4,
            "Rohini": 3,
            "Bharani": -4, #never tries to be funny
        },
        "antinakshatras": {
            "Ardra": -6 #never 'humorless', but often 'solemn'/caustic
        },
        "positions": {
            "Sun in Gemini": 4,
            "Sun in H10": 5,
            "Mercury in Scorpio": -3,
            "Mercury in Capricorn": -3,
            "Saturn in H11": 5,
            "Uranus in Virgo": 5,
            #"Neptune in Taurus": -1,
            #"Neptune in Scorpio": 7,
            #"Neptune in Sagittarius": 4,
            "Neptune in H3": 4,
            #"Pluto in Virgo": 7,
            #"Pluto in Libra": 5,
            #"Pluto in Sagittarius": -3,
            "Ceres in Leo": 3,
            "Ceres in H5": 3,
            "Gemini in H11": 4,
            "Sagittarius in H5": 4,
            "True Lilith in H7": -5,
        },
        "antipositions": {
            "Sun in Virgo": 5,
            "Sun in Aquarius": -5,
#            "Moon in Sagittarius": 5, #Decan 3 (Leo/Sun) is twice as hilarious as Decan 1 (Sag/Jupiter).
            "Mercury in Libra": 6,
            "Mars in Scorpio": 5,
            "Saturn in Cancer": -5,
#            "Uranus in Cancer": 6,
#            "Pluto in Leo": 10,
#            "Pluto in Libra": -7,
            "Chiron in Aries": -9,
            "Chiron in Sagittarius": 7,
            "Ceres in H2": -6,
            "Ceres in H3": 8,
            "Juno in Leo": 4,
            "Juno in H10": 8,
            "Part of Fortune in H5": -6,
            "True Lilith in H10": 7,
            "True Lilith in H12": 6
        },
        "aspects": {
            "Neptune sextile Pluto": 12,
            "Chiron opposition Uranus": 7,
            #"Chiron trine Neptune": 4,
            "Chiron opposition Pluto": 3,
            "Pluto conjunction Uranus": 5,
            #"Neptune sextile Uranus": 3,
            "Ceres conjunction Juno": 3,
            "Uranus sextile Vesta": 3,
            "IC opposition Jupiter": 3,
            "Jupiter conjunction MC": 3,
            "AS conjunction Pluto": 3,
            "DS opposition Pluto": 3,
            "DS quincunx Mars": 3,
            "DS quincunx Saturn": 3,
            "AS trine Pallas": -3,
        },
        "antiaspects": {
            #these came over from 'solemn gem suns'
            "Neptune opposition Sun": 18, #shows up in funny charts, shows up WAY more in solemn charts
            "Chiron trine Neptune": 17, #shows up in funny charts but shows up MORE in solemn charts
            "Juno conjunction Pallas": 17,
            "AS trine Ceres": 17,
            "Mercury square Pallas": 16,
            "Juno trine Sun": 15,
            "Pluto trine Saturn": 14,
            "Moon square Saturn": 12,
            #these came over from 'humorless'
            "Pluto square Sun": 12,
            "Chiron opposition Uranus": -8,
            "Ceres square True Lilith": 6,
            "Juno sextile Sun": 6,
            "Mars trine Pallas": 5,
            "Part of Fortune trine True Lilith": 5,
            "Uranus square Venus": 5,
            "Ceres square Uranus": 5,
            "Mars trine Saturn": 4,
            "Moon sextile True Lilith": 5,
            "Rahu trine Uranus": 5,
            "IC square Mars": 9,
            "MC square Mars": 9,
            "Juno quincunx Rahu": 6,
            "Pallas conjunction Sun": 4,
            "Chiron trine Pluto": 4,
            "Juno semisextile Ketu": 5,
            "Mars quincunx Uranus": 5,
            "Mars semisquare Venus": 3,
            "Ceres sesquiquadrate Moon": 4,
            "Juno semisquare Neptune": 4,
            "Mars biquintile Pluto": 4,
            "Mercury sesquiquadrate Pluto": 4,
            "Pluto semisextile Venus": 4,
            "Chiron biquintile Moon": 3,
            "Chiron semisextile Part of Fortune": 3,
            "DS quincunx Jupiter": 4,
            "Juno quintile Venus": 3,
            "Juno semisextile Mercury": 3,
            "Ketu quincunx Mars": 3,
            "Ketu sesquiquadrate Pallas": 3,
            "Mars semisquare Pallas": 3,
            "Pallas semisquare Rahu": 3,
            "Pallas sesquiquadrate Pluto": 3,
            "Sun biquintile True Lilith": 3,
            "Chiron quintile Pluto": 3,
            "Jupiter semisquare Pallas": 3,
            "Jupiter sesquiquadrate Mercury": 3,
            "Ketu quintile Mars": 3,
            "Mars sesquiquadrate True Lilith": 3,
            "Mercury biquintile Rahu": 3,
            "Mercury semisquare Uranus": 3,
            "Moon biquintile Pallas": 3,
            "Moon sesquiquadrate Pluto": 3,
            "Neptune semisextile Sun": 3,
            "Pallas semisquare Venus": 3,
            "Part of Fortune quintile Pluto": 3,
            "AS quintile Rahu": 4,
            "IC sesquiquadrate Sun": 4,
            "Mars conjunction Mercury": -5,
            "Mars semisextile Rahu": 3,
            "MC semisquare Sun": 4,
            "AS semisextile Mercury": 4,
            "AS sesquiquadrate Vesta": 3,
            "Chiron quintile DS": 3,
            "Chiron semisquare Neptune": 3,
            "DS quintile Uranus": 3,
            "DS semisquare Vesta": 3,
            "IC quincunx Neptune": 3,
            "Jupiter quintile MC": 3,
            "Jupiter square Pallas": -4,
            "Ketu square Neptune": -5,
            "Mars conjunction Sun": -4,
            "Neptune square Rahu": -5,
            "Ceres conjunction Juno": -5,
            "Ceres sextile Saturn": -4,
            "Ceres square Venus": -4,
            "DS trine Saturn": -6,
            "Juno conjunction Pluto": -5,
            "IC trine Pallas": -7,
            "Ketu square Sun": -6,
            "MC trine Neptune": -8,
            "Mercury conjunction Vesta": -5,
            "Rahu square Sun": -6
        },
        "gates": {
            34: 5,
            20: 5,
            19: -4,
        },
        "antigates": {},
        "channels": {
            (20, 34): 4,
        },
        "antichannels": {
            (16, 48): 5
        },
        "centers": {},
        "anticenters": {},
        "profiles": {},
        "antiprofiles": {},
        "authorities": {
            "Splenic": -3,
        },
        "antiauthorities": {
            "Splenic": 8
        },
        "bazisigns": {},
        "antibazisigns": {},
        "color": "#cc99ff",
        "motivation": "",
        "description": "",
        "quotes": {},
    },
    "conflict_avoidant":{
     "name":"Conflict Avoidant",
        "signs":{"Capricorn":10,"Sagittarius":9,"Libra":7,"Gemini":4,"Cancer":4}, #Pretty sure Sagittarius is just trying not to go to jail...again. But maybe it's a specific nakshatra of Sag that's calling those shots. Also-- no pisces??
        "antisigns":{"Taurus":8,"Leo":6,"Scorpio":4},
        "houses":{5:6,11:4,4:3},
        "antihouses":{1:5,2:4},
        "bodies":{"Pluto":3}, #they've seen too much already...
        "antibodies":{},
        "nakshatras":{"Hasta":8,"Uttara Ashadha":5,"Dhanishta":5,"Uttara Bhadrapada":6,"Rohini":4,"Mrigashira":4,"Punarvasu":6,}, #ardra was 4 but i ignored it
        "antinakshatras":{"Pushya":3,"Swati":3,"Anuradha":4,"Mula":4,"Shravana":3,"Revati":5,},
        "positions":{"Sun in Pisces":6,"Sun in Leo":3,"Moon in Gemini":3,"Moon in Leo":4,"Moon in Aquarius":3,"Venus in Aquarius":5,"Venus in Cancer":3}, #not sure about sun in leo...
        "antipositions":{"Sun in Taurus":6,"Sun in Sagittarius":5,"Sun in Aquarius":4,"Moon in Virgo":8,"Moon in Capricorn":4,"Mercury in Scorpio":7,"Mercury in Capricorn":3,"Venus in Libra":4,"Venus in Scorpio":5,"Venus in Pisces":3,"Venus in Sagittarius":3},
        "aspects":{},
        "antiaspects":{},
        "gates":{},
        "antigates":{},
        "channels": {},
        "antichannels": {},
        "centers":{},
        "anticenters":{},
        "profiles":{},
        "antiprofiles":{},
        "authorities":{},
        "antiauthorities":{},
        "bazisigns":{},
        "antibazisigns":{},
        "color":"#cc99ff",
        "motivation":"",
        "description":"",
        "quotes":{""},
        },
    "sex_symbol":{
     "name":"Sex Symbol",
        "signs":{},
        "antisigns":{},
        "houses":{},
        "antihouses":{},
        "bodies":{},
        "antibodies":{},
        "nakshatras":{},
        "antinakshatras":{},
        "positions":{},
        "antipositions":{},
        "aspects":{},
        "antiaspects":{},
        "gates":{},
        "antigates":{},
        "channels": {},
        "antichannels": {},
        "centers":{},
        "anticenters":{},
        "profiles":{},
        "antiprofiles":{},
        "authorities":{},
        "antiauthorities":{},
        "bazisigns":{},
        "antibazisigns":{},
        "color":"#cc99ff",
        "motivation":"",
        "description":"",
        "quotes":{""},
        },
    "placeholder":{
     "name":"Placeholder",
        "signs":{},
        "antisigns":{},
        "houses":{},
        "antihouses":{},
        "bodies":{},
        "antibodies":{},
        "nakshatras":{},
        "antinakshatras":{},
        "positions":{},
        "antipositions":{},
        "aspects":{},
        "antiaspects":{},
        "gates":{},
        "antigates":{},
        "channels": {},
        "antichannels": {},
        "centers":{},
        "anticenters":{},
        "profiles":{},
        "antiprofiles":{},
        "authorities":{},
        "antiauthorities":{},
        "bazisigns":{},
        "antibazisigns":{},
        "color":"#cc99ff",
        "motivation":"",
        "description":"",
        "quotes":{""},
        },
}