#!/usr/bin/env python3
"""Regenerate packaging files from ``ephemeraldaddy.version``."""

from __future__ import annotations

import argparse
import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION_SOURCE = ROOT / "ephemeraldaddy" / "version.py"
WINDOWS_VERSION_INCLUDE = ROOT / "packaging" / "windows" / "version.iss"


def read_version() -> str:
    tree = ast.parse(VERSION_SOURCE.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == "__version__"
            for target in node.targets
        ):
            if isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
                return node.value.value
    raise RuntimeError(f"No literal __version__ found in {VERSION_SOURCE}")


def rendered_files() -> dict[Path, str]:
    version = read_version()
    return {
        WINDOWS_VERSION_INCLUDE: (
            "; Generated by tools/sync_release_version.py; do not edit.\n"
            f'#define MyAppVersion "{version}"\n'
        )
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated files are stale")
    args = parser.parse_args()
    stale: list[Path] = []
    for path, content in rendered_files().items():
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        stale.append(path)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if args.check and stale:
        print("Stale generated version files:", *(path.relative_to(ROOT) for path in stale))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

